IAR Library: Lib::System::HardwareVersion Class Reference
Lib::System::HardwareVersion Class Reference
HardwareVersion class.
Public Member Functions
HardwareVersion (const std::string &versionString, uint32_t subVersion)
Constructor of the HardwareVersion class.
~HardwareVersion () override=default
Destructor of HardwareVersion class.
uint32_t getValue () const override
Retrieves hardware version value.
uint32_t getSubVersion () const override
Retrieves sub-version value.
std::string toString () const override
Converts hardware version to string.
operator uint32_t () const override
Conversion operator to uint32_t.
operator std::string () const override
Conversion operator to std::string.
Static Protected Member Functions
static uint32_t stringToU32 (const std::string &versionString)
Converts a version string to a 32-bit unsigned integer.
Detailed Description
HardwareVersion class.
Represents hardware version and sub-version, extending VersionBase. Provides accessors and conversion operators for version and sub-version retrieval, ensuring type safety and input validation for embedded hardware version management.
Examples
Lib::System::HardwareVersion.
Constructor & Destructor Documentation
HardwareVersion()
Lib::System::HardwareVersion::HardwareVersion (const std::string & versionString, uint32_t subVersion) inline
Constructor of the HardwareVersion class.
Parameters
versionString Hardware version string.
subVersion Sub-version value.
~HardwareVersion()
Lib::System::HardwareVersion::~HardwareVersion () override default
Destructor of HardwareVersion class.
Member Function Documentation
getSubVersion()
uint32_t Lib::System::HardwareVersion::getSubVersion () const inline override virtual
Retrieves sub-version value.
Returns
Sub-version value as uint32_t.
Reimplemented from Lib::System::VersionBase.
Examples
Lib::System::HardwareVersion.
getValue()
uint32_t Lib::System::HardwareVersion::getValue () const inline override virtual
Retrieves hardware version value.
Returns
Hardware version value as uint32_t.
Reimplemented from Lib::System::VersionBase.
Referenced by operator uint32_t().
operator std::string()
Lib::System::HardwareVersion::operator std::string () const inline override virtual
Conversion operator to std::string.
Returns
Hardware version as std::string.
Reimplemented from Lib::System::VersionBase.
operator uint32_t()
Lib::System::HardwareVersion::operator uint32_t () const inline override virtual
Conversion operator to uint32_t.
Returns
Hardware version as uint32_t.
Reimplemented from Lib::System::VersionBase.
stringToU32()
uint32_t Lib::System::VersionBase::stringToU32 (const std::string & versionString) inline static protected inherited
Converts a version string to a 32-bit unsigned integer.
Parameters
versionString Version string in the format "X.Y".
Returns
32-bit unsigned integer representing the version.
Precondition
versionString must be in the format "X.Y" where X and Y are integers in [0,255].
Exceptions
std::invalid_argument if the input format is invalid or out of range.
Referenced by VersionBase().
toString()
std::string Lib::System::HardwareVersion::toString () const inline override virtual
Converts hardware version to string.
Returns
Hardware version as std::string.
Reimplemented from Lib::System::VersionBase.
Examples
Lib::System::HardwareVersion.
Referenced by operator std::string().