IAR Library: RTOS::Timeout Class Reference
RTOS::Timeout Class Reference
Timeout class for managing tick-based timeouts in FreeRTOS.
Public Types
using TickType = TickCounter::TickType
Public Member Functions
Timeout ()
Constructor of Timeout class.
Timeout (TickType ticks)
Constructor of Timeout class.
void set (TickType ticks)
Set timeout duration in ticks.
void setMilliseconds (uint32_t ms)
Set timeout duration in milliseconds.
void setSeconds (uint32_t sec)
Set timeout duration in seconds.
bool isExpired () const
Check if timeout has expired.
void reset ()
Reset the timeout to start from current tick.
TickType getRemaining () const
Get remaining time in ticks.
uint32_t getRemainingMs () const
Get remaining time in milliseconds.
TickType getElapsed () const
Get elapsed time in ticks since timeout started.
uint32_t getElapsedMs () const
Get elapsed time in milliseconds since timeout started.
uint32_t getProgressPercent () const
Get progress percentage of timeout.
Timeout & operator= (TickType ticks)
Assignment operator of Timeout class.
bool operator== (bool expired) const
Equality operator of Timeout class.
bool operator!= (bool expired) const
Inequality operator of Timeout class.
Timeout & operator+= (TickType ticks)
Addition assignment operator of Timeout class.
Timeout & operator-= (TickType ticks)
Subtraction assignment operator of Timeout class.
operator TickType () const
Conversion operator to TickType.
operator bool () const
Explicit conversion operator to bool.
void disable ()
Disable the timeout.
bool isDisabled () const
Check if timeout is disabled.
bool isActive () const
Check if timeout is active.
TickType getDuration () const
Get timeout duration in ticks.
uint32_t getDurationMs () const
Get timeout duration in milliseconds.
TickType getStartTicks () const
Get start tick value.
void extend (TickType ticks)
Extend timeout by specified ticks.
void extendMs (uint32_t ms)
Extend timeout by specified milliseconds.
bool willExpireWithin (TickType ticks) const
Check if timeout will expire within specified ticks.
bool willExpireWithinMs (uint32_t ms) const
Check if timeout will expire within specified milliseconds.
Static Public Member Functions
static Timeout fromMilliseconds (uint32_t ms)
Create Timeout from milliseconds.
static Timeout fromSeconds (uint32_t sec)
Create Timeout from seconds.
static Timeout immediate ()
Create an immediate timeout.
static Timeout disabled ()
Create a disabled timeout.
Static Public Attributes
static constexpr TickType DISABLED = portMAX_DELAY
static constexpr TickType IMMEDIATE = 0
Detailed Description
Timeout class for managing tick-based timeouts in FreeRTOS.
Provides methods for setting, extending, resetting, and querying timeouts in ticks, milliseconds, and seconds. Supports disabled and immediate timeouts, and offers conversion and status utilities.
Examples
RTOS::Timeout.
Constructor & Destructor Documentation
Timeout() [1/2]
RTOS::Timeout::Timeout () inline
Constructor of Timeout class.
Referenced by disabled(), fromMilliseconds(), fromSeconds(), immediate(), operator+=(), operator-=(), and operator=().
Timeout() [2/2]
RTOS::Timeout::Timeout (TickType ticks) inline explicit
Constructor of Timeout class.
Parameters
ticks Timeout duration in ticks.
Member Function Documentation
disable()
void RTOS::Timeout::disable () inline
Disable the timeout.
Referenced by set().
disabled()
Timeout RTOS::Timeout::disabled () inline static
Create a disabled timeout.
Returns
Timeout object that is disabled.
extend()
void RTOS::Timeout::extend (TickType ticks) inline
Extend timeout by specified ticks.
Parameters
ticks Number of ticks to extend.
Referenced by extendMs().
extendMs()
void RTOS::Timeout::extendMs (uint32_t ms) inline
Extend timeout by specified milliseconds.
Parameters
ms Number of milliseconds to extend.
Examples
RTOS::Timeout.
fromMilliseconds()
Timeout RTOS::Timeout::fromMilliseconds (uint32_t ms) inline static
Create Timeout from milliseconds.
Parameters
ms Timeout duration in milliseconds.
Returns
Timeout object with specified duration.
Examples
RTOS::Timeout.
fromSeconds()
Timeout RTOS::Timeout::fromSeconds (uint32_t sec) inline static
Create Timeout from seconds.
Parameters
sec Timeout duration in seconds.
Returns
Timeout object with specified duration.
getDuration()
TickType RTOS::Timeout::getDuration () const inline
Get timeout duration in ticks.
Returns
Timeout duration in ticks.
Referenced by RTOS::Semaphore::take(), and RTOS::EventGroup::waitForBits().
getDurationMs()
uint32_t RTOS::Timeout::getDurationMs () const inline
Get timeout duration in milliseconds.
Returns
Timeout duration in milliseconds.
getElapsed()
TickType RTOS::Timeout::getElapsed () const inline
Get elapsed time in ticks since timeout started.
Returns
Elapsed ticks since timeout started.
Referenced by getElapsedMs(), and getProgressPercent().
getElapsedMs()
uint32_t RTOS::Timeout::getElapsedMs () const inline
Get elapsed time in milliseconds since timeout started.
Returns
Elapsed milliseconds since timeout started.
getProgressPercent()
uint32_t RTOS::Timeout::getProgressPercent () const inline
Get progress percentage of timeout.
Returns
Progress percentage (0-100).
getRemaining()
TickType RTOS::Timeout::getRemaining () const inline
Get remaining time in ticks.
Returns
Remaining ticks until timeout expires.
Referenced by getRemainingMs(), and willExpireWithin().
getRemainingMs()
uint32_t RTOS::Timeout::getRemainingMs () const inline
Get remaining time in milliseconds.
Returns
Remaining milliseconds until timeout expires.
Examples
RTOS::Timeout.
getStartTicks()
TickType RTOS::Timeout::getStartTicks () const inline
Get start tick value.
Returns
Tick value when timeout was started.
immediate()
Timeout RTOS::Timeout::immediate () inline static
Create an immediate timeout.
Returns
Timeout object that is immediately expired.
isActive()
bool RTOS::Timeout::isActive () const inline
Check if timeout is active.
Returns
true if timeout is active, false otherwise.
Referenced by operator bool().
isDisabled()
bool RTOS::Timeout::isDisabled () const inline
Check if timeout is disabled.
Returns
true if timeout is disabled, false otherwise.
Referenced by extend(), getElapsed(), getProgressPercent(), getRemaining(), isActive(), isExpired(), operator+=(), operator-=(), reset(), RTOS::Semaphore::take(), RTOS::EventGroup::waitForBits(), and willExpireWithin().
isExpired()
bool RTOS::Timeout::isExpired () const inline
Check if timeout has expired.
Returns
true if timeout has expired, false otherwise.
Examples
RTOS::Timeout.
Referenced by operator!=(), operator==(), Lib::BSP::Ethercat::PDI::LAN9252::Base::resetChip(), and Lib::Digi::API::Service::NetworkDiscovery::start().
operator bool()
RTOS::Timeout::operator bool () const inline explicit
Explicit conversion operator to bool.
Returns
true if timeout is active, false otherwise.
operator TickType()
RTOS::Timeout::operator TickType () const inline
Conversion operator to TickType.
operator!=()
bool RTOS::Timeout::operator!= (bool expired) const inline
Inequality operator of Timeout class.
Parameters
expired Expired state to compare.
Returns
true if expired state does not match, false otherwise.
operator+=()
Timeout & RTOS::Timeout::operator+= (TickType ticks) inline
Addition assignment operator of Timeout class.
Parameters
ticks Number of ticks to add to duration.
Returns
Reference to this object.
operator-=()
Timeout & RTOS::Timeout::operator-= (TickType ticks) inline
Subtraction assignment operator of Timeout class.
Parameters
ticks Number of ticks to subtract from duration.
Returns
Reference to this object.
operator=()
Timeout & RTOS::Timeout::operator= (TickType ticks) inline
Assignment operator of Timeout class.
Parameters
ticks Timeout duration in ticks.
Returns
Reference to this object.
operator==()
bool RTOS::Timeout::operator== (bool expired) const inline
Equality operator of Timeout class.
Parameters
expired Expired state to compare.
Returns
true if expired state matches, false otherwise.
reset()
void RTOS::Timeout::reset () inline
Reset the timeout to start from current tick.
set()
void RTOS::Timeout::set (TickType ticks) inline
Set timeout duration in ticks.
Parameters
ticks Timeout duration in ticks.
Referenced by operator=(), Lib::BSP::Ethercat::PDI::LAN9252::Base::resetChip(), setMilliseconds(), setSeconds(), and Lib::Digi::API::Service::NetworkDiscovery::start().
setMilliseconds()
void RTOS::Timeout::setMilliseconds (uint32_t ms) inline
Set timeout duration in milliseconds.
Parameters
ms Timeout duration in milliseconds.
Examples
RTOS::Timeout.
setSeconds()
void RTOS::Timeout::setSeconds (uint32_t sec) inline
Set timeout duration in seconds.
Parameters
sec Timeout duration in seconds.
willExpireWithin()
bool RTOS::Timeout::willExpireWithin (TickType ticks) const inline
Check if timeout will expire within specified ticks.
Parameters
ticks Number of ticks to check.
Returns
true if timeout will expire within specified ticks, false otherwise.
Referenced by willExpireWithinMs().
willExpireWithinMs()
bool RTOS::Timeout::willExpireWithinMs (uint32_t ms) const inline
Check if timeout will expire within specified milliseconds.
Parameters
ms Number of milliseconds to check.
Returns
true if timeout will expire within specified milliseconds, false otherwise.
Member Data Documentation
DISABLED
TickType RTOS::Timeout::DISABLED = portMAX_DELAY static constexpr
Disabled timeout value.
Referenced by Timeout(), Timeout(), disable(), getDurationMs(), getRemaining(), getRemainingMs(), isDisabled(), and set().
IMMEDIATE
TickType RTOS::Timeout::IMMEDIATE = 0 static constexpr
Immediate timeout value.
Referenced by immediate().