IAR Library: CanFilter Class Reference
CanFilter Class Reference final
CAN filter wrapper class.
Public Member Functions
CanFilter ()
Constructor of the CanFilter class.
CanFilter (uint32_t id, uint32_t mask=std::numeric_limits< uint32_t >::max() > > 3)
Constructor of the CanFilter class.
~CanFilter ()=default
Destructor of the CanFilter class.
void enable (uint32_t value)
Enables the CAN filter.
void setId (uint32_t id)
Sets the filter identifier.
void setMask (uint32_t mask)
Sets the filter mask.
void setBank (uint32_t bank)
Sets the filter bank.
void setMode (uint32_t mode)
Sets the filter mode.
void setFilterActivation (bool isEnabled)
Sets the filter activation state.
void setSlaveStartFilterBank (uint32_t bank)
Sets the slave start filter bank.
void setFilterFIFOAssignment (uint32_t fifo)
Sets the filter FIFO assignment.
void setFilterScale (uint32_t scale)
Sets the filter scale.
operator CAN_FilterTypeDef * ()
Conversion operator to CAN_FilterTypeDef pointer.
operator const CAN_FilterTypeDef * () const
Conversion operator to const CAN_FilterTypeDef pointer.
Detailed Description
CAN filter wrapper class.
Provides a type-safe and convenient interface for configuring CAN hardware filters.
Constructor & Destructor Documentation
CanFilter() [1/2]
CanFilter::CanFilter () explicit
Constructor of the CanFilter class.
CanFilter() [2/2]
CanFilter::CanFilter (uint32_t id, uint32_t mask = std::numeric_limits< uint32_t >::max(), 3) explicit
Constructor of the CanFilter class.
Parameters
id Filter identifier.
mask Filter mask.
~CanFilter()
CanFilter::~CanFilter () default
Destructor of the CanFilter class.
Member Function Documentation
enable()
void CanFilter::enable (uint32_t value)
Enables the CAN filter.
Parameters
value Value to enable the filter.
operator CAN_FilterTypeDef *()
CanFilter::operator CAN_FilterTypeDef * ()
Conversion operator to CAN_FilterTypeDef pointer.
Returns
Pointer to CAN_FilterTypeDef.
operator const CAN_FilterTypeDef *()
CanFilter::operator const CAN_FilterTypeDef * () const
Conversion operator to const CAN_FilterTypeDef pointer.
Returns
Const pointer to CAN_FilterTypeDef.
setBank()
void CanFilter::setBank (uint32_t bank)
Sets the filter bank.
Parameters
bank Filter bank.
Referenced by Lib::Canbus::CanServiceBase::start().
setFilterActivation()
void CanFilter::setFilterActivation (bool isEnabled)
Sets the filter activation state.
Parameters
isEnabled true to enable the filter, false to disable.
setFilterFIFOAssignment()
void CanFilter::setFilterFIFOAssignment (uint32_t fifo)
Sets the filter FIFO assignment.
Parameters
fifo FIFO assignment.
setFilterScale()
void CanFilter::setFilterScale (uint32_t scale)
Sets the filter scale.
Parameters
scale Filter scale.
setId()
void CanFilter::setId (uint32_t id)
Sets the filter identifier.
Parameters
id Filter identifier.
Referenced by Lib::Canbus::CanServiceBase::start().
setMask()
void CanFilter::setMask (uint32_t mask)
Sets the filter mask.
Parameters
mask Filter mask.
Referenced by Lib::Canbus::CanServiceBase::start().
setMode()
void CanFilter::setMode (uint32_t mode)
Sets the filter mode.
Parameters
mode Filter mode.
setSlaveStartFilterBank()
void CanFilter::setSlaveStartFilterBank (uint32_t bank)
Sets the slave start filter bank.
Parameters
bank Slave start filter bank.