IAR Library: Lib::Digi::Core::ComDriver Class Reference
Lib::Digi::Core::ComDriver Class Reference abstract
ComDriver class for Digi XBee modules.
Classes
struct Config
Config struct for ComDriver configuration.
class UartPort
UartPort class for RX/TX UART port wrapper.
Public Member Functions
ComDriver (const Config &config)
Constructor of ComDriver class.
virtual ~ComDriver ()
Destructor of ComDriver class.
virtual bool init ()
Initializes the communication driver.
bool send (const ApiFrameBuffer *frameBuffer, uint32_t timeout)
Sends a DIGI API1 frame.
virtual void emitBeginMessageReceive ()=0
Begin of receive callback.
virtual void emitEndMessageReceived ()=0
End of receive callback.
virtual void emitBeginMessageSend ()=0
Emit begin send event.
virtual void emitEndMessageSend ()=0
Emit end of send event.
Protected Member Functions
virtual void reset ()
Hardware reset of XBee module.
Protected Attributes
Diagnostic diagnostic
PinOutput xrst
Detailed Description
ComDriver class for Digi XBee modules.
Handles UART communication, frame parsing, hardware reset, and event hooks for Digi XBee modules.
Constructor & Destructor Documentation
ComDriver()
Lib::Digi::Core::ComDriver::ComDriver (const Config & config) inline explicit
Constructor of ComDriver class.
Parameters
config Configuration for the communication driver.
Referenced by Lib::Digi::Core::Module::Module().
~ComDriver()
virtual Lib::Digi::Core::ComDriver::~ComDriver () inline virtual
Destructor of ComDriver class.
Member Function Documentation
emitBeginMessageReceive()
virtual void Lib::Digi::Core::ComDriver::emitBeginMessageReceive () pure virtual
Begin of receive callback.
emitBeginMessageSend()
virtual void Lib::Digi::Core::ComDriver::emitBeginMessageSend () pure virtual
Emit begin send event.
Referenced by send().
emitEndMessageReceived()
virtual void Lib::Digi::Core::ComDriver::emitEndMessageReceived () pure virtual
End of receive callback.
emitEndMessageSend()
virtual void Lib::Digi::Core::ComDriver::emitEndMessageSend () pure virtual
Emit end of send event.
Referenced by send().
init()
virtual bool Lib::Digi::Core::ComDriver::init () inline virtual
Initializes the communication driver.
Returns
true if initialization succeeds, false otherwise.
Reimplemented in Lib::Digi::Core::Module.
Referenced by Lib::Digi::Core::Module::init().
reset()
virtual void Lib::Digi::Core::ComDriver::reset () inline protected virtual
Hardware reset of XBee module.
Reimplemented in Lib::Digi::Core::Module.
Referenced by Lib::Digi::Core::Module::reset().
send()
bool Lib::Digi::Core::ComDriver::send (const ApiFrameBuffer * frameBuffer, uint32_t timeout) inline
Sends a DIGI API1 frame.
Parameters
frameBuffer Pointer to DIGI API1 frame.
timeout Timeout in milliseconds.
Returns
true if the frame was sent successfully, false otherwise.
Referenced by Lib::Digi::Core::Module::send().
Member Data Documentation
diagnostic
Diagnostic Lib::Digi::Core::ComDriver::diagnostic protected
Diagnostic reference.
Referenced by ComDriver().
xrst
PinOutput Lib::Digi::Core::ComDriver::xrst protected
Reset pin of XBee module.
Referenced by ComDriver(), and reset().