IAR Library: RTOS::Mutex Class Reference
RTOS::Mutex Class Reference
Mutex class for synchronization.
Classes
class LockGuard
LockGuard class for RAII locking.
Public Types
enum class MutexType : uint8_t {
NORMAL = 0 ,
RECURSIVE = 1
}
Mutex type enumeration.
Public Member Functions
Mutex (MutexType type=MutexType::NORMAL)
Constructor of Mutex class.
~Mutex ()
Destructor of Mutex class.
bool create ()
Create the mutex.
void destroy ()
Destroy the mutex.
Mutex (Mutex &&other) noexcept
Move constructor of Mutex class.
Mutex & operator= (Mutex &&other) noexcept
Move assignment operator of Mutex class.
bool lock (uint32_t timeout=WAIT_FOREVER)
Lock the mutex.
bool tryLock ()
Try to lock the mutex without waiting.
void unlock ()
Unlock the mutex.
bool isValid () const
Check if the mutex is valid.
SemaphoreHandle_t getNativeHandle () const
Get the native FreeRTOS handle.
MutexType getType () const
Get the mutex type.
Static Public Attributes
static constexpr uint32_t NO_WAIT = 0
No wait timeout constant.
static constexpr uint32_t WAIT_FOREVER = portMAX_DELAY
Wait forever timeout constant.
Detailed Description
Mutex class for synchronization.
Provides a wrapper around FreeRTOS semaphores for mutex functionality, supporting normal and recursive mutexes. Ensures thread-safe access to shared resources.
Examples
RTOS::Mutex, and RTOS::MutexGuard.
Member Enumeration Documentation
MutexType
enum class RTOS::Mutex::MutexType : uint8_t strong
Mutex type enumeration.
Defines the type of mutex: normal or recursive.
Enumerator
NORMAL
Normal mutex type.
RECURSIVE
Recursive mutex type.
Constructor & Destructor Documentation
Mutex() [1/2]
RTOS::Mutex::Mutex (MutexType type = MutexType::NORMAL) inline explicit
Constructor of Mutex class.
Parameters
type Type of the mutex (normal or recursive).
Referenced by RTOS::Mutex::LockGuard::LockGuard(), Mutex(), and operator=().
~Mutex()
RTOS::Mutex::~Mutex () inline
Destructor of Mutex class.
Destroys the mutex if it exists.
Mutex() [2/2]
RTOS::Mutex::Mutex (Mutex && other) inline noexcept
Move constructor of Mutex class.
Parameters
other Mutex to move from.
Member Function Documentation
create()
bool RTOS::Mutex::create () inline
Create the mutex.
Allocates and initializes the FreeRTOS semaphore based on the mutex type.
Returns
true if creation was successful, false otherwise.
destroy()
void RTOS::Mutex::destroy () inline
Destroy the mutex.
Deletes the FreeRTOS semaphore and resets the handle.
Referenced by ~Mutex(), and operator=().
getNativeHandle()
SemaphoreHandle_t RTOS::Mutex::getNativeHandle () const inline
Get the native FreeRTOS handle.
Returns
The native semaphore handle.
getType()
MutexType RTOS::Mutex::getType () const inline
Get the mutex type.
Returns
The type of the mutex.
isValid()
bool RTOS::Mutex::isValid () const inline
Check if the mutex is valid.
Returns
true if the mutex handle is valid, false otherwise.
lock()
bool RTOS::Mutex::lock (uint32_t timeout = WAIT_FOREVER) inline
Lock the mutex.
Attempts to take the mutex with a timeout.
Parameters
timeout Timeout in milliseconds.
Returns
true if the lock was acquired, false otherwise.
Referenced by RTOS::Mutex::LockGuard::LockGuard(), and tryLock().
operator=()
Mutex & RTOS::Mutex::operator= (Mutex && other) inline noexcept
Move assignment operator of Mutex class.
Parameters
other Mutex to move from.
Returns
Reference to this mutex.
tryLock()
bool RTOS::Mutex::tryLock () inline
Try to lock the mutex without waiting.
Returns
true if the lock was acquired, false otherwise.
unlock()
void RTOS::Mutex::unlock () inline
Unlock the mutex.
Releases the mutex.
Member Data Documentation
NO_WAIT
uint32_t RTOS::Mutex::NO_WAIT = 0 static constexpr
No wait timeout constant.
Referenced by tryLock().
WAIT_FOREVER
uint32_t RTOS::Mutex::WAIT_FOREVER = portMAX_DELAY static constexpr
Wait forever timeout constant.
Referenced by RTOS::Mutex::LockGuard::LockGuard(), and lock().