IAR Library: Lib::Ethernet::Wiznet::ClientBase Class Reference
Lib::Ethernet::Wiznet::ClientBase Class Reference abstract
TCP client base class for Wiznet Ethernet communication.
Public Types
enum class ConnectionState {
INIT ,
IDLE ,
CONNECTED ,
DISCONNECTED ,
INIT ,
IDLE ,
CONNECTED ,
DISCONNECTED
}
Connection state for Wiznet TCP client.
enum class ConnectionState {
INIT ,
IDLE ,
CONNECTED ,
DISCONNECTED ,
INIT ,
IDLE ,
CONNECTED ,
DISCONNECTED
}
Connection state for TCP client.
Protected Member Functions
ClientBase ()
Constructor of ClientBase class.
virtual ~ClientBase ()=default
Destructor of ClientBase class.
virtual void start ()
Start the TCP client task and initialize connection state.
virtual void handleIncomingMessage (const DataHandle<> &receivedDataHandle)=0
Handle incoming TCP message.
virtual bool handleOutgoingMessage (DataHandle<> &outgoingDataHandle)=0
Prepare outgoing TCP message.
virtual void handleConnectionStateChangedEvent (ConnectionState newState)=0
Handle connection state change event.
virtual void updateRxLedCallback (bool isRxLedOn)
Update RX LED indicator.
virtual void updateTxLedCallback (bool isTxLedOn)
Update TX LED indicator.
virtual void applicationLoopCallback ()
Application-specific loop callback.
virtual ConnectionState getConnectionState () const
Get current connection state.
void setConnectionState (ConnectionState newState)
Set connection state and trigger event if changed.
virtual bool readLinkState ()=0
Read physical link state.
virtual void initCallback ()=0
Initialization callback for client setup.
void setRemoteNode (const IpAddress &remoteIp, uint16_t remotePort)
Set remote node IP and port.
const Node & getRemoteNode ()
Get remote node information.
void taskFn ()
TCP client main task loop.
Socket::Error send (const DataHandle<> &dataHandleToSend, size_t dataSize)
Send data using socket.
ClientBase ()
Constructor of the ClientBase class.
virtual ~ClientBase ()=default
Destructor of the ClientBase class.
virtual void start ()
Start the client task and initialize state.
virtual void handleIncomingMessage (const DataHandle<> &data)=0
Handle incoming message.
virtual bool handleOutgoingMessage (DataHandle<> &data)=0
Handle outgoing message.
virtual void handleConnectionStateChangedEvent (ConnectionState state)=0
Handle connection state change event.
virtual void updateRxLedCallback (bool isActive)
Update RX LED callback.
virtual void updateTxLedCallback (bool isActive)
Update TX LED callback.
virtual void handleApplicationProcess ()
Application loop callback.
virtual ConnectionState getConnectionState () const
Get current connection state.
void setConnectionState (ConnectionState state)
Set connection state and trigger event if changed.
virtual bool readLinkState ()=0
Read link state.
virtual void initCallback ()=0
Initialization callback.
void setRemoteNode (const IpAddress &ip, uint16_t port)
Set remote node IP and port.
const Node & getRemoteNode ()
Get remote node.
void taskFn ()
Client task function.
Socket::Error send (const DataHandle<> &data, size_t length)
Send data using socket.
Detailed Description
TCP client base class for Wiznet Ethernet communication.
Provides connection state management, message handling, and diagnostic tracking.
Member Enumeration Documentation
ConnectionState [1/2]
enum class Lib::Ethernet::Wiznet::ClientBase::ConnectionState strong
Connection state for Wiznet TCP client.
Enumerator
INIT
Initial state.
IDLE
Idle state.
CONNECTED
Connected state.
DISCONNECTED
Disconnected state.
ConnectionState [2/2]
enum class Lib::Ethernet::Wiznet::ClientBase::ConnectionState strong
Connection state for TCP client.
Enumerator
INIT
Initial state.
IDLE
Idle state.
CONNECTED
Connected state.
DISCONNECTED
Disconnected state.
Constructor & Destructor Documentation
ClientBase() [1/2]
Lib::Ethernet::Wiznet::ClientBase::ClientBase () inline protected
Constructor of ClientBase class.
~ClientBase() [1/2]
virtual Lib::Ethernet::Wiznet::ClientBase::~ClientBase () protected virtual default
Destructor of ClientBase class.
ClientBase() [2/2]
Lib::Ethernet::Wiznet::ClientBase::ClientBase () inline protected
Constructor of the ClientBase class.
~ClientBase() [2/2]
virtual Lib::Ethernet::Wiznet::ClientBase::~ClientBase () protected virtual default
Destructor of the ClientBase class.
Member Function Documentation
applicationLoopCallback()
virtual void Lib::Ethernet::Wiznet::ClientBase::applicationLoopCallback () inline protected virtual
Application-specific loop callback.
Referenced by taskFn().
getConnectionState() [1/2]
virtual ConnectionState Lib::Ethernet::Wiznet::ClientBase::getConnectionState () const inline protected virtual
Get current connection state.
Returns
Current ConnectionState.
Referenced by taskFn().
getConnectionState() [2/2]
virtual ConnectionState Lib::Ethernet::Wiznet::ClientBase::getConnectionState () const inline protected virtual
Get current connection state.
Returns
Current connection state.
getRemoteNode() [1/2]
const Node & Lib::Ethernet::Wiznet::ClientBase::getRemoteNode () inline protected
Get remote node information.
Returns
Reference to remote Node.
getRemoteNode() [2/2]
const Node & Lib::Ethernet::Wiznet::ClientBase::getRemoteNode () inline protected
Get remote node.
Returns
Remote node.
handleApplicationProcess()
virtual void Lib::Ethernet::Wiznet::ClientBase::handleApplicationProcess () inline protected virtual
Application loop callback.
Referenced by taskFn().
handleConnectionStateChangedEvent() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::handleConnectionStateChangedEvent (ConnectionState newState) protected pure virtual
Handle connection state change event.
Parameters
newState New connection state.
Precondition
newState must be a valid ConnectionState.
Postcondition
State change processed.
Referenced by setConnectionState(), and setConnectionState().
handleConnectionStateChangedEvent() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::handleConnectionStateChangedEvent (ConnectionState state) protected pure virtual
Handle connection state change event.
Parameters
state New connection state.
handleIncomingMessage() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::handleIncomingMessage (const DataHandle<> & data) protected pure virtual
Handle incoming message.
Parameters
data Incoming data handle.
handleIncomingMessage() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::handleIncomingMessage (const DataHandle<> & receivedDataHandle) protected pure virtual
Handle incoming TCP message.
Parameters
receivedDataHandle Data handle for received message.
Precondition
receivedDataHandle must be valid.
Postcondition
Message processed.
Referenced by taskFn().
handleOutgoingMessage() [1/2]
virtual bool Lib::Ethernet::Wiznet::ClientBase::handleOutgoingMessage (DataHandle<> & data) protected pure virtual
Handle outgoing message.
Parameters
data Outgoing data handle.
Returns
true if message should be sent, false otherwise.
handleOutgoingMessage() [2/2]
virtual bool Lib::Ethernet::Wiznet::ClientBase::handleOutgoingMessage (DataHandle<> & outgoingDataHandle) protected pure virtual
Prepare outgoing TCP message.
Parameters
[out] outgoingDataHandle Data handle for outgoing message.
Returns
true if message is ready to send, false otherwise.
Precondition
outgoingDataHandle must be valid if true is returned.
Postcondition
Message sent if true is returned.
Referenced by taskFn().
initCallback() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::initCallback () protected pure virtual
Initialization callback for client setup.
Referenced by taskFn().
initCallback() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::initCallback () protected pure virtual
Initialization callback.
readLinkState() [1/2]
virtual bool Lib::Ethernet::Wiznet::ClientBase::readLinkState () protected pure virtual
Read physical link state.
Returns
true if link is up, false otherwise.
Referenced by taskFn().
readLinkState() [2/2]
virtual bool Lib::Ethernet::Wiznet::ClientBase::readLinkState () protected pure virtual
Read link state.
Returns
true if link is up, false otherwise.
send() [1/2]
Socket::Error Lib::Ethernet::Wiznet::ClientBase::send (const DataHandle<> & data, size_t length) inline protected
Send data using socket.
Parameters
data Data handle to send.
length Number of bytes to send.
Returns
Socket error code.
send() [2/2]
Socket::Error Lib::Ethernet::Wiznet::ClientBase::send (const DataHandle<> & dataHandleToSend, size_t dataSize) inline protected
Send data using socket.
Parameters
dataHandleToSend Data handle to send.
dataSize Size of data.
Returns
Socket error code.
Precondition
dataHandleToSend must be valid; dataSize must be > 0.
Postcondition
Data sent if error code is OK.
Referenced by taskFn().
setConnectionState() [1/2]
void Lib::Ethernet::Wiznet::ClientBase::setConnectionState (ConnectionState newState) inline protected
Set connection state and trigger event if changed.
Parameters
newState New connection state.
Precondition
newState must be a valid ConnectionState.
Postcondition
State updated and event triggered if changed.
Referenced by start(), and taskFn().
setConnectionState() [2/2]
void Lib::Ethernet::Wiznet::ClientBase::setConnectionState (ConnectionState state) inline protected
Set connection state and trigger event if changed.
Parameters
state New connection state.
setRemoteNode() [1/2]
void Lib::Ethernet::Wiznet::ClientBase::setRemoteNode (const IpAddress & ip, uint16_t port) inline protected
Set remote node IP and port.
Parameters
ip Remote IP address.
port Remote port.
setRemoteNode() [2/2]
void Lib::Ethernet::Wiznet::ClientBase::setRemoteNode (const IpAddress & remoteIp, uint16_t remotePort) inline protected
Set remote node IP and port.
Parameters
remoteIp Remote IP address.
remotePort Remote port.
Precondition
remoteIp must be valid; remotePort must be in valid range.
Postcondition
Remote node updated.
start() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::start () inline protected virtual
Start the TCP client task and initialize connection state.
Precondition
FreeRTOS::Task::run must succeed; asserts on failure.
Postcondition
TCP client task is running.
start() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::start () inline protected virtual
Start the client task and initialize state.
taskFn() [1/2]
void Lib::Ethernet::Wiznet::ClientBase::taskFn () inline protected
TCP client main task loop.
Referenced by start().
taskFn() [2/2]
void Lib::Ethernet::Wiznet::ClientBase::taskFn () inline protected
Client task function.
updateRxLedCallback() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::updateRxLedCallback (bool isActive) inline protected virtual
Update RX LED callback.
Parameters
isActive RX LED state.
updateRxLedCallback() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::updateRxLedCallback (bool isRxLedOn) inline protected virtual
Update RX LED indicator.
Parameters
isRxLedOn LED state.
Referenced by start(), and taskFn().
updateTxLedCallback() [1/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::updateTxLedCallback (bool isActive) inline protected virtual
Update TX LED callback.
Parameters
isActive TX LED state.
updateTxLedCallback() [2/2]
virtual void Lib::Ethernet::Wiznet::ClientBase::updateTxLedCallback (bool isTxLedOn) inline protected virtual
Update TX LED indicator.
Parameters
isTxLedOn LED state.
Referenced by start(), and taskFn().