IAR Library: Lib::Digi::API::Service::ServiceBase Class Reference
Lib::Digi::API::Service::ServiceBase Class Reference
Base class for Digi API services.
Protected Member Functions
ServiceBase ()=default
Constructor of ServiceBase class.
virtual ~ServiceBase ()=default
Destructor of ServiceBase class.
virtual bool open ()
Opens the service.
virtual void close ()
Closes the service.
bool isServiceOpen () const
Checks if the service is open.
virtual void beginUpdate ()
Initializes the service.
virtual void update ()
Updates the service.
virtual void endUpdate ()
Called after the service is closed.
Protected Attributes
bool isOpen {false}
bool hasClosed {false}
bool isFirstUpdate {false}
Friends
class Manager
Detailed Description
Base class for Digi API services.
The ServiceBase class provides a common interface and lifecycle management for all service classes in the Digi API. It supports open/close state management, update cycles, and integration with service managers. The class is designed for embedded Digi modules, enabling robust service management, error handling, and maintainable, type-safe service development.
Constructor & Destructor Documentation
ServiceBase()
Lib::Digi::API::Service::ServiceBase::ServiceBase () protected default
Constructor of ServiceBase class.
~ServiceBase()
virtual Lib::Digi::API::Service::ServiceBase::~ServiceBase () protected virtual default
Destructor of ServiceBase class.
Member Function Documentation
beginUpdate()
virtual void Lib::Digi::API::Service::ServiceBase::beginUpdate () inline protected virtual
Initializes the service.
Called once after opening.
Reimplemented in Lib::Digi::API::Service::Parameters, and Lib::Digi::API::Service::SpectrumAnalyzer.
close()
virtual void Lib::Digi::API::Service::ServiceBase::close () inline protected virtual
Closes the service.
Reimplemented in Lib::Digi::API::Service::ChannelScanner, Lib::Digi::API::Service::NetworkDiscovery, Lib::Digi::API::Service::Parameters, and Lib::Digi::API::Service::SpectrumAnalyzer.
Referenced by Lib::Digi::API::Service::ChannelScanner::close(), Lib::Digi::API::Service::NetworkDiscovery::close(), Lib::Digi::API::Service::Parameters::close(), and Lib::Digi::API::Service::SpectrumAnalyzer::close().
endUpdate()
virtual void Lib::Digi::API::Service::ServiceBase::endUpdate () inline protected virtual
Called after the service is closed.
Reimplemented in Lib::Digi::API::Service::Parameters, and Lib::Digi::API::Service::SpectrumAnalyzer.
isServiceOpen()
bool Lib::Digi::API::Service::ServiceBase::isServiceOpen () const inline protected
Checks if the service is open.
Returns
true if the service is open, false otherwise.
Referenced by Lib::Digi::API::Service::ChannelScanner::update().
open()
virtual bool Lib::Digi::API::Service::ServiceBase::open () inline protected virtual
Opens the service.
Returns
true if the service was opened successfully, false otherwise.
Reimplemented in Lib::Digi::API::Service::ChannelScanner, Lib::Digi::API::Service::NetworkDiscovery, Lib::Digi::API::Service::Parameters, and Lib::Digi::API::Service::SpectrumAnalyzer.
Referenced by Lib::Digi::API::Service::ChannelScanner::open(), Lib::Digi::API::Service::NetworkDiscovery::open(), Lib::Digi::API::Service::Parameters::open(), and Lib::Digi::API::Service::SpectrumAnalyzer::open().
update()
virtual void Lib::Digi::API::Service::ServiceBase::update () inline protected virtual
Updates the service.
Called periodically.
Reimplemented in Lib::Digi::API::Service::ChannelScanner, Lib::Digi::API::Service::NetworkDiscovery, Lib::Digi::API::Service::Parameters, and Lib::Digi::API::Service::SpectrumAnalyzer.
Member Data Documentation
hasClosed
bool Lib::Digi::API::Service::ServiceBase::hasClosed {false} protected
Indicates if the service has been closed.
Referenced by close(), and open().
isFirstUpdate
bool Lib::Digi::API::Service::ServiceBase::isFirstUpdate {false} protected
Indicates if this is the first update call.
Referenced by open().
isOpen
bool Lib::Digi::API::Service::ServiceBase::isOpen {false} protected
Indicates if the service is open.
Referenced by isServiceOpen(), and open().