IAR Library: RTOS::Task Class Reference
RTOS::Task Class Reference final
Task class for FreeRTOS thread management.
Classes
struct Data
Data structure for task properties.
Public Types
enum class NotifyAction : uint32_t {
NO_ACTION = eNoAction ,
SET_BITS = eSetBits ,
INCREMENT = eIncrement ,
SET_VALUE_WITH_OVERWRITE = eSetValueWithOverwrite ,
SET_VALUE_WITHOUT_OVERWRITE = eSetValueWithoutOverwrite
}
Notification action enumeration.
using Handle = TaskHandle_t
using NotificationBits = std::bitset<32>
Public Member Functions
Task (size_t stackSize=DEFAULT_STACK_SIZE, UBaseType_t priority=DEFAULT_TASK_PRIORITY)
Constructor of Task class.
Task (const std::string &name, size_t stackSize=DEFAULT_STACK_SIZE, UBaseType_t priority=DEFAULT_TASK_PRIORITY)
Constructor of Task class.
Task (Handle handle)
Constructor of Task class from handle.
Task (const Task &other)=delete
Copy constructor of Task class.
Task (Task &&other)=default
Move constructor of Task class.
Task & operator= (const Task &other)=delete
Copy assignment operator of Task class.
Task & operator= (Task &&other)=default
Move assignment operator of Task class.
~Task ()=default
Destructor of Task class.
bool operator== (const Task &other) const
Equality operator of Task class.
bool operator!= (const Task &other) const
Inequality operator of Task class.
Handle start (std::function< void()> func)
Starts the task with the given function.
void stop ()
Stops the task.
Handle getHandle () const
Gets the task handle.
operator Handle () const
Conversion operator to Handle.
void suspend ()
Suspends the task.
void resume ()
Resumes the task.
UBaseType_t getPriority () const
Gets the task priority.
void setPriority (UBaseType_t priority)
Sets the task priority.
BaseType_t resumeFromISR ()
Resumes the task from ISR.
eTaskState getState () const
Gets the task state.
bool isRunning () const
Checks if the task is running.
bool isSuspended () const
Checks if the task is suspended.
bool isReady () const
Checks if the task is ready.
bool isBlocked () const
Checks if the task is blocked.
bool isValid () const
Checks if the task handle is valid.
const std::string & getName () const
Gets the task name.
size_t getStackSize () const
Gets the stack size.
UBaseType_t getStackHighWaterMark () const
Gets the stack high water mark.
Static Public Member Functions
static void yield ()
Yields the current task.
static void sleep (uint32_t ms)
Sleeps the current task for the specified milliseconds.
static void delay (uint32_t ms)
Delays the current task for the specified milliseconds.
static void delayTicks (TickType_t ticks)
Delays the current task for the specified number of ticks.
Static Public Attributes
static constexpr UBaseType_t DEFAULT_TASK_PRIORITY = tskIDLE_PRIORITY
static constexpr size_t MIN_STACK_SIZE = configMINIMAL_STACK_SIZE
static constexpr size_t DEFAULT_STACK_SIZE = configMINIMAL_STACK_SIZE * 4
Detailed Description
Task class for FreeRTOS thread management.
Provides a C++17 abstraction for FreeRTOS task creation, control, and notification. Supports safe resource management, priority and stack configuration, and notification APIs.
See also
https://github.com/panchev68-Library/IAR/blob/3.03/inc/Lib/RTOS/doc/Task.md
Examples
RTOS::Task.
Member Typedef Documentation
Handle
using RTOS::Task::Handle = TaskHandle_t
Alias for FreeRTOS task handle.
Examples
RTOS::Task.
NotificationBits
using RTOS::Task::NotificationBits = std::bitset<32>
Type for notification bits.
Member Enumeration Documentation
NotifyAction
enum class RTOS::Task::NotifyAction : uint32_t strong
Notification action enumeration.
Enumerates the possible notification actions for FreeRTOS task notifications.
Enumerator
NO_ACTION
No action.
SET_BITS
Set bits.
INCREMENT
Increment value.
SET_VALUE_WITH_OVERWRITE
Set value with overwrite.
SET_VALUE_WITHOUT_OVERWRITE
Set value without overwrite.
Constructor & Destructor Documentation
Task() [1/5]
RTOS::Task::Task (size_t stackSize = DEFAULT_STACK_SIZE, UBaseType_t priority = DEFAULT_TASK_PRIORITY) inline explicit
Constructor of Task class.
Parameters
stackSize Stack size.
priority Task priority.
Referenced by Task(), Task(), operator!=(), operator=(), operator=(), and operator==().
Task() [2/5]
RTOS::Task::Task (const std::string & name, size_t stackSize = DEFAULT_STACK_SIZE, UBaseType_t priority = DEFAULT_TASK_PRIORITY) inline
Constructor of Task class.
Parameters
name Task name.
stackSize Stack size.
priority Task priority.
Task() [3/5]
RTOS::Task::Task (Handle handle) inline explicit
Constructor of Task class from handle.
Parameters
handle Task handle.
Task() [4/5]
RTOS::Task::Task (const Task & other) delete
Copy constructor of Task class.
Parameters
other Task object to copy.
Task() [5/5]
RTOS::Task::Task (Task && other) default
Move constructor of Task class.
Parameters
other Task object to move.
~Task()
RTOS::Task::~Task () default
Destructor of Task class.
Member Function Documentation
delay()
void RTOS::Task::delay (uint32_t ms) inline static
Delays the current task for the specified milliseconds.
Parameters
ms Milliseconds to delay.
Examples
RTOS::Task.
delayTicks()
void RTOS::Task::delayTicks (TickType_t ticks) inline static
Delays the current task for the specified number of ticks.
Parameters
ticks Number of ticks to delay.
Referenced by RTOS::TickService::start().
getHandle()
Handle RTOS::Task::getHandle () const inline
Gets the task handle.
Returns
Task handle.
Referenced by operator Handle().
getName()
const std::string & RTOS::Task::getName () const inline
Gets the task name.
Returns
Task name.
getPriority()
UBaseType_t RTOS::Task::getPriority () const inline
Gets the task priority.
Returns
Task priority.
getStackHighWaterMark()
UBaseType_t RTOS::Task::getStackHighWaterMark () const inline
Gets the stack high water mark.
Returns
Stack high water mark.
getStackSize()
size_t RTOS::Task::getStackSize () const inline
Gets the stack size.
Returns
Stack size.
getState()
eTaskState RTOS::Task::getState () const inline
Gets the task state.
Returns
Task state.
Referenced by isBlocked(), isReady(), isRunning(), and isSuspended().
isBlocked()
bool RTOS::Task::isBlocked () const inline
Checks if the task is blocked.
Returns
true if blocked, false otherwise.
isReady()
bool RTOS::Task::isReady () const inline
Checks if the task is ready.
Returns
true if ready, false otherwise.
isRunning()
bool RTOS::Task::isRunning () const inline
Checks if the task is running.
Returns
true if running, false otherwise.
isSuspended()
bool RTOS::Task::isSuspended () const inline
Checks if the task is suspended.
Returns
true if suspended, false otherwise.
isValid()
bool RTOS::Task::isValid () const inline
Checks if the task handle is valid.
Returns
true if valid, false otherwise.
operator Handle()
RTOS::Task::operator Handle () const inline
Conversion operator to Handle.
Returns
Task handle.
operator!=()
bool RTOS::Task::operator!= (const Task & other) const inline
Inequality operator of Task class.
Parameters
other Task object to compare.
Returns
true if not equal, false otherwise.
operator=() [1/2]
Task & RTOS::Task::operator= (const Task & other) delete
Copy assignment operator of Task class.
Parameters
other Task object to copy.
Returns
Reference to this object.
operator=() [2/2]
Task & RTOS::Task::operator= (Task && other) default
Move assignment operator of Task class.
Parameters
other Task object to move.
Returns
Reference to this object.
operator==()
bool RTOS::Task::operator== (const Task & other) const inline
Equality operator of Task class.
Parameters
other Task object to compare.
Returns
true if equal, false otherwise.
resume()
void RTOS::Task::resume () inline
Resumes the task.
resumeFromISR()
BaseType_t RTOS::Task::resumeFromISR () inline
Resumes the task from ISR.
Returns
pdTRUE if resumed, pdFALSE otherwise.
setPriority()
void RTOS::Task::setPriority (UBaseType_t priority) inline
Sets the task priority.
Parameters
priority Task priority.
sleep()
void RTOS::Task::sleep (uint32_t ms) inline static
Sleeps the current task for the specified milliseconds.
Parameters
ms Milliseconds to sleep.
Referenced by delay().
start()
Handle RTOS::Task::start (std::function< void()> func) inline
Starts the task with the given function.
Parameters
func Function to execute in the task.
Returns
Task handle.
stop()
void RTOS::Task::stop () inline
Stops the task.
suspend()
void RTOS::Task::suspend () inline
Suspends the task.
yield()
void RTOS::Task::yield () inline static
Yields the current task.
Referenced by Lib::BSP::DigitalPeripheralBase::Inputs::update().
Member Data Documentation
DEFAULT_STACK_SIZE
size_t RTOS::Task::DEFAULT_STACK_SIZE = configMINIMAL_STACK_SIZE * 4 static constexpr
Default stack size for a task.
Referenced by Task(), and Task().
DEFAULT_TASK_PRIORITY
UBaseType_t RTOS::Task::DEFAULT_TASK_PRIORITY = tskIDLE_PRIORITY static constexpr
Default task priority.
Examples
RTOS::Task.
Referenced by RTOS::Task::Data::Data(), Task(), Task(), and Task().
MIN_STACK_SIZE
size_t RTOS::Task::MIN_STACK_SIZE = configMINIMAL_STACK_SIZE static constexpr
Minimum stack size for a task.
Referenced by RTOS::Task::Data::Data(), RTOS::Task::Data::Data(), Task(), Task(), and Task().