IAR Library: Lib::Helper::RingBuffer< T, T_SIZE > Class Template Reference
Lib::Helper::RingBuffer< T, T_SIZE > Class Template Reference
Fixed-size ring buffer for FIFO storage.
Public Member Functions
constexpr RingBuffer ()=default
Constructor of RingBuffer class.
~RingBuffer ()=default
Destructor of RingBuffer class.
bool push (const T &value)
Pushes an element into the buffer.
bool push (T &&value)
Pushes an element into the buffer using move semantics.
bool pop (T &value)
Pops an element from the buffer.
void clear ()
Clears the buffer and resets its state.
size_t available () const
Returns the number of elements currently stored in the buffer.
bool isEmpty () const
Checks if the buffer is empty.
bool isFull () const
Checks if the buffer is full.
Static Public Attributes
static constexpr size_t CAPACITY = T_SIZE
Detailed Description
template<typename T, size_t T_SIZE>
class Lib::Helper::RingBuffer< T, T_SIZE >
Fixed-size ring buffer for FIFO storage.
The RingBuffer class implements a circular buffer of fixed capacity for storing elements of type T. It provides efficient push and pop operations, as well as methods to check if the buffer is full or empty, retrieve the number of stored elements, and clear the buffer. This class is suitable for embedded and real-time systems where bounded, non-blocking data queues are required.
Template Parameters
T Type of elements stored in the buffer.
T_SIZE Capacity of the buffer.
Examples
Lib::Helper::RingBuffer.
Constructor & Destructor Documentation
RingBuffer()
template<typename T, size_t T_SIZE> Lib::Helper::RingBuffer< T, T_SIZE >::RingBuffer () constexpr default
Constructor of RingBuffer class.
~RingBuffer()
template<typename T, size_t T_SIZE> Lib::Helper::RingBuffer< T, T_SIZE >::~RingBuffer () default
Destructor of RingBuffer class.
Member Function Documentation
available()
template<typename T, size_t T_SIZE> size_t Lib::Helper::RingBuffer< T, T_SIZE >::available () const inline
Returns the number of elements currently stored in the buffer.
Returns
Number of elements in the buffer.
clear()
template<typename T, size_t T_SIZE> void Lib::Helper::RingBuffer< T, T_SIZE >::clear () inline
Clears the buffer and resets its state.
isEmpty()
template<typename T, size_t T_SIZE> bool Lib::Helper::RingBuffer< T, T_SIZE >::isEmpty () const inline
Checks if the buffer is empty.
Returns
true if the buffer is empty, false otherwise.
Referenced by pop().
isFull()
template<typename T, size_t T_SIZE> bool Lib::Helper::RingBuffer< T, T_SIZE >::isFull () const inline
Checks if the buffer is full.
Returns
true if the buffer is full, false otherwise.
Referenced by push(), and push().
pop()
template<typename T, size_t T_SIZE> bool Lib::Helper::RingBuffer< T, T_SIZE >::pop (T & value) inline
Pops an element from the buffer.
Parameters
[out] value Element removed from the buffer.
Returns
true if an element was removed, false if the buffer is empty.
Examples
Lib::Helper::RingBuffer.
push() [1/2]
template<typename T, size_t T_SIZE> bool Lib::Helper::RingBuffer< T, T_SIZE >::push (const T & value) inline
Pushes an element into the buffer.
Parameters
value Element to be added to the buffer.
Returns
true if the element was added, false if the buffer is full.
Examples
Lib::Helper::RingBuffer.
push() [2/2]
template<typename T, size_t T_SIZE> bool Lib::Helper::RingBuffer< T, T_SIZE >::push (T && value) inline
Pushes an element into the buffer using move semantics.
Parameters
value Element to be added to the buffer.
Returns
true if the element was added, false if the buffer is full.
Member Data Documentation
CAPACITY
template<typename T, size_t T_SIZE> size_t Lib::Helper::RingBuffer< T, T_SIZE >::CAPACITY = T_SIZE static constexpr
Maximum number of elements in the buffer.
Referenced by isFull(), pop(), push(), and push().