IAR Library: Lib::BSP::EEPROM::I2C::M24C64W Class Reference
Lib::BSP::EEPROM::I2C::M24C64W Class Reference
Public Types
using Config = DriverBase::Config
Public Member Functions
M24C64W (const Config &config)
Constructor of the M24C64W class.
~M24C64W () override=default
Destructor of the M24C64W class.
bool open () override
Opens the EEPROM device.
bool close () override
Closes the EEPROM device.
bool read (uint32_t addr, void *buffer, size_t size) override
Reads data from EEPROM at specified address.
bool write (uint32_t addr, const void *buffer, size_t size) override
Writes data to EEPROM at specified address.
size_t getChipSize () const override
Returns the total chip size in bytes.
Static Public Attributes
static constexpr uint32_t I2C_TIMEOUT = 100
Protected Member Functions
virtual bool read8 (uint32_t addr, void *buffer, size_t size)
Reads data from the EEPROM using 8-bit memory addressing.
virtual bool read16 (uint32_t addr, void *buffer, size_t size)
Reads data from the EEPROM using 16-bit memory addressing.
bool write8 (uint32_t addr, const void *buffer, size_t size)
Writes data to the EEPROM using 8-bit memory addressing.
bool write16 (uint32_t addr, const void *buffer, size_t size)
Writes data to the EEPROM using 16-bit memory addressing.
Detailed Description
Examples
Lib::BSP::EEPROM::I2C::M24C64W.
Constructor & Destructor Documentation
M24C64W()
Lib::BSP::EEPROM::I2C::M24C64W::M24C64W (const Config & config) inline explicit
Constructor of the M24C64W class.
Parameters
config EEPROM driver configuration.
~M24C64W()
Lib::BSP::EEPROM::I2C::M24C64W::~M24C64W () override default
Destructor of the M24C64W class.
Member Function Documentation
close()
bool Lib::BSP::EEPROM::I2C::M24C64W::close () inline override virtual
Closes the EEPROM device.
Returns
true if successful, false otherwise.
Reimplemented from Lib::BSP::EEPROM::I2C::DriverBase.
Examples
Lib::BSP::EEPROM::I2C::M24C64W.
getChipSize()
size_t Lib::BSP::EEPROM::I2C::M24C64W::getChipSize () const inline override virtual
Returns the total chip size in bytes.
Returns
Chip size in bytes.
Reimplemented from Lib::BSP::EEPROM::I2C::DriverBase.
open()
bool Lib::BSP::EEPROM::I2C::M24C64W::open () inline override virtual
Opens the EEPROM device.
Returns
true if successful, false otherwise.
Reimplemented from Lib::BSP::EEPROM::I2C::DriverBase.
Examples
Lib::BSP::EEPROM::I2C::M24C64W.
read()
bool Lib::BSP::EEPROM::I2C::M24C64W::read (uint32_t addr, void * buffer, size_t size) inline override virtual
Reads data from EEPROM at specified address.
Parameters
addr EEPROM address to read from.
[out] buffer Destination buffer for read data.
size Number of bytes to read.
Returns
true if read was successful, false otherwise.
Precondition
buffer must be valid and size > 0.
Implements Lib::BSP::EEPROM::I2C::DriverBase.
Examples
Lib::BSP::EEPROM::I2C::M24C64W.
read16()
virtual bool Lib::BSP::EEPROM::I2C::DriverBase::read16 (uint32_t addr, void * buffer, size_t size) inline protected virtual inherited
Reads data from the EEPROM using 16-bit memory addressing.
Parameters
addr Memory address to read from.
buffer Pointer to the buffer to store read data.
size Size of the buffer.
Returns
true if successful, false otherwise.
Referenced by Lib::BSP::EEPROM::I2C::M24C64W::read().
read8()
virtual bool Lib::BSP::EEPROM::I2C::DriverBase::read8 (uint32_t addr, void * buffer, size_t size) inline protected virtual inherited
Reads data from the EEPROM using 8-bit memory addressing.
Parameters
addr Memory address to read from.
buffer Pointer to the buffer to store read data.
size Size of the buffer.
Returns
true if successful, false otherwise.
Referenced by Lib::BSP::EEPROM::I2C::M24C16::read().
write()
bool Lib::BSP::EEPROM::I2C::M24C64W::write (uint32_t addr, const void * buffer, size_t size) inline override virtual
Writes data to EEPROM at specified address.
Parameters
addr EEPROM address to write to.
buffer Source buffer containing data to write.
size Number of bytes to write.
Returns
true if write was successful, false otherwise.
Precondition
buffer must be valid and size > 0.
Implements Lib::BSP::EEPROM::I2C::DriverBase.
Examples
Lib::BSP::EEPROM::I2C::M24C64W.
write16()
bool Lib::BSP::EEPROM::I2C::DriverBase::write16 (uint32_t addr, const void * buffer, size_t size) inline protected inherited
Writes data to the EEPROM using 16-bit memory addressing.
Parameters
addr Memory address to write to.
buffer Pointer to the buffer containing data to write.
size Size of the buffer.
Returns
true if successful, false otherwise.
Referenced by Lib::BSP::EEPROM::I2C::M24C64W::write().
write8()
bool Lib::BSP::EEPROM::I2C::DriverBase::write8 (uint32_t addr, const void * buffer, size_t size) inline protected inherited
Writes data to the EEPROM using 8-bit memory addressing.
Parameters
addr Memory address to write to.
buffer Pointer to the buffer containing data to write.
size Size of the buffer.
Returns
true if successful, false otherwise.
Referenced by Lib::BSP::EEPROM::I2C::M24C16::write().
Member Data Documentation
I2C_TIMEOUT
uint32_t Lib::BSP::EEPROM::I2C::DriverBase::I2C_TIMEOUT = 100 static constexpr inherited
Timeout for I2C operations (ms).
Referenced by read16(), and read8().