IAR Library: Lib::Digi::API::UserProtocol Class Reference
Lib::Digi::API::UserProtocol Class Reference
Base class for user-defined protocol parsing and message building.
Public Types
enum Command : uint8_t {
INPUTS = 0 ,
GET_PARAMETERS = 1 ,
OUTPUTS = 10 ,
SET_PARAMETERS = 11
}
User-defined protocol commands.
Protected Member Functions
UserProtocol ()=default
Constructor of UserProtocol class.
virtual ~UserProtocol ()=default
Destructor of UserProtocol class.
virtual bool parse (const std::vector< uint8_t > &buffer)
Parses the incoming message.
virtual void build (std::vector< uint8_t > &buffer, Command cmd, const void *data, size_t len)
Builds the outgoing message.
virtual void handleInputsUpdate (const uint8_t *data, size_t len)
Handles inputs update.
virtual void handleGetParameters (const uint8_t *data, size_t len)
Handles get parameters.
virtual void handleSetParameters (const uint8_t *data, size_t len)
Handles set parameters.
virtual void handleOutputsUpdate (const uint8_t *data, size_t len)
Handles outputs update.
Detailed Description
Base class for user-defined protocol parsing and message building.
The UserProtocol class provides an abstract interface for parsing incoming messages and building outgoing messages according to user-defined protocol commands. It defines a set of protocol commands and callback methods for handling specific protocol actions. Derived classes can override these callbacks to implement custom protocol logic. The class ensures efficient message handling and type safety for Digi XBee API communication.
Member Enumeration Documentation
Command
enum Lib::Digi::API::UserProtocol::Command : uint8_t
User-defined protocol commands.
Enumerator
INPUTS
Command for inputs update.
GET_PARAMETERS
Command for getting parameters.
OUTPUTS
Command for outputs update.
SET_PARAMETERS
Command for setting parameters.
Constructor & Destructor Documentation
UserProtocol()
Lib::Digi::API::UserProtocol::UserProtocol () protected default
Constructor of UserProtocol class.
~UserProtocol()
virtual Lib::Digi::API::UserProtocol::~UserProtocol () protected virtual default
Destructor of UserProtocol class.
Member Function Documentation
build()
virtual void Lib::Digi::API::UserProtocol::build (std::vector< uint8_t > & buffer, Command cmd, const void * data, size_t len) inline protected virtual
Builds the outgoing message.
Parameters
[out] buffer Result buffer.
cmd User command.
data Pointer to data (payload).
len Data length.
Warning
Asserts if data is nullptr when len > 0.
handleGetParameters()
virtual void Lib::Digi::API::UserProtocol::handleGetParameters (const uint8_t * data, size_t len) inline protected virtual
Handles get parameters.
Parameters
data Pointer to parameter data.
len Data length.
Referenced by parse().
handleInputsUpdate()
virtual void Lib::Digi::API::UserProtocol::handleInputsUpdate (const uint8_t * data, size_t len) inline protected virtual
Handles inputs update.
Parameters
data Pointer to input data.
len Data length.
Referenced by parse().
handleOutputsUpdate()
virtual void Lib::Digi::API::UserProtocol::handleOutputsUpdate (const uint8_t * data, size_t len) inline protected virtual
Handles outputs update.
Parameters
data Pointer to output data.
len Data length.
Referenced by parse().
handleSetParameters()
virtual void Lib::Digi::API::UserProtocol::handleSetParameters (const uint8_t * data, size_t len) inline protected virtual
Handles set parameters.
Parameters
data Pointer to parameter data.
len Data length.
Referenced by parse().
parse()
virtual bool Lib::Digi::API::UserProtocol::parse (const std::vector< uint8_t > & buffer) inline protected virtual
Parses the incoming message.
Parameters
buffer Reference to vector containing the received data.
Returns
true if handled, false otherwise.
Warning
Asserts if buffer is empty or command is invalid.