IAR Library: RTOS::EventGroup Class Reference
RTOS::EventGroup Class Reference
EventGroup class for FreeRTOS event group management.
Public Types
enum class WaitMode : uint8_t {
WAIT_ANY = 0 ,
WAIT_ALL = 1
}
Wait mode for event group waiting.
enum class ClearMode : uint8_t {
CLEAR_NO_CLEAR = 0 ,
CLEAR_CLEAR = 1
}
Clear mode for event group waiting.
enum class State : uint8_t {
STATE_INVALID = 0 ,
STATE_ACTIVE = 1
}
State of the event group.
using TickType = TickCounter::TickType
using Handle = EventGroupHandle_t
using BitIndex = uint8_t
using BitMask = EventBits_t
Public Member Functions
EventGroup ()
Constructor of the EventGroup class.
EventGroup (bool isAutoCreate)
Constructor of the EventGroup class.
EventGroup (EventGroup &&other) noexcept
Move constructor of the EventGroup class.
EventGroup & operator= (EventGroup &&other) noexcept
Move assignment operator of the EventGroup class.
~EventGroup ()
Destructor of the EventGroup class.
bool create ()
Creates the event group.
void destroy ()
Destroys the event group and releases resources.
EventBits setBits (const EventBits &bits)
Sets the specified event bits.
EventBits setBit (BitIndex bitIndex)
Sets a single event bit.
template<size_t N>
EventBits setBits (const std::array< BitIndex, N > &bitIndices)
Sets multiple event bits by indices.
bool setBitsFromISR (const EventBits &bits)
Sets event bits from ISR context.
bool setBitFromISR (BitIndex bitIndex)
Sets a single event bit from ISR context.
EventBits getBits () const
Gets the current event bits.
EventBits getBitsFromISR () const
Gets the current event bits from ISR context.
bool isBitSet (BitIndex bitIndex) const
Checks if a specific bit is set.
bool anyBitsSet (const EventBits &bits) const
Checks if any of the specified bits are set.
bool allBitsSet (const EventBits &bits) const
Checks if all of the specified bits are set.
EventBits clearBits (const EventBits &bits)
Clears the specified event bits.
EventBits clearBit (BitIndex bitIndex)
Clears a single event bit.
EventBits clearAllBits ()
Clears all event bits.
bool clearBitsFromISR (const EventBits &bits)
Clears event bits from ISR context.
bool clearBitFromISR (BitIndex bitIndex)
Clears a single event bit from ISR context.
EventBits waitForBits (const EventBits &bits, ClearMode clearMode=ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode=WaitMode::WAIT_ANY, TickType waitTime=DEFAULT_WAIT) const
Waits for specified event bits.
EventBits waitForBitsMs (const EventBits &bits, uint32_t timeoutMs, ClearMode clearMode=ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode=WaitMode::WAIT_ANY) const
Waits for specified event bits with timeout in milliseconds.
EventBits waitForBitsSeconds (const EventBits &bits, uint32_t timeoutSec, ClearMode clearMode=ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode=WaitMode::WAIT_ANY) const
Waits for specified event bits with timeout in seconds.
bool waitForBit (BitIndex bitIndex, TickType waitTime=DEFAULT_WAIT, ClearMode clearMode=ClearMode::CLEAR_NO_CLEAR) const
Waits for a single event bit.
bool tryWaitForBits (const EventBits &bits) const
Tries to wait for specified event bits without blocking.
EventBits waitForBits (const EventBits &bits, const Timeout &timeout, ClearMode clearMode=ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode=WaitMode::WAIT_ANY) const
Waits for specified event bits with Timeout object.
EventBits syncBits (const EventBits &bitsToSet, const EventBits &bitsToWait, TickType waitTime=DEFAULT_WAIT) const
Synchronizes event bits with other tasks.
EventBits syncBits (const EventBits &bitsToSet, const EventBits &bitsToWait, uint32_t timeoutMs) const
Synchronizes event bits with other tasks (timeout in milliseconds).
bool syncBit (BitIndex bitToSet, BitIndex bitToWait, TickType waitTime=DEFAULT_WAIT) const
Synchronizes a single event bit with another task.
bool isCreated () const
Checks if the event group is created.
State getState () const
Gets the current state of the event group.
bool isValid () const
Checks if the event group is valid.
Handle getHandle () const
Gets the underlying FreeRTOS event group handle.
operator bool () const
Conversion operator to bool.
Static Public Member Functions
static constexpr uint8_t getBitCount ()
Gets the number of event bits.
static constexpr BitIndex getMaxBitIndex ()
Gets the maximum bit index.
static std::unique_ptr< EventGroup > create (bool isAutoCreate=true)
Creates a unique_ptr to an EventGroup instance.
static std::unique_ptr< EventGroup > createWithBits (const EventBits &initialBits)
Creates a unique_ptr to an EventGroup with initial bits set.
template<size_t N>
static std::unique_ptr< EventGroup > createWithIndices (const std::array< BitIndex, N > &bitIndices)
Creates a unique_ptr to an EventGroup with bits set by indices.
Static Public Attributes
static constexpr TickType DEFAULT_WAIT = portMAX_DELAY
static constexpr TickType NO_WAIT = 0
Detailed Description
EventGroup class for FreeRTOS event group management.
Provides a modern, type-safe C++17 wrapper for FreeRTOS event groups, supporting bitwise signaling, waiting, and synchronization with compile-time validation and utility methods.
Member Typedef Documentation
BitIndex
using RTOS::EventGroup::BitIndex = uint8_t
Bit index type.
BitMask
using RTOS::EventGroup::BitMask = EventBits_t
Bit mask type.
Handle
using RTOS::EventGroup::Handle = EventGroupHandle_t
FreeRTOS event group handle type.
TickType
using RTOS::EventGroup::TickType = TickCounter::TickType
Tick type alias.
Member Enumeration Documentation
ClearMode
enum class RTOS::EventGroup::ClearMode : uint8_t strong
Clear mode for event group waiting.
Enumerator
CLEAR_NO_CLEAR
Do not clear bits after waiting.
CLEAR_CLEAR
Clear bits after waiting.
State
enum class RTOS::EventGroup::State : uint8_t strong
State of the event group.
Enumerator
STATE_INVALID
Event group is invalid or not created.
STATE_ACTIVE
Event group is active and created.
WaitMode
enum class RTOS::EventGroup::WaitMode : uint8_t strong
Wait mode for event group waiting.
Enumerator
WAIT_ANY
Wait for any bit to be set.
WAIT_ALL
Wait for all bits to be set.
Constructor & Destructor Documentation
EventGroup() [1/3]
RTOS::EventGroup::EventGroup () inline
Constructor of the EventGroup class.
Referenced by EventGroup(), and operator=().
EventGroup() [2/3]
RTOS::EventGroup::EventGroup (bool isAutoCreate) inline explicit
Constructor of the EventGroup class.
Parameters
isAutoCreate If true, automatically creates the event group.
EventGroup() [3/3]
RTOS::EventGroup::EventGroup (EventGroup && other) inline noexcept
Move constructor of the EventGroup class.
Parameters
other EventGroup to move from.
~EventGroup()
RTOS::EventGroup::~EventGroup () inline
Destructor of the EventGroup class.
Member Function Documentation
allBitsSet()
bool RTOS::EventGroup::allBitsSet (const EventBits & bits) const inline
Checks if all of the specified bits are set.
Parameters
bits Bits to check.
Returns
true if all bits are set, false otherwise.
anyBitsSet()
bool RTOS::EventGroup::anyBitsSet (const EventBits & bits) const inline
Checks if any of the specified bits are set.
Parameters
bits Bits to check.
Returns
true if any bit is set, false otherwise.
clearAllBits()
EventBits RTOS::EventGroup::clearAllBits () inline
Clears all event bits.
Returns
Event bits after clearing all bits.
clearBit()
EventBits RTOS::EventGroup::clearBit (BitIndex bitIndex) inline
Clears a single event bit.
Parameters
bitIndex Index of the bit to clear.
Returns
Event bits after clearing.
clearBitFromISR()
bool RTOS::EventGroup::clearBitFromISR (BitIndex bitIndex) inline
Clears a single event bit from ISR context.
Parameters
bitIndex Index of the bit to clear.
Returns
true if operation was successful, false otherwise.
clearBits()
EventBits RTOS::EventGroup::clearBits (const EventBits & bits) inline
Clears the specified event bits.
Parameters
bits Event bits to clear.
Returns
Event bits after clearing.
Referenced by clearAllBits(), and clearBit().
clearBitsFromISR()
bool RTOS::EventGroup::clearBitsFromISR (const EventBits & bits) inline
Clears event bits from ISR context.
Parameters
bits Event bits to clear.
Returns
true if operation was successful, false otherwise.
Referenced by clearBitFromISR().
create() [1/2]
bool RTOS::EventGroup::create () inline
Creates the event group.
Returns
true if creation was successful, false otherwise.
Referenced by createWithBits(), and createWithIndices().
create() [2/2]
std::unique_ptr< EventGroup > RTOS::EventGroup::create (bool isAutoCreate = true) inline static
Creates a unique_ptr to an EventGroup instance.
Parameters
isAutoCreate If true, automatically creates the event group.
Returns
Unique pointer to EventGroup, or nullptr if creation failed.
createWithBits()
std::unique_ptr< EventGroup > RTOS::EventGroup::createWithBits (const EventBits & initialBits) inline static
Creates a unique_ptr to an EventGroup with initial bits set.
Parameters
initialBits Bits to set initially.
Returns
Unique pointer to EventGroup, or nullptr if creation failed.
createWithIndices()
template<size_t N> std::unique_ptr< EventGroup > RTOS::EventGroup::createWithIndices (const std::array< BitIndex, N > & bitIndices) inline static
Creates a unique_ptr to an EventGroup with bits set by indices.
Template Parameters
N Number of bit indices.
Parameters
bitIndices Array of bit indices to set.
Returns
Unique pointer to EventGroup, or nullptr if creation failed.
destroy()
void RTOS::EventGroup::destroy () inline
Destroys the event group and releases resources.
Referenced by ~EventGroup(), and operator=().
getBitCount()
constexpr uint8_t RTOS::EventGroup::getBitCount () inline static constexpr
Gets the number of event bits.
Returns
Number of event bits.
getBits()
EventBits RTOS::EventGroup::getBits () const inline
Gets the current event bits.
Returns
Current event bits.
Referenced by allBitsSet(), anyBitsSet(), clearBit(), clearBits(), isBitSet(), setBit(), syncBits(), waitForBits(), and waitForBitsMs().
getBitsFromISR()
EventBits RTOS::EventGroup::getBitsFromISR () const inline
Gets the current event bits from ISR context.
Returns
Current event bits.
getHandle()
Handle RTOS::EventGroup::getHandle () const inline
Gets the underlying FreeRTOS event group handle.
Returns
Event group handle.
getMaxBitIndex()
constexpr BitIndex RTOS::EventGroup::getMaxBitIndex () inline static constexpr
Gets the maximum bit index.
Returns
Maximum bit index.
getState()
State RTOS::EventGroup::getState () const inline
Gets the current state of the event group.
Returns
State of the event group.
isBitSet()
bool RTOS::EventGroup::isBitSet (BitIndex bitIndex) const inline
Checks if a specific bit is set.
Parameters
bitIndex Index of the bit to check.
Returns
true if the bit is set, false otherwise.
isCreated()
bool RTOS::EventGroup::isCreated () const inline
Checks if the event group is created.
Returns
true if created, false otherwise.
Referenced by clearBits(), clearBitsFromISR(), destroy(), getBits(), getBitsFromISR(), getState(), isValid(), operator bool(), setBits(), setBitsFromISR(), syncBits(), and waitForBits().
isValid()
bool RTOS::EventGroup::isValid () const inline
Checks if the event group is valid.
Returns
true if valid, false otherwise.
operator bool()
RTOS::EventGroup::operator bool () const inline explicit
Conversion operator to bool.
Returns
true if created, false otherwise.
operator=()
EventGroup & RTOS::EventGroup::operator= (EventGroup && other) inline noexcept
Move assignment operator of the EventGroup class.
Parameters
other EventGroup to move from.
Returns
Reference to this EventGroup.
setBit()
EventBits RTOS::EventGroup::setBit (BitIndex bitIndex) inline
Sets a single event bit.
Parameters
bitIndex Index of the bit to set.
Returns
Event bits after setting.
setBitFromISR()
bool RTOS::EventGroup::setBitFromISR (BitIndex bitIndex) inline
Sets a single event bit from ISR context.
Parameters
bitIndex Index of the bit to set.
Returns
true if operation was successful, false otherwise.
setBits() [1/2]
EventBits RTOS::EventGroup::setBits (const EventBits & bits) inline
Sets the specified event bits.
Parameters
bits Event bits to set.
Returns
Event bits after setting.
Referenced by setBit().
setBits() [2/2]
template<size_t N> EventBits RTOS::EventGroup::setBits (const std::array< BitIndex, N > & bitIndices) inline
Sets multiple event bits by indices.
Template Parameters
N Number of bit indices.
Parameters
bitIndices Array of bit indices to set.
Returns
Event bits after setting.
Referenced by setBits().
setBitsFromISR()
bool RTOS::EventGroup::setBitsFromISR (const EventBits & bits) inline
Sets event bits from ISR context.
Parameters
bits Event bits to set.
Returns
true if operation was successful, false otherwise.
Referenced by setBitFromISR().
syncBit()
bool RTOS::EventGroup::syncBit (BitIndex bitToSet, BitIndex bitToWait, TickType waitTime = DEFAULT_WAIT) const inline
Synchronizes a single event bit with another task.
Parameters
bitToSet Bit to set.
bitToWait Bit to wait for.
waitTime Timeout in ticks.
Returns
true if the bit was synchronized, false otherwise.
syncBits() [1/2]
EventBits RTOS::EventGroup::syncBits (const EventBits & bitsToSet, const EventBits & bitsToWait, TickType waitTime = DEFAULT_WAIT) const inline
Synchronizes event bits with other tasks.
Parameters
bitsToSet Bits to set.
bitsToWait Bits to wait for.
waitTime Timeout in ticks.
Returns
Event bits after synchronization.
Referenced by syncBit(), and syncBits().
syncBits() [2/2]
EventBits RTOS::EventGroup::syncBits (const EventBits & bitsToSet, const EventBits & bitsToWait, uint32_t timeoutMs) const inline
Synchronizes event bits with other tasks (timeout in milliseconds).
Parameters
bitsToSet Bits to set.
bitsToWait Bits to wait for.
timeoutMs Timeout in milliseconds.
Returns
Event bits after synchronization.
tryWaitForBits()
bool RTOS::EventGroup::tryWaitForBits (const EventBits & bits) const inline
Tries to wait for specified event bits without blocking.
Parameters
bits Bits to wait for.
Returns
true if any bit was set, false otherwise.
waitForBit()
bool RTOS::EventGroup::waitForBit (BitIndex bitIndex, TickType waitTime = DEFAULT_WAIT, ClearMode clearMode = ClearMode::CLEAR_NO_CLEAR) const inline
Waits for a single event bit.
Parameters
bitIndex Index of the bit to wait for.
waitTime Timeout in ticks.
clearMode Whether to clear the bit after waiting.
Returns
true if the bit was set, false otherwise.
waitForBits() [1/2]
EventBits RTOS::EventGroup::waitForBits (const EventBits & bits, ClearMode clearMode = ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode = WaitMode::WAIT_ANY, TickType waitTime = DEFAULT_WAIT) const inline
Waits for specified event bits.
Parameters
bits Bits to wait for.
clearMode Whether to clear bits after waiting.
waitMode Wait for any or all bits.
waitTime Timeout in ticks.
Returns
Event bits after waiting.
Referenced by tryWaitForBits(), waitForBit(), waitForBits(), and waitForBitsMs().
waitForBits() [2/2]
EventBits RTOS::EventGroup::waitForBits (const EventBits & bits, const Timeout & timeout, ClearMode clearMode = ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode = WaitMode::WAIT_ANY) const inline
Waits for specified event bits with Timeout object.
Parameters
bits Bits to wait for.
timeout Timeout object.
clearMode Whether to clear bits after waiting.
waitMode Wait for any or all bits.
Returns
Event bits after waiting.
waitForBitsMs()
EventBits RTOS::EventGroup::waitForBitsMs (const EventBits & bits, uint32_t timeoutMs, ClearMode clearMode = ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode = WaitMode::WAIT_ANY) const inline
Waits for specified event bits with timeout in milliseconds.
Parameters
bits Bits to wait for.
timeoutMs Timeout in milliseconds.
clearMode Whether to clear bits after waiting.
waitMode Wait for any or all bits.
Returns
Event bits after waiting.
Referenced by waitForBitsSeconds().
waitForBitsSeconds()
EventBits RTOS::EventGroup::waitForBitsSeconds (const EventBits & bits, uint32_t timeoutSec, ClearMode clearMode = ClearMode::CLEAR_NO_CLEAR, WaitMode waitMode = WaitMode::WAIT_ANY) const inline
Waits for specified event bits with timeout in seconds.
Parameters
bits Bits to wait for.
timeoutSec Timeout in seconds.
clearMode Whether to clear bits after waiting.
waitMode Wait for any or all bits.
Returns
Event bits after waiting.
Member Data Documentation
DEFAULT_WAIT
TickType RTOS::EventGroup::DEFAULT_WAIT = portMAX_DELAY static constexpr
Default wait time (infinite).
Referenced by syncBit(), syncBits(), waitForBit(), waitForBits(), and waitForBits().
NO_WAIT
TickType RTOS::EventGroup::NO_WAIT = 0 static constexpr
No wait time (immediate return).
Referenced by tryWaitForBits().