IAR Library: Lib::Digi::Core::Protocol Class Reference
Lib::Digi::Core::Protocol Class Reference
Protocol class for Digi XBee API frames.
Static Public Member Functions
static bool parse (const ApiFrameBuffer &apiFrame, Frame::Data &frameData)
Parses the incoming Digi API frame.
static bool processMessage (const ApiFrameBuffer &apiFrame)
Processes a received Digi API frame and dispatches events.
static bool isValid (const ApiFrameBuffer &apiFrame)
Checks whether the Digi API frame is valid (non-escaped message).
static bool isValid (const uint8_t *dst)
Checks whether the message is valid (non-escaped message).
static const ApiFrameBuffer & build (const Frame::Data &frameData)
Builds a Digi API frame from frame data.
Static Public Attributes
static constexpr uint8_t START_DELIMITER = 0x7E
static constexpr ApiMode API_MODE = ApiMode::API1
Detailed Description
Protocol class for Digi XBee API frames.
Handles parsing, validation, and processing of Digi XBee API frames, including frame construction, checksum verification, and event dispatching for Digi XBee modules.
Member Function Documentation
build()
const ApiFrameBuffer & Lib::Digi::Core::Protocol::build (const Frame::Data & frameData) inline static
Builds a Digi API frame from frame data.
Parameters
frameData Reference to the frame data.
Returns
Reference to the built ApiFrameBuffer object.
Referenced by Lib::Digi::Core::Module::send().
isValid() [1/2]
bool Lib::Digi::Core::Protocol::isValid (const ApiFrameBuffer & apiFrame) inline static
Checks whether the Digi API frame is valid (non-escaped message).
Parameters
apiFrame Reference to Digi API frame.
Returns
true if the message is valid, false otherwise.
Referenced by parse().
isValid() [2/2]
bool Lib::Digi::Core::Protocol::isValid (const uint8_t * dst) inline static
Checks whether the message is valid (non-escaped message).
Parameters
dst Pointer to the raw message buffer.
Returns
true if the message is valid, false otherwise.
parse()
bool Lib::Digi::Core::Protocol::parse (const ApiFrameBuffer & apiFrame, Frame::Data & frameData) inline static
Parses the incoming Digi API frame.
Parameters
apiFrame Incoming Digi API frame.
[out] frameData Output frame data.
Returns
true if parsing is successful, false otherwise.
Referenced by processMessage().
processMessage()
bool Lib::Digi::Core::Protocol::processMessage (const ApiFrameBuffer & apiFrame) inline static
Processes a received Digi API frame and dispatches events.
Parameters
apiFrame Reference to Digi API frame (incoming message).
Returns
true if the message was processed successfully, false otherwise.
Member Data Documentation
API_MODE
ApiMode Lib::Digi::Core::Protocol::API_MODE = ApiMode::API1 static constexpr
API mode used.
Referenced by build().
START_DELIMITER
uint8_t Lib::Digi::Core::Protocol::START_DELIMITER = 0x7E static constexpr
Start delimiter for Digi API frames.
Referenced by build(), isValid(), and isValid().