IAR Library: Lib::Helper Namespace Reference
Lib::Helper Namespace Reference
Helper utilities and functions for the Lib module.
Classes
class Buffer
Manages a dynamic memory buffer.
class BufferHandle
Provides a handle to a buffer of bytes.
class BufferStatic
Manages a static memory buffer.
class CityHash
CityHash utility for 32-bit hash calculation.
class Container
Generic pointer container for object management.
class ContainerBase
Generic value container base for object management.
class Crc16
CRC-16 calculation utility.
class DataHandle
DataHandle class template for managing raw data buffers.
class DateTime
Combined date and time representation.
class Delay
Utility class for microsecond delays using DWT cycle counter.
class Exception
Custom exception class for the library.
class FindPeaks
FindPeaks class.
class Instance
Singleton instance holder.
class InstanceWithArg
Singleton instance holder with configuration.
class Integrator
Template class for computing moving average.
class JaggedArrayBase
JaggedArrayBase class.
class MoonPhase
Moon phase calculator.
class RingBuffer
Fixed-size ring buffer for FIFO storage.
class Singleton
Template for creating singleton classes.
class StringHelper
Utility functions for string operations.
class Sunset
Sunset and moon phase calculation utility.
class TimePeriod
Measures time periods using FreeRTOS TickCounter.
class TimeZone
TimeZone class.
Typedefs
template<class T>
using JaggedArrayRow = JaggedArrayBase<T>
Type alias for JaggedArrayRow.
template<class T>
using JaggedArray = JaggedArrayBase<JaggedArrayRow<T>>
Type alias for JaggedArray.
Functions
template<typename T>
T & getInstance ()
Retrieves a singleton instance.
template<typename T, typename TConfig>
T & getInstance (const TConfig &config)
Retrieves a singleton instance with configuration.
template<typename T>
constexpr T swapBytes (T value)
Swaps the byte order of a value.
template<typename T>
T swapBytes (const void *src)
Swaps the byte order of a value pointed to by a pointer.
void swapBytes (const void *src, void *dst, size_t size)
Swaps the byte order of a memory buffer.
template<>
constexpr uint16_t swapBytes< uint16_t > (uint16_t value)
Swaps the byte order of a 16-bit unsigned integer.
template<>
uint16_t swapBytes< uint16_t > (const void *src)
Swaps the byte order of a 16-bit unsigned integer from a pointer.
template<>
constexpr int16_t swapBytes< int16_t > (int16_t value)
Swaps the byte order of a 16-bit signed integer.
template<>
int16_t swapBytes< int16_t > (const void *src)
Swaps the byte order of a 16-bit signed integer from a pointer.
template<>
constexpr uint32_t swapBytes< uint32_t > (uint32_t value)
Swaps the byte order of a 32-bit unsigned integer.
template<>
uint32_t swapBytes< uint32_t > (const void *src)
Swaps the byte order of a 32-bit unsigned integer from a pointer.
template<>
constexpr int32_t swapBytes< int32_t > (int32_t value)
Swaps the byte order of a 32-bit signed integer.
template<>
int32_t swapBytes< int32_t > (const void *src)
Swaps the byte order of a 32-bit signed integer from a pointer.
template<>
constexpr uint64_t swapBytes< uint64_t > (uint64_t value)
Swaps the byte order of a 64-bit unsigned integer.
template<>
uint64_t swapBytes< uint64_t > (const void *src)
Swaps the byte order of a 64-bit unsigned integer from a pointer.
template<>
constexpr int64_t swapBytes< int64_t > (int64_t value)
Swaps the byte order of a 64-bit signed integer.
template<>
int64_t swapBytes< int64_t > (const void *src)
Swaps the byte order of a 64-bit signed integer from a pointer.
Variables
template<typename T, typename TConfig>
char InstanceWithArg< T, TConfig >::storage [sizeof(T)]
template<typename T, typename TConfig>
bool InstanceWithArg< T, TConfig >::initialized {false}
Detailed Description
Helper utilities and functions for the Lib module.
This namespace contains reusable helper functions and classes that provide common functionality across the Lib module. It is designed to promote code reuse and maintainability by encapsulating shared logic and utilities. The namespace may be extended with additional helper classes, functions, or constants as needed to support the evolving requirements of the Lib module.
Typedef Documentation
JaggedArray
template<class T> using Lib::Helper::JaggedArray = JaggedArrayBase<JaggedArrayRow<T>>
Type alias for JaggedArray.
Alias for JaggedArrayBase<JaggedArrayRow<T>> representing a jagged array.
Template Parameters
T The type of elements in the array.
Examples
Lib::Helper::JaggedArray.
JaggedArrayRow
template<class T> using Lib::Helper::JaggedArrayRow = JaggedArrayBase<T>
Type alias for JaggedArrayRow.
Alias for JaggedArrayBase<T> representing a row in a jagged array.
Template Parameters
T The type of elements in the row.
Examples
Lib::Helper::JaggedArray.
Function Documentation
getInstance() [1/2]
template<typename T> T & Lib::Helper::getInstance ()
Retrieves a singleton instance.
This function provides a thread-safe way to access a singleton instance of type T.
Template Parameters
T The type of the singleton instance.
Returns
Reference to the singleton instance of type T.
Examples
Lib::Helper::instance.
getInstance() [2/2]
template<typename T, typename TConfig> T & Lib::Helper::getInstance (const TConfig & config)
Retrieves a singleton instance with configuration.
This function provides a thread-safe way to access a singleton instance of type T, initialized with a configuration argument.
Template Parameters
T The type of the singleton instance.
TConfig The type of the configuration parameter.
Parameters
config The configuration to initialize the instance with.
Returns
Reference to the singleton instance of type T.
swapBytes() [1/3]
template<typename T> T Lib::Helper::swapBytes (const void * src)
Swaps the byte order of a value pointed to by a pointer.
Template Parameters
T Type of the value.
Parameters
src Pointer to the value whose byte order is to be swapped.
Returns
Value with its byte order swapped.
swapBytes() [2/3]
void Lib::Helper::swapBytes (const void * src, void * dst, size_t size) inline
Swaps the byte order of a memory buffer.
Parameters
src Pointer to the source buffer.
dst Pointer to the destination buffer.
size Length of the buffer in bytes.
swapBytes() [3/3]
template<typename T> T Lib::Helper::swapBytes (T value) constexpr
Swaps the byte order of a value.
Template Parameters
T Type of the value.
Parameters
value Value whose byte order is to be swapped.
Returns
Value with its byte order swapped.
Examples
Lib::Helper::swapBytes.
swapBytes< int16_t >() [1/2]
template<> int16_t Lib::Helper::swapBytes< int16_t > (const void * src) inline
Swaps the byte order of a 16-bit signed integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< int16_t >() [2/2]
template<> int16_t Lib::Helper::swapBytes< int16_t > (int16_t value) constexpr
Swaps the byte order of a 16-bit signed integer.
Parameters
value Value to swap.
Returns
Swapped value.
swapBytes< int32_t >() [1/2]
template<> int32_t Lib::Helper::swapBytes< int32_t > (const void * src) inline
Swaps the byte order of a 32-bit signed integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< int32_t >() [2/2]
template<> int32_t Lib::Helper::swapBytes< int32_t > (int32_t value) constexpr
Swaps the byte order of a 32-bit signed integer.
Parameters
value Value to swap.
Returns
Swapped value.
swapBytes< int64_t >() [1/2]
template<> int64_t Lib::Helper::swapBytes< int64_t > (const void * src) inline
Swaps the byte order of a 64-bit signed integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< int64_t >() [2/2]
template<> int64_t Lib::Helper::swapBytes< int64_t > (int64_t value) constexpr
Swaps the byte order of a 64-bit signed integer.
Parameters
value Value to swap.
Returns
Swapped value.
swapBytes< uint16_t >() [1/2]
template<> uint16_t Lib::Helper::swapBytes< uint16_t > (const void * src) inline
Swaps the byte order of a 16-bit unsigned integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< uint16_t >() [2/2]
template<> uint16_t Lib::Helper::swapBytes< uint16_t > (uint16_t value) constexpr
Swaps the byte order of a 16-bit unsigned integer.
Parameters
value Value to swap.
Returns
Swapped value.
Referenced by swapBytes< int16_t >(), swapBytes< int16_t >(), swapBytes< uint16_t >(), Lib::Digi::Core::Frame::Helper::Convert::to(), and Lib::Digi::Core::Frame::Helper::Convert::to().
swapBytes< uint32_t >() [1/2]
template<> uint32_t Lib::Helper::swapBytes< uint32_t > (const void * src) inline
Swaps the byte order of a 32-bit unsigned integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< uint32_t >() [2/2]
template<> uint32_t Lib::Helper::swapBytes< uint32_t > (uint32_t value) constexpr
Swaps the byte order of a 32-bit unsigned integer.
Parameters
value Value to swap.
Returns
Swapped value.
Referenced by swapBytes< int32_t >(), swapBytes< int32_t >(), and swapBytes< uint32_t >().
swapBytes< uint64_t >() [1/2]
template<> uint64_t Lib::Helper::swapBytes< uint64_t > (const void * src) inline
Swaps the byte order of a 64-bit unsigned integer from a pointer.
Parameters
src Pointer to the value.
Returns
Swapped value.
swapBytes< uint64_t >() [2/2]
template<> uint64_t Lib::Helper::swapBytes< uint64_t > (uint64_t value) constexpr
Swaps the byte order of a 64-bit unsigned integer.
Parameters
value Value to swap.
Returns
Swapped value.
Referenced by swapBytes< int64_t >(), swapBytes< int64_t >(), swapBytes< uint64_t >(), Lib::Digi::Core::Frame::Helper::Convert::to(), and Lib::Digi::Core::Frame::Helper::Convert::to().