var searchData=
[
  ['safe_20access_0',['Example usage of RTOS::Mutex and MutexGuard for thread-safe access.',['../X:/Lib/IAR/inc/Lib/RTOS/Mutex.hpp#example-usage-of-rtosmutex-and-mutexguard-for-thread-safe-access',1,'']]],
  ['select_20the_20appropriate_20mode_20based_20on_20performance_20and_20interrupt_20requirements_1',['Select the appropriate mode based on performance and interrupt requirements.',['../d9/d8d/namespace_lib_1_1_h_a_l.html#select-the-appropriate-mode-based-on-performance-and-interrupt-requirements',1,'']]],
  ['sending_20and_20receiving_20messages_2',['Example usage of RTOS::MessageBuffer for sending and receiving messages.',['../X:/Lib/IAR/inc/Lib/RTOS/MessageBuffer.hpp#example-usage-of-rtosmessagebuffer-for-sending-and-receiving-messages',1,'']]],
  ['sensor_20data_3',['Example of Kalman filter usage for smoothing noisy sensor data.',['../X:/Lib/IAR/inc/Lib/Math/Filter/Kalman.hpp#example-of-kalman-filter-usage-for-smoothing-noisy-sensor-data',1,'']]],
  ['serial_20number_20generation_20and_20formatting_20example_4',['Serial Number Generation and Formatting Example',['../X:/Lib/IAR/inc/Lib/System/SerialNumber.hpp#serial-number-generation-and-formatting-example',1,'']]],
  ['serial_20repeater_20functionality_5',['Example usage of SerialPortRepeaterBase for USB serial repeater functionality.',['../X:/Lib/IAR/inc/Lib/USB/SerialPortRepeaterBase.hpp#example-usage-of-serialportrepeaterbase-for-usb-serial-repeater-functionality',1,'']]],
  ['serialportrepeaterbase_20for_20usb_20serial_20repeater_20functionality_6',['Example usage of SerialPortRepeaterBase for USB serial repeater functionality.',['../X:/Lib/IAR/inc/Lib/USB/SerialPortRepeaterBase.hpp#example-usage-of-serialportrepeaterbase-for-usb-serial-repeater-functionality',1,'']]],
  ['sets_7',['Example usage of RTOS::QueueSet with FreeRTOS queue sets.',['../X:/Lib/IAR/inc/Lib/RTOS/QueueSet.hpp#example-usage-of-rtosqueueset-with-freertos-queue-sets',1,'']]],
  ['shared_20resource_20in_20concurrent_20tasks_8',['Advanced example: Using RTOS::Mutex for protecting a shared resource in concurrent tasks.',['../X:/Lib/IAR/inc/Lib/RTOS/Mutex.hpp#advanced-example-using-rtosmutex-for-protecting-a-shared-resource-in-concurrent-tasks',1,'']]],
  ['short_20busy_20wait_20delays_20in_20embedded_20systems_9',['Using Delay for short busy-wait delays in embedded systems.',['../X:/Lib/IAR/inc/Lib/Helper/Delay.hpp#using-delay-for-short-busy-wait-delays-in-embedded-systems',1,'']]],
  ['simple_20open_20ethercat_20slave_20or_20soes_10',['Simple Open EtherCAT Slave or SOES',['../index.html',1,'']]],
  ['slave_20or_20soes_11',['Simple Open EtherCAT Slave or SOES',['../index.html',1,'']]],
  ['smoothing_20noisy_20sensor_20data_12',['Example of Kalman filter usage for smoothing noisy sensor data.',['../X:/Lib/IAR/inc/Lib/Math/Filter/Kalman.hpp#example-of-kalman-filter-usage-for-smoothing-noisy-sensor-data',1,'']]],
  ['soes_13',['Simple Open EtherCAT Slave or SOES',['../index.html',1,'']]],
  ['specializations_20for_20various_20use_20cases_20in_20embedded_20systems_14',['It provides convenient access to ADC port specializations for various use cases in embedded systems.',['../d9/d8d/namespace_lib_1_1_h_a_l.html#it-provides-convenient-access-to-adc-port-specializations-for-various-use-cases-in-embedded-systems',1,'']]],
  ['spi_20communication_20with_20spiportbase_15',['Asynchronous SPI communication with SpiPortBase.',['../X:/Lib/IAR/inc/Lib/HAL/core/SPI/SpiPortBase.hpp#asynchronous-spi-communication-with-spiportbase',1,'']]],
  ['spiportbase_16',['Asynchronous SPI communication with SpiPortBase.',['../X:/Lib/IAR/inc/Lib/HAL/core/SPI/SpiPortBase.hpp#asynchronous-spi-communication-with-spiportbase',1,'']]],
  ['spline_20interpolation_20with_20standard_20output_17',['Example: Cubic spline interpolation with standard output',['../X:/Lib/IAR/inc/Lib/Math/Interpolation/CubicInterpolation.hpp#example-cubic-spline-interpolation-with-standard-output',1,'']]],
  ['standard_20output_18',['standard output',['../X:/Lib/IAR/inc/Lib/RTOS/Queue.hpp#example-usage-of-rtosqueue-with-standard-output',1,'Example usage of RTOS::Queue with standard output.'],['../X:/Lib/IAR/inc/Lib/Math/Interpolation/CubicInterpolation.hpp#example-cubic-spline-interpolation-with-standard-output',1,'Example: Cubic spline interpolation with standard output']]],
  ['storage_19',['Managing dynamic buffers for data storage.',['../X:/Lib/IAR/inc/Lib/Helper/Buffer/Buffer.hpp#managing-dynamic-buffers-for-data-storage',1,'']]],
  ['stringhelper_20utilities_20',['Example usage of StringHelper utilities.',['../X:/Lib/IAR/inc/Lib/Helper/StringHelper.hpp#example-usage-of-stringhelper-utilities',1,'']]],
  ['sunrise_20and_20sunset_20times_21',['Calculating Sunrise and Sunset Times',['../X:/Lib/IAR/inc/Lib/Helper/Sunset.hpp#calculating-sunrise-and-sunset-times',1,'']]],
  ['sunset_20times_22',['Calculating Sunrise and Sunset Times',['../X:/Lib/IAR/inc/Lib/Helper/Sunset.hpp#calculating-sunrise-and-sunset-times',1,'']]],
  ['swapping_20example_23',['Byte-Order Swapping Example',['../X:/Lib/IAR/inc/Lib/Helper/SwapBytes.hpp#byte-order-swapping-example',1,'']]],
  ['system_20class_24',['Example usage of System class.',['../X:/Lib/IAR/inc/Lib/System/System.hpp#example-usage-of-system-class',1,'']]],
  ['systems_25',['systems',['../d9/d8d/namespace_lib_1_1_h_a_l.html#it-provides-convenient-access-to-adc-port-specializations-for-various-use-cases-in-embedded-systems',1,'It provides convenient access to ADC port specializations for various use cases in embedded systems.'],['../X:/Lib/IAR/inc/Lib/Helper/Delay.hpp#using-delay-for-short-busy-wait-delays-in-embedded-systems',1,'Using Delay for short busy-wait delays in embedded systems.']]]
];
