var searchData=
[
  ['features_0',['Key Features',['../da/dec/a00080.html#key-features',1,'']]],
  ['filter_20usage_20for_20smoothing_20noisy_20sensor_20data_1',['Example of Kalman filter usage for smoothing noisy sensor data.',['../X:/Lib/IAR/inc/Lib/Math/Filter/Kalman.hpp#example-of-kalman-filter-usage-for-smoothing-noisy-sensor-data',1,'']]],
  ['float_20values_2',['Example of using LinearInterpolation for float values.',['../X:/Lib/IAR/inc/Lib/Math/Interpolation/LinearInterpolation.hpp#example-of-using-linearinterpolation-for-float-values',1,'']]],
  ['for_20a_20data_20buffer_3',['for a data buffer',['../X:/Lib/IAR/inc/Lib/Helper/crc16.hpp#computing-crc16-checksum-for-a-data-buffer',1,'Computing CRC16 checksum for a data buffer.'],['../X:/Lib/IAR/inc/Lib/Helper/CityHash.hpp#computing-hash-for-a-data-buffer',1,'Computing hash for a data buffer.']]],
  ['for_20ascii_20character_20conversion_4',['Example usage of Ascii class for ASCII character conversion.',['../X:/Lib/IAR/inc/Lib/Helper/Convert/Ascii.hpp#example-usage-of-ascii-class-for-ascii-character-conversion',1,'']]],
  ['for_20data_20storage_5',['Managing dynamic buffers for data storage.',['../X:/Lib/IAR/inc/Lib/Helper/Buffer/Buffer.hpp#managing-dynamic-buffers-for-data-storage',1,'']]],
  ['for_20encoding_20and_20decoding_20with_20error_20correction_6',['Example usage of HammingCode for encoding and decoding with error correction.',['../X:/Lib/IAR/inc/Lib/Math/HammingCode.hpp#example-usage-of-hammingcode-for-encoding-and-decoding-with-error-correction',1,'']]],
  ['for_20float_20values_7',['Example of using LinearInterpolation for float values.',['../X:/Lib/IAR/inc/Lib/Math/Interpolation/LinearInterpolation.hpp#example-of-using-linearinterpolation-for-float-values',1,'']]],
  ['for_20managing_20a_20collection_20of_20integers_8',['Basic usage of ContainerBase for managing a collection of integers.',['../X:/Lib/IAR/inc/Lib/Helper/ContainerBase.hpp#basic-usage-of-containerbase-for-managing-a-collection-of-integers',1,'']]],
  ['for_20percentage_20to_20dbm_20conversion_9',['Example usage of Percent class for percentage to dBM conversion.',['../X:/Lib/IAR/inc/Lib/Helper/Convert/Percent.hpp#example-usage-of-percent-class-for-percentage-to-dbm-conversion',1,'']]],
  ['for_20protecting_20a_20shared_20resource_20in_20concurrent_20tasks_10',['Advanced example: Using RTOS::Mutex for protecting a shared resource in concurrent tasks.',['../X:/Lib/IAR/inc/Lib/RTOS/Mutex.hpp#advanced-example-using-rtosmutex-for-protecting-a-shared-resource-in-concurrent-tasks',1,'']]],
  ['for_20sending_20and_20receiving_20messages_11',['Example usage of RTOS::MessageBuffer for sending and receiving messages.',['../X:/Lib/IAR/inc/Lib/RTOS/MessageBuffer.hpp#example-usage-of-rtosmessagebuffer-for-sending-and-receiving-messages',1,'']]],
  ['for_20short_20busy_20wait_20delays_20in_20embedded_20systems_12',['Using Delay for short busy-wait delays in embedded systems.',['../X:/Lib/IAR/inc/Lib/Helper/Delay.hpp#using-delay-for-short-busy-wait-delays-in-embedded-systems',1,'']]],
  ['for_20smoothing_20noisy_20sensor_20data_13',['Example of Kalman filter usage for smoothing noisy sensor data.',['../X:/Lib/IAR/inc/Lib/Math/Filter/Kalman.hpp#example-of-kalman-filter-usage-for-smoothing-noisy-sensor-data',1,'']]],
  ['for_20temperature_20regulation_14',['Example usage of the Pid controller for temperature regulation.',['../X:/Lib/IAR/inc/Lib/Math/Pid.hpp#example-usage-of-the-pid-controller-for-temperature-regulation',1,'']]],
  ['for_20thread_20safe_20access_15',['Example usage of RTOS::Mutex and MutexGuard for thread-safe access.',['../X:/Lib/IAR/inc/Lib/RTOS/Mutex.hpp#example-usage-of-rtosmutex-and-mutexguard-for-thread-safe-access',1,'']]],
  ['for_20usb_20serial_20repeater_20functionality_16',['Example usage of &lt;span class=&quot;tt&quot;&gt;SerialPortRepeaterBase&lt;/span&gt; for USB serial repeater functionality.',['../X:/Lib/IAR/inc/Lib/USB/SerialPortRepeaterBase.hpp#example-usage-of-serialportrepeaterbase-for-usb-serial-repeater-functionality',1,'']]],
  ['freertos_20queue_20sets_17',['Example usage of RTOS::QueueSet with FreeRTOS queue sets.',['../X:/Lib/IAR/inc/Lib/RTOS/QueueSet.hpp#example-usage-of-rtosqueueset-with-freertos-queue-sets',1,'']]],
  ['functionality_18',['Example usage of &lt;span class=&quot;tt&quot;&gt;SerialPortRepeaterBase&lt;/span&gt; for USB serial repeater functionality.',['../X:/Lib/IAR/inc/Lib/USB/SerialPortRepeaterBase.hpp#example-usage-of-serialportrepeaterbase-for-usb-serial-repeater-functionality',1,'']]]
];
