IAR Library: RTOS::TickCounter Class Reference
RTOS::TickCounter Class Reference
TickCounter utility for FreeRTOS tick/time conversions and elapsed/timeout calculations.
Public Types
using TickType = TickType_t
Static Public Member Functions
static TickType get ()
Get the current tick count.
static TickType getFromISR ()
Get the current tick count from ISR context.
static TickType msToTicks (uint32_t ms)
Convert milliseconds to ticks.
static uint32_t ticksToMs (TickType ticks)
Convert ticks to milliseconds.
static TickType secondsToTicks (uint32_t seconds)
Convert seconds to ticks.
static uint32_t ticksToSeconds (TickType ticks)
Convert ticks to seconds.
static constexpr uint32_t getTickPeriodMs ()
Get the tick period in milliseconds.
static constexpr uint32_t getTickRateHz ()
Get the tick rate in Hertz.
static constexpr TickType getMaxDelay ()
Get the maximum delay in ticks.
static TickType getElapsedTicks (TickType startTicks, TickType endTicks)
Calculate elapsed ticks between two tick counts (handles overflow).
static uint32_t getElapsedMs (TickType startTicks, TickType endTicks)
Calculate elapsed milliseconds between two tick counts.
static uint32_t getElapsedMsSince (TickType startTicks)
Calculate elapsed milliseconds since a start tick count.
static TickType getElapsedTicksSince (TickType startTicks)
Calculate elapsed ticks since a start tick count.
static bool hasTimedOut (TickType startTicks, uint32_t timeoutMs)
Check if a timeout (in milliseconds) has occurred since start tick.
static bool hasTimedOutTicks (TickType startTicks, TickType timeoutTicks)
Check if a timeout (in ticks) has occurred since start tick.
static uint32_t getRemainingTimeMs (TickType startTicks, uint32_t timeoutMs)
Get remaining time in milliseconds before timeout.
static TickType getRemainingTicks (TickType startTicks, TickType timeoutTicks)
Get remaining ticks before timeout.
Detailed Description
TickCounter utility for FreeRTOS tick/time conversions and elapsed/timeout calculations.
Provides static methods for converting between ticks and milliseconds/seconds, calculating elapsed time, and checking timeouts. Ensures type safety and overflow protection.
See also
https://github.com/panchev68-Library/IAR/blob/c7a278579c85aecf574831f2c2d77005a66d21c2/inc/Lib/RTOS/doc/TickCounter.md
Member Function Documentation
get()
TickType RTOS::TickCounter::get () inline static
Get the current tick count.
Returns
Current tick count.
Referenced by Lib::Digi::API::Connection::Info::Period::beginMeasurement(), Lib::Digi::API::Connection::Info::Period::endMeasurement(), getElapsedMsSince(), getElapsedTicksSince(), RTOS::Timeout::immediate(), RTOS::Timeout::reset(), RTOS::Timeout::set(), Lib::Helper::TimePeriod::start(), RTOS::TickService::start(), and Lib::Helper::TimePeriod::stop().
getElapsedMs()
uint32_t RTOS::TickCounter::getElapsedMs (TickType startTicks, TickType endTicks) inline static
Calculate elapsed milliseconds between two tick counts.
Parameters
startTicks Start tick count.
endTicks End tick count.
Returns
Elapsed milliseconds.
Referenced by getElapsedMsSince().
getElapsedMsSince()
uint32_t RTOS::TickCounter::getElapsedMsSince (TickType startTicks) inline static
Calculate elapsed milliseconds since a start tick count.
Parameters
startTicks Start tick count.
Returns
Elapsed milliseconds.
Referenced by getRemainingTimeMs(), and hasTimedOut().
getElapsedTicks()
TickType RTOS::TickCounter::getElapsedTicks (TickType startTicks, TickType endTicks) inline static
Calculate elapsed ticks between two tick counts (handles overflow).
Parameters
startTicks Start tick count.
endTicks End tick count.
Returns
Elapsed ticks.
Referenced by getElapsedMs(), getElapsedTicksSince(), and RTOS::TickService::start().
getElapsedTicksSince()
TickType RTOS::TickCounter::getElapsedTicksSince (TickType startTicks) inline static
Calculate elapsed ticks since a start tick count.
Parameters
startTicks Start tick count.
Returns
Elapsed ticks.
Referenced by RTOS::Timeout::getElapsed(), getRemainingTicks(), and hasTimedOutTicks().
getFromISR()
TickType RTOS::TickCounter::getFromISR () inline static
Get the current tick count from ISR context.
Returns
Current tick count.
getMaxDelay()
constexpr TickType RTOS::TickCounter::getMaxDelay () inline static constexpr
Get the maximum delay in ticks.
Returns
Maximum delay in ticks.
getRemainingTicks()
TickType RTOS::TickCounter::getRemainingTicks (TickType startTicks, TickType timeoutTicks) inline static
Get remaining ticks before timeout.
Parameters
startTicks Start tick count.
timeoutTicks Timeout in ticks.
Returns
Remaining ticks before timeout.
Referenced by RTOS::Timeout::getRemaining().
getRemainingTimeMs()
uint32_t RTOS::TickCounter::getRemainingTimeMs (TickType startTicks, uint32_t timeoutMs) inline static
Get remaining time in milliseconds before timeout.
Parameters
startTicks Start tick count.
timeoutMs Timeout in milliseconds.
Returns
Remaining milliseconds before timeout.
getTickPeriodMs()
constexpr uint32_t RTOS::TickCounter::getTickPeriodMs () inline static constexpr
Get the tick period in milliseconds.
Returns
Tick period in milliseconds.
Referenced by msToTicks(), and ticksToMs().
getTickRateHz()
constexpr uint32_t RTOS::TickCounter::getTickRateHz () inline static constexpr
Get the tick rate in Hertz.
Returns
Tick rate in Hertz.
hasTimedOut()
bool RTOS::TickCounter::hasTimedOut (TickType startTicks, uint32_t timeoutMs) inline static
Check if a timeout (in milliseconds) has occurred since start tick.
Parameters
startTicks Start tick count.
timeoutMs Timeout in milliseconds.
Returns
true if timed out, false otherwise.
hasTimedOutTicks()
bool RTOS::TickCounter::hasTimedOutTicks (TickType startTicks, TickType timeoutTicks) inline static
Check if a timeout (in ticks) has occurred since start tick.
Parameters
startTicks Start tick count.
timeoutTicks Timeout in ticks.
Returns
true if timed out, false otherwise.
Referenced by RTOS::Timeout::isExpired().
msToTicks()
TickType RTOS::TickCounter::msToTicks (uint32_t ms) inline static
Convert milliseconds to ticks.
Parameters
ms Milliseconds to convert.
Returns
Equivalent ticks.
Precondition
ms must be less than or equal to max representable ticks.
Referenced by RTOS::Kernel::delayMs(), RTOS::Timeout::extendMs(), RTOS::Timeout::fromMilliseconds(), secondsToTicks(), RTOS::Timeout::setMilliseconds(), RTOS::TickService::start(), RTOS::EventGroup::syncBits(), RTOS::Semaphore::takeMs(), RTOS::EventGroup::waitForBitsMs(), and RTOS::Timeout::willExpireWithinMs().
secondsToTicks()
TickType RTOS::TickCounter::secondsToTicks (uint32_t seconds) inline static
Convert seconds to ticks.
Parameters
seconds Seconds to convert.
Returns
Equivalent ticks.
Referenced by RTOS::Timeout::fromSeconds(), and RTOS::Timeout::setSeconds().
ticksToMs()
uint32_t RTOS::TickCounter::ticksToMs (TickType ticks) inline static
Convert ticks to milliseconds.
Parameters
ticks Ticks to convert.
Returns
Equivalent milliseconds.
Referenced by RTOS::Timeout::getDurationMs(), getElapsedMs(), RTOS::Timeout::getElapsedMs(), RTOS::Timeout::getRemainingMs(), RTOS::Kernel::getTickCountMs(), and ticksToSeconds().
ticksToSeconds()
uint32_t RTOS::TickCounter::ticksToSeconds (TickType ticks) inline static
Convert ticks to seconds.
Parameters
ticks Ticks to convert.
Returns
Equivalent seconds.