IAR Library: Lib::Ethernet::IpAddress Class Reference
Lib::Ethernet::IpAddress Class Reference
IpAddress class.
Public Member Functions
IpAddress ()
Constructor of the IpAddress class.
IpAddress (uint8_t first, uint8_t second, uint8_t third, uint8_t fourth)
Constructor of the IpAddress class.
IpAddress (const std::array< uint8_t, 4 > &address)
Constructor of the IpAddress class.
IpAddress (const uint8_t address[4])
Constructor of the IpAddress class.
virtual ~IpAddress ()=default
Destructor of the IpAddress class.
uint8_t operator[] (size_t index) const
Subscript operator of the IpAddress class.
const std::array< uint8_t, 4 > & get () const
Returns the internal array representing the IP address.
virtual void set (const uint8_t *address)
Sets the IP address from a pointer to 4 octets.
const uint8_t * data () const
Returns a pointer to the internal array data.
constexpr size_t size () const
Returns the size of the IP address (always 4).
virtual std::string toString () const
Converts the IP address to a string representation.
bool fromString (const std::string &str)
Parses an IP address from a string and sets the internal value.
Static Public Member Functions
static std::string toString (const std::array< uint8_t, 4 > &address)
Converts an IP address array to a string representation.
static std::string toString (const uint8_t *address)
Converts an IP address from a pointer to a string representation.
static bool fromString (const std::string &str, std::array< uint8_t, 4 > &address)
Parses an IP address from a string into an array.
static bool validateString (const std::string &str)
Validates if a string is a valid IPv4 address.
Protected Member Functions
IpAddress (uint32_t value)
Constructor of the IpAddress class.
virtual void set (uint8_t first, uint8_t second, uint8_t third, uint8_t fourth)
Sets the IP address from four octets.
virtual void set (uint32_t value)
Sets the IP address from a 32-bit integer.
Detailed Description
IpAddress class.
Represents an IPv4 address and provides utility methods for conversion, validation, and access.
Constructor & Destructor Documentation
IpAddress() [1/5]
Lib::Ethernet::IpAddress::IpAddress () inline
Constructor of the IpAddress class.
IpAddress() [2/5]
Lib::Ethernet::IpAddress::IpAddress (uint8_t first, uint8_t second, uint8_t third, uint8_t fourth) inline
Constructor of the IpAddress class.
Parameters
first First octet of the IP address.
second Second octet of the IP address.
third Third octet of the IP address.
fourth Fourth octet of the IP address.
IpAddress() [3/5]
Lib::Ethernet::IpAddress::IpAddress (const std::array< uint8_t, 4 > & address) inline
Constructor of the IpAddress class.
Parameters
address Array containing the IP address octets.
IpAddress() [4/5]
Lib::Ethernet::IpAddress::IpAddress (const uint8_t address[4]) inline
Constructor of the IpAddress class.
Parameters
address Pointer to an array of 4 octets.
~IpAddress()
virtual Lib::Ethernet::IpAddress::~IpAddress () virtual default
Destructor of the IpAddress class.
IpAddress() [5/5]
Lib::Ethernet::IpAddress::IpAddress (uint32_t value) inline protected
Constructor of the IpAddress class.
Parameters
value 32-bit integer representing the IP address.
Member Function Documentation
data()
const uint8_t * Lib::Ethernet::IpAddress::data () const inline
Returns a pointer to the internal array data.
Returns
Pointer to the array data.
fromString() [1/2]
bool Lib::Ethernet::IpAddress::fromString (const std::string & str) inline
Parses an IP address from a string and sets the internal value.
Parameters
str String representation of the IP address.
Returns
true if parsing was successful, false otherwise.
Referenced by fromString().
fromString() [2/2]
bool Lib::Ethernet::IpAddress::fromString (const std::string & str, std::array< uint8_t, 4 > & address) inline static
Parses an IP address from a string into an array.
Parameters
str String representation of the IP address.
[out] address Output array to store the parsed octets.
Returns
true if parsing was successful, false otherwise.
get()
const std::array< uint8_t, 4 > & Lib::Ethernet::IpAddress::get () const inline
Returns the internal array representing the IP address.
Returns
Reference to the internal array.
Referenced by Lib::Ethernet::Wiznet::Socket::connect(), Lib::Ethernet::Wiznet::Socket::receiveFrom(), and Lib::Ethernet::Wiznet::Socket::sendTo().
operator[]()
uint8_t Lib::Ethernet::IpAddress::operator[] (size_t index) const inline
Subscript operator of the IpAddress class.
Parameters
index Index of the octet to access.
Returns
Value of the octet at the specified index.
set() [1/3]
virtual void Lib::Ethernet::IpAddress::set (const uint8_t * address) inline virtual
Sets the IP address from a pointer to 4 octets.
Parameters
address Pointer to an array of 4 octets.
Referenced by IpAddress().
set() [2/3]
virtual void Lib::Ethernet::IpAddress::set (uint32_t value) inline protected virtual
Sets the IP address from a 32-bit integer.
Parameters
value 32-bit integer representing the IP address.
set() [3/3]
virtual void Lib::Ethernet::IpAddress::set (uint8_t first, uint8_t second, uint8_t third, uint8_t fourth) inline protected virtual
Sets the IP address from four octets.
Parameters
first First octet.
second Second octet.
third Third octet.
fourth Fourth octet.
size()
size_t Lib::Ethernet::IpAddress::size () const inline constexpr
Returns the size of the IP address (always 4).
Returns
Size of the IP address.
toString() [1/3]
virtual std::string Lib::Ethernet::IpAddress::toString () const inline virtual
Converts the IP address to a string representation.
Returns
String representation of the IP address.
Referenced by toString().
toString() [2/3]
std::string Lib::Ethernet::IpAddress::toString (const std::array< uint8_t, 4 > & address) inline static
Converts an IP address array to a string representation.
Parameters
address Array containing the IP address octets.
Returns
String representation of the IP address.
toString() [3/3]
std::string Lib::Ethernet::IpAddress::toString (const uint8_t * address) inline static
Converts an IP address from a pointer to a string representation.
Parameters
address Pointer to an array of 4 octets.
Returns
String representation of the IP address.
validateString()
bool Lib::Ethernet::IpAddress::validateString (const std::string & str) inline static
Validates if a string is a valid IPv4 address.
Parameters
str String to validate.
Returns
true if the string is a valid IPv4 address, false otherwise.