IAR Library: Lib::Canbus::CanServiceBase Class Reference
Lib::Canbus::CanServiceBase Class Reference abstract
Base class for CAN bus services.
Classes
struct Diagnostic
Diagnostic info for CAN bus communication.
Public Member Functions
CanServiceBase (CAN_HandleTypeDef *handle)
virtual bool start (uint8_t serviceId)
Starts the CAN service.
virtual bool stop ()
Stops the CAN service.
virtual bool receive (CanRxMessage &message, uint32_t timeout)
Receives a CAN message.
virtual bool send (uint8_t messageId, uint32_t timeout=SEND_TIMEOUT)
Sends a CAN message with no data.
virtual bool send (uint8_t messageId, const void *data, size_t length, uint32_t timeout=SEND_TIMEOUT) override
Sends a CAN message with data.
virtual bool send (uint8_t messageId, uint64_t value, uint32_t timeout=SEND_TIMEOUT)
Sends a CAN message with a 64-bit value.
const Diagnostic & getDiagnostic () const
Gets the diagnostic information.
virtual void handleMessageReceivedEvent (const CanRxMessage &message) override
Handles the event when a CAN message is received.
virtual void handleErrorEvent (uint32_t errorCode) override
Handles the event when a CAN error occurs.
virtual void taskFn ()=0
Task function for the CAN service.
Protected Attributes
uint8_t id {0}
RTOS::Task task
Diagnostic diagnostic
RTOS::Queue< CanRxMessage, 8 > queueRxMessage
Static Protected Attributes
static constexpr uint32_t SEND_TIMEOUT {50}
static constexpr uint32_t RECEIVE_TIMEOUT {50}
Detailed Description
Base class for CAN bus services.
Provides start/stop, send/receive, diagnostics, and event handling for CAN messages.
Member Function Documentation
getDiagnostic()
const Diagnostic & Lib::Canbus::CanServiceBase::getDiagnostic () const inline
Gets the diagnostic information.
Returns
Reference to the diagnostic structure.
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::getDiagnostic().
handleErrorEvent()
virtual void Lib::Canbus::CanServiceBase::handleErrorEvent (uint32_t errorCode) inline override virtual
Handles the event when a CAN error occurs.
Parameters
errorCode The error code.
handleMessageReceivedEvent()
virtual void Lib::Canbus::CanServiceBase::handleMessageReceivedEvent (const CanRxMessage & message) inline override virtual
Handles the event when a CAN message is received.
Parameters
message The received CAN message.
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::handleMessageReceivedEvent().
receive()
virtual bool Lib::Canbus::CanServiceBase::receive (CanRxMessage & message, uint32_t timeout) inline virtual
Receives a CAN message.
Parameters
[out] message Reference to the received message.
timeout Timeout in milliseconds.
Returns
true if a message was received, false otherwise.
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::taskFn().
send() [1/3]
virtual bool Lib::Canbus::CanServiceBase::send (uint8_t messageId, const void * data, size_t length, uint32_t timeout = SEND_TIMEOUT) inline override virtual
Sends a CAN message with data.
Parameters
messageId Message identifier.
data Pointer to the data buffer.
length Length of the data buffer.
timeout Timeout in milliseconds.
Returns
true if the message was sent, false otherwise.
Reimplemented in Lib::Canbus::Service< CanServiceMode::SERVER >.
send() [2/3]
virtual bool Lib::Canbus::CanServiceBase::send (uint8_t messageId, uint32_t timeout = SEND_TIMEOUT) inline virtual
Sends a CAN message with no data.
Parameters
messageId Message identifier.
timeout Timeout in milliseconds.
Returns
true if the message was sent, false otherwise.
Reimplemented in Lib::Canbus::Service< CanServiceMode::SERVER >.
Referenced by send(), send(), Lib::Canbus::Service< CanServiceMode::SERVER >::send(), Lib::Canbus::Service< CanServiceMode::SERVER >::send(), and Lib::Canbus::Service< CanServiceMode::SERVER >::send().
send() [3/3]
virtual bool Lib::Canbus::CanServiceBase::send (uint8_t messageId, uint64_t value, uint32_t timeout = SEND_TIMEOUT) inline virtual
Sends a CAN message with a 64-bit value.
Parameters
messageId Message identifier.
value 64-bit value to send.
timeout Timeout in milliseconds.
Returns
true if the message was sent, false otherwise.
Reimplemented in Lib::Canbus::Service< CanServiceMode::SERVER >.
start()
virtual bool Lib::Canbus::CanServiceBase::start (uint8_t serviceId) inline virtual
Starts the CAN service.
Parameters
serviceId Service identifier.
Returns
true if the service started successfully, false otherwise.
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::start().
stop()
virtual bool Lib::Canbus::CanServiceBase::stop () inline virtual
Stops the CAN service.
Returns
true if the service stopped successfully, false otherwise.
Reimplemented in Lib::Canbus::Service< CanServiceMode::SERVER >.
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::stop().
taskFn()
virtual void Lib::Canbus::CanServiceBase::taskFn () pure virtual
Task function for the CAN service.
Implemented in Lib::Canbus::Service< CanServiceMode::SERVER >.
Referenced by start().
Member Data Documentation
diagnostic
Diagnostic Lib::Canbus::CanServiceBase::diagnostic protected
Diagnostic info.
Referenced by getDiagnostic(), handleErrorEvent(), handleMessageReceivedEvent(), and send().
id
uint8_t Lib::Canbus::CanServiceBase::id {0} protected
Service identifier.
queueRxMessage
RTOS::Queue<CanRxMessage, 8> Lib::Canbus::CanServiceBase::queueRxMessage protected
Rx message queue.
Referenced by handleMessageReceivedEvent(), receive(), and start().
RECEIVE_TIMEOUT
uint32_t Lib::Canbus::CanServiceBase::RECEIVE_TIMEOUT {50} static constexpr protected
Receive timeout (ms).
Referenced by Lib::Canbus::Service< CanServiceMode::SERVER >::taskFn().
SEND_TIMEOUT
uint32_t Lib::Canbus::CanServiceBase::SEND_TIMEOUT {50} static constexpr protected
Send timeout (ms).
Referenced by send(), send(), send(), Lib::Canbus::Service< CanServiceMode::SERVER >::send(), Lib::Canbus::Service< CanServiceMode::SERVER >::send(), and Lib::Canbus::Service< CanServiceMode::SERVER >::send().
task
RTOS::Task Lib::Canbus::CanServiceBase::task protected
FreeRTOS task.
Referenced by start(), and stop().