IAR Library: Lib::USB::SerialPortRepeaterBase Class Reference
Lib::USB::SerialPortRepeaterBase Class Reference
USB serial port repeater base class.
Classes
struct Config
Configuration for SerialPortRepeaterBase.
Public Member Functions
SerialPortRepeaterBase (const Config &config)
Constructor of the SerialPortRepeaterBase class.
virtual ~SerialPortRepeaterBase ()=default
Virtual destructor of the SerialPortRepeaterBase class.
virtual bool open () override
Open the serial port repeater.
virtual void close () override
Close the serial port repeater.
virtual void setModuleResetPin (bool value) override
Set the module reset pin.
virtual bool isPoweredByUSB ()
Check if powered by USB.
virtual void enableUSBPort (bool value)
Enable or disable the USB port.
void setResetPin (bool value)
Set the reset pin to a value.
bool send (const uint8_t *data, size_t length)
Send data through the serial port.
void setBaudRate (uint32_t baudRate)
Set baud rate for the serial port.
Public Attributes
std::function< void(bool)> onConnected
Protected Member Functions
virtual void signalReceivedBegin ()
Signal the beginning of a receive event.
virtual void signalReceivedEnd ()
Signal the end of a receive event.
virtual void signalTransmitBegin ()
Signal the beginning of a transmit event.
virtual void signalTransmitEnd ()
Signal the end of a transmit event.
void postReceivedCallback (const uint8_t *data, size_t length) override
Callback after data is received.
void postTransmitCallback () override
Callback after transmit completes.
Detailed Description
USB serial port repeater base class.
Extends SerialPort to provide USB serial port repeater functionality, including open/close, USB enable/disable, connection detection, and callback support.
Examples
Lib::USB::SerialPortRepeaterBase.
Constructor & Destructor Documentation
SerialPortRepeaterBase()
Lib::USB::SerialPortRepeaterBase::SerialPortRepeaterBase (const Config & config) inline explicit
Constructor of the SerialPortRepeaterBase class.
Parameters
config Configuration settings.
~SerialPortRepeaterBase()
virtual Lib::USB::SerialPortRepeaterBase::~SerialPortRepeaterBase () virtual default
Virtual destructor of the SerialPortRepeaterBase class.
Member Function Documentation
close()
virtual void Lib::USB::SerialPortRepeaterBase::close () inline override virtual
Close the serial port repeater.
Reimplemented from Lib::USB::SerialPort.
enableUSBPort()
virtual void Lib::USB::SerialPortRepeaterBase::enableUSBPort (bool value) inline virtual
Enable or disable the USB port.
Parameters
value true to enable, false to disable.
Referenced by close(), and open().
isPoweredByUSB()
virtual bool Lib::USB::SerialPortRepeaterBase::isPoweredByUSB () inline virtual
Check if powered by USB.
Returns
true if powered by USB, false otherwise.
open()
virtual bool Lib::USB::SerialPortRepeaterBase::open () inline override virtual
Open the serial port repeater.
Returns
true if opened successfully, false otherwise.
Reimplemented from Lib::USB::SerialPort.
Examples
Lib::USB::SerialPortRepeaterBase.
postReceivedCallback()
void Lib::USB::SerialPortRepeaterBase::postReceivedCallback (const uint8_t * data, size_t length) inline override protected virtual
Callback after data is received.
Parameters
data Received data pointer.
length Received data size.
Reimplemented from Lib::USB::SerialPort.
postTransmitCallback()
void Lib::USB::SerialPortRepeaterBase::postTransmitCallback () inline override protected virtual
Callback after transmit completes.
Reimplemented from Lib::USB::SerialPort.
send()
bool Lib::USB::SerialPort::send (const uint8_t * data, size_t length) inline inherited
Send data through the serial port.
Parameters
data Data buffer pointer.
length Data length.
Returns
true if sent successfully, false otherwise.
setBaudRate()
void Lib::USB::SerialPort::setBaudRate (uint32_t baudRate) inline inherited
Set baud rate for the serial port.
Parameters
baudRate Baud rate.
setModuleResetPin()
virtual void Lib::USB::SerialPortRepeaterBase::setModuleResetPin (bool value) inline override virtual
Set the module reset pin.
Parameters
value true to set high, false to set low.
setResetPin()
void Lib::USB::SerialPort::setResetPin (bool value) inline inherited
Set the reset pin to a value.
Parameters
value Pin value (true = high, false = low).
Referenced by close(), and open().
signalReceivedBegin()
virtual void Lib::USB::SerialPortRepeaterBase::signalReceivedBegin () inline protected virtual
Signal the beginning of a receive event.
Referenced by postReceivedCallback().
signalReceivedEnd()
virtual void Lib::USB::SerialPortRepeaterBase::signalReceivedEnd () inline protected virtual
Signal the end of a receive event.
Referenced by postReceivedCallback().
signalTransmitBegin()
virtual void Lib::USB::SerialPortRepeaterBase::signalTransmitBegin () inline protected virtual
Signal the beginning of a transmit event.
Referenced by postTransmitCallback().
signalTransmitEnd()
virtual void Lib::USB::SerialPortRepeaterBase::signalTransmitEnd () inline protected virtual
Signal the end of a transmit event.
Referenced by postTransmitCallback().
Member Data Documentation
onConnected
std::function<void(bool)> Lib::USB::SerialPortRepeaterBase::onConnected
Callback for USB connection state changes.
Examples
Lib::USB::SerialPortRepeaterBase.