IAR Library: Lib::Helper::Convert::HexHelper Class Reference
Lib::Helper::Convert::HexHelper Class Reference
Utility class for hexadecimal and BCD conversions.
Static Public Member Functions
static constexpr char toAscii (uint8_t value)
Converts a 4-bit value to its ASCII hexadecimal character.
static constexpr uint32_t toBcd (uint16_t value)
Converts a 16-bit unsigned integer to BCD format.
static constexpr uint8_t toBcd8 (uint8_t value)
Converts an 8-bit unsigned integer to BCD format.
static constexpr uint8_t fromAscii (char ascii)
Converts an ASCII hexadecimal character to its 4-bit value.
Detailed Description
Utility class for hexadecimal and BCD conversions.
The HexHelper class provides static methods for converting between hexadecimal, ASCII, and BCD formats. It supports conversion of 4-bit values to ASCII hexadecimal characters, conversion of 8-bit and 16-bit unsigned integers to BCD format, and conversion of ASCII hexadecimal characters to their corresponding 4-bit values.
Member Function Documentation
fromAscii()
constexpr uint8_t Lib::Helper::Convert::HexHelper::fromAscii (char ascii) inline static constexpr
Converts an ASCII hexadecimal character to its 4-bit value.
Parameters
ascii ASCII character to convert.
Returns
4-bit value corresponding to the ASCII character.
toAscii()
constexpr char Lib::Helper::Convert::HexHelper::toAscii (uint8_t value) inline static constexpr
Converts a 4-bit value to its ASCII hexadecimal character.
Parameters
value 4-bit value to convert.
Returns
ASCII character representing the hexadecimal digit.
Referenced by Lib::Helper::Convert::Hex< uint16_t >::toBcdString(), Lib::Helper::Convert::Hex< uint8_t >::toBcdString(), Lib::Helper::Convert::Hex< uint16_t >::toString(), Lib::Helper::Convert::Hex< uint64_t >::toString(), and Lib::Helper::Convert::Hex< uint8_t >::toString().
toBcd()
constexpr uint32_t Lib::Helper::Convert::HexHelper::toBcd (uint16_t value) inline static constexpr
Converts a 16-bit unsigned integer to BCD format.
Parameters
value 16-bit unsigned integer value.
Returns
BCD representation as uint32_t.
Referenced by Lib::Helper::Convert::Hex< uint8_t >::toBcd().
toBcd8()
constexpr uint8_t Lib::Helper::Convert::HexHelper::toBcd8 (uint8_t value) inline static constexpr
Converts an 8-bit unsigned integer to BCD format.
Parameters
value 8-bit unsigned integer value.
Returns
BCD representation as uint8_t.