IAR Library: Lib::USB::SerialPort Class Reference
Lib::USB::SerialPort Class Reference
USB serial port interface.
Classes
struct Config
SerialPort configuration.
Public Member Functions
SerialPort (const Config &config)
Constructor of the SerialPort class.
virtual ~SerialPort ()=default
Virtual destructor of the SerialPort class.
virtual bool open ()
Open the serial port.
virtual void close ()
Close the serial port.
void setResetPin (bool value)
Set the reset pin to a value.
bool send (const uint8_t *data, size_t length)
Send data through the serial port.
void setBaudRate (uint32_t baudRate)
Set baud rate for the serial port.
virtual void postReceivedCallback (const uint8_t *data, size_t length)
Callback after data is received.
virtual void postTransmitCallback ()
Callback after transmit completes.
Detailed Description
USB serial port interface.
Provides methods for USB serial communication, including open/close, send, reset, baud rate management, and event callbacks. Encapsulates UART port management, USB reset pin control, RTOS task handling, and message buffering for efficient and reliable USB serial data transfer.
Examples
Lib::USB::SerialPort.
Constructor & Destructor Documentation
SerialPort()
Lib::USB::SerialPort::SerialPort (const Config & config) inline explicit
Constructor of the SerialPort class.
Parameters
config SerialPort configuration.
Referenced by Lib::USB::SerialPortRepeaterBase::SerialPortRepeaterBase().
~SerialPort()
virtual Lib::USB::SerialPort::~SerialPort () virtual default
Virtual destructor of the SerialPort class.
Member Function Documentation
close()
virtual void Lib::USB::SerialPort::close () inline virtual
Close the serial port.
Reimplemented in Lib::USB::SerialPortRepeaterBase.
Referenced by Lib::USB::SerialPortRepeaterBase::close().
open()
virtual bool Lib::USB::SerialPort::open () inline virtual
Open the serial port.
Returns
true if opened successfully, false otherwise.
Reimplemented in Lib::USB::SerialPortRepeaterBase.
Referenced by Lib::USB::SerialPortRepeaterBase::open().
postReceivedCallback()
virtual void Lib::USB::SerialPort::postReceivedCallback (const uint8_t * data, size_t length) inline virtual
Callback after data is received.
Parameters
data Received data pointer.
length Received data size.
Reimplemented in Lib::USB::SerialPortRepeaterBase.
postTransmitCallback()
virtual void Lib::USB::SerialPort::postTransmitCallback () inline virtual
Callback after transmit completes.
Reimplemented in Lib::USB::SerialPortRepeaterBase.
send()
bool Lib::USB::SerialPort::send (const uint8_t * data, size_t length) inline
Send data through the serial port.
Parameters
data Data buffer pointer.
length Data length.
Returns
true if sent successfully, false otherwise.
setBaudRate()
void Lib::USB::SerialPort::setBaudRate (uint32_t baudRate) inline
Set baud rate for the serial port.
Parameters
baudRate Baud rate.
setResetPin()
void Lib::USB::SerialPort::setResetPin (bool value) inline
Set the reset pin to a value.
Parameters
value Pin value (true = high, false = low).
Referenced by close(), and open().