IAR Library: RTOS::SemaphoreCounting Class Reference
RTOS::SemaphoreCounting Class Reference
Counting semaphore.
Public Types
using Handle = SemaphoreHandle_t
Public Member Functions
SemaphoreCounting (UBaseType_t maxCountParam, UBaseType_t initialCountParam)
Constructor of SemaphoreCounting class.
~SemaphoreCounting ()=default
Destructor of SemaphoreCounting class.
SemaphoreCounting (const SemaphoreCounting &)=delete
Copy constructor is deleted to prevent accidental copying of the underlying handle.
SemaphoreCounting & operator= (const SemaphoreCounting &)=delete
Copy assignment is deleted to prevent accidental copying of the underlying handle.
SemaphoreCounting (SemaphoreCounting &&)=delete
Move constructor is deleted because the class contains const members.
SemaphoreCounting & operator= (SemaphoreCounting &&)=delete
Move assignment is deleted because the class contains const members.
bool create () override
Creates the counting semaphore.
UBaseType_t getCount () const
Gets the current count of the semaphore.
UBaseType_t getMaxCount () const
Gets the maximum count of the semaphore.
UBaseType_t getInitialCount () const
Gets the initial count of the semaphore.
bool isAtMaxCount () const
Checks if the semaphore is at maximum count.
bool isEmpty () const
Checks if the semaphore is empty.
UBaseType_t getAvailableCount () const
Gets the available count (current count).
UBaseType_t getRemainingCapacity () const
Gets the remaining capacity before reaching maximum count.
virtual Handle getHandle () const noexcept
Returns the underlying semaphore handle.
virtual operator Handle & () noexcept
Conversion operator to handle reference.
virtual bool isCreated () const noexcept
Checks if the semaphore is created.
Protected Member Functions
virtual void destroy () noexcept
Destroys the semaphore and releases resources.
virtual bool take (TickType_t timeout=0) noexcept
Takes the semaphore with timeout.
virtual bool takeNow () noexcept
Takes the semaphore without waiting.
virtual bool takeForever () noexcept
Takes the semaphore, waiting forever.
virtual bool give () noexcept
Gives the semaphore.
virtual bool overwrite () noexcept
Overwrites the semaphore (take then give).
virtual bool takeFromISR () noexcept
Takes the semaphore from ISR context.
virtual bool giveFromISR () noexcept
Gives the semaphore from ISR context.
virtual bool overwriteFromISR () noexcept
Overwrites the semaphore from ISR context.
Protected Attributes
Handle handle = nullptr
Detailed Description
Counting semaphore.
Implements a counting semaphore with configurable maximum and initial count.
Examples
RTOS::SemaphoreCounting.
Member Typedef Documentation
Handle
using RTOS::SemaphoreBase::Handle = SemaphoreHandle_t inherited
Alias for FreeRTOS semaphore handle.
Constructor & Destructor Documentation
SemaphoreCounting() [1/3]
RTOS::SemaphoreCounting::SemaphoreCounting (UBaseType_t maxCountParam, UBaseType_t initialCountParam) inline
Constructor of SemaphoreCounting class.
Parameters
maxCountParam Maximum count for the semaphore.
initialCountParam Initial count for the semaphore.
Precondition
maxCountParam must be greater than 0.
initialCountParam must be less than or equal to maxCountParam.
Referenced by SemaphoreCounting(), SemaphoreCounting(), operator=(), and operator=().
~SemaphoreCounting()
RTOS::SemaphoreCounting::~SemaphoreCounting () default
Destructor of SemaphoreCounting class.
SemaphoreCounting() [2/3]
RTOS::SemaphoreCounting::SemaphoreCounting (const SemaphoreCounting &) delete
Copy constructor is deleted to prevent accidental copying of the underlying handle.
SemaphoreCounting() [3/3]
RTOS::SemaphoreCounting::SemaphoreCounting (SemaphoreCounting &&) delete
Move constructor is deleted because the class contains const members.
Member Function Documentation
create()
bool RTOS::SemaphoreCounting::create () inline override virtual
Creates the counting semaphore.
Returns
true if creation was successful, false otherwise.
Precondition
Semaphore handle must be null.
Postcondition
Semaphore handle is valid if creation succeeded.
Implements RTOS::SemaphoreBase.
Examples
RTOS::SemaphoreCounting.
destroy()
virtual void RTOS::SemaphoreBase::destroy () inline protected virtual noexcept inherited
Destroys the semaphore and releases resources.
Reimplemented in RTOS::Semaphore.
Referenced by ~SemaphoreBase(), RTOS::Semaphore::destroy(), destroy(), and operator=().
getAvailableCount()
UBaseType_t RTOS::SemaphoreCounting::getAvailableCount () const inline
Gets the available count (current count).
Returns
Current count value.
getCount()
UBaseType_t RTOS::SemaphoreCounting::getCount () const inline
Gets the current count of the semaphore.
Returns
Current count value.
Precondition
Semaphore handle must not be null.
Referenced by getAvailableCount(), getRemainingCapacity(), isAtMaxCount(), and isEmpty().
getHandle()
virtual Handle RTOS::SemaphoreBase::getHandle () const inline virtual noexcept inherited
Returns the underlying semaphore handle.
Returns
Semaphore handle.
getInitialCount()
UBaseType_t RTOS::SemaphoreCounting::getInitialCount () const inline
Gets the initial count of the semaphore.
Returns
Initial count value.
getMaxCount()
UBaseType_t RTOS::SemaphoreCounting::getMaxCount () const inline
Gets the maximum count of the semaphore.
Returns
Maximum count value.
getRemainingCapacity()
UBaseType_t RTOS::SemaphoreCounting::getRemainingCapacity () const inline
Gets the remaining capacity before reaching maximum count.
Returns
Remaining capacity value.
give()
virtual bool RTOS::SemaphoreBase::give () inline protected virtual noexcept inherited
Gives the semaphore.
Returns
true if given, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::give().
giveFromISR()
virtual bool RTOS::SemaphoreBase::giveFromISR () inline protected virtual noexcept inherited
Gives the semaphore from ISR context.
Returns
true if given, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::giveFromISR().
isAtMaxCount()
bool RTOS::SemaphoreCounting::isAtMaxCount () const inline
Checks if the semaphore is at maximum count.
Returns
true if current count is greater than or equal to maximum, false otherwise.
Examples
RTOS::SemaphoreCounting.
isCreated()
virtual bool RTOS::SemaphoreBase::isCreated () const inline virtual noexcept inherited
Checks if the semaphore is created.
Returns
true if created, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::isCreated().
isEmpty()
bool RTOS::SemaphoreCounting::isEmpty () const inline
Checks if the semaphore is empty.
Returns
true if current count is zero, false otherwise.
Examples
RTOS::SemaphoreCounting.
operator Handle &()
virtual RTOS::SemaphoreBase::operator Handle & () inline virtual noexcept inherited
Conversion operator to handle reference.
Returns
Reference to semaphore handle.
Reimplemented in RTOS::Semaphore.
operator=() [1/2]
SemaphoreCounting & RTOS::SemaphoreCounting::operator= (const SemaphoreCounting &) delete
Copy assignment is deleted to prevent accidental copying of the underlying handle.
operator=() [2/2]
SemaphoreCounting & RTOS::SemaphoreCounting::operator= (SemaphoreCounting &&) delete
Move assignment is deleted because the class contains const members.
overwrite()
virtual bool RTOS::SemaphoreBase::overwrite () inline protected virtual noexcept inherited
Overwrites the semaphore (take then give).
Returns
true if successful, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::overwrite().
overwriteFromISR()
virtual bool RTOS::SemaphoreBase::overwriteFromISR () inline protected virtual noexcept inherited
Overwrites the semaphore from ISR context.
Returns
true if successful, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::overwriteFromISR().
take()
virtual bool RTOS::SemaphoreBase::take (TickType_t timeout = 0) inline protected virtual noexcept inherited
Takes the semaphore with timeout.
Parameters
timeout Timeout in ticks.
Returns
true if taken, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::take(), takeForever(), and takeNow().
takeForever()
virtual bool RTOS::SemaphoreBase::takeForever () inline protected virtual noexcept inherited
Takes the semaphore, waiting forever.
Returns
true if taken, false otherwise.
takeFromISR()
virtual bool RTOS::SemaphoreBase::takeFromISR () inline protected virtual noexcept inherited
Takes the semaphore from ISR context.
Returns
true if taken, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::takeFromISR().
takeNow()
virtual bool RTOS::SemaphoreBase::takeNow () inline protected virtual noexcept inherited
Takes the semaphore without waiting.
Returns
true if taken, false otherwise.
Member Data Documentation
handle
Handle RTOS::SemaphoreBase::handle = nullptr protected inherited
Underlying FreeRTOS semaphore handle.
Referenced by ~SemaphoreBase(), RTOS::Semaphore::create(), RTOS::SemaphoreCounting::create(), destroy(), RTOS::Semaphore::getCount(), RTOS::SemaphoreCounting::getCount(), getHandle(), RTOS::Semaphore::getState(), give(), giveFromISR(), RTOS::Semaphore::isAvailable(), isCreated(), RTOS::Semaphore::isTaken(), operator Handle &(), operator=(), overwrite(), overwriteFromISR(), take(), and takeFromISR().