IAR Library: RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > Class Template Reference
RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > Class Template Reference
RAII wrapper for FreeRTOS queues.
Public Types
using Handle = QueueHandle_t
Public Member Functions
Queue () noexcept
Default constructor.
~Queue ()
Destructor of Queue class.
Queue (Queue &&other) noexcept
Move constructor of Queue class.
Queue & operator= (Queue &&other) noexcept
Move assignment operator of Queue class.
Queue (const Queue &)=delete
Queue & operator= (const Queue &)=delete
bool create ()
Creates a dynamic queue.
void destroy () noexcept
Destroys the queue.
void reset () noexcept
Resets the queue.
bool receive (T_ELEMENT_TYPE &item, TickType_t maxTicksToWait=portMAX_DELAY) const noexcept
Receives an item from the queue.
bool receiveFromISR (T_ELEMENT_TYPE &item) const noexcept
Receives an item from the queue in ISR context.
bool peek (T_ELEMENT_TYPE &item, TickType_t maxTicksToWait=0) const noexcept
Peeks at the front item without removing it.
bool peekFromISR (T_ELEMENT_TYPE &item) const noexcept
Peeks at the front item in ISR context.
bool send (const T_ELEMENT_TYPE &item, TickType_t maxTicksToWait=portMAX_DELAY) noexcept
Sends an item to the back of the queue.
bool sendToFront (const T_ELEMENT_TYPE &item, TickType_t maxTicksToWait=portMAX_DELAY) noexcept
Sends an item to the front of the queue.
bool sendToBack (const T_ELEMENT_TYPE &item, TickType_t maxTicksToWait=portMAX_DELAY) noexcept
Sends an item to the back of the queue.
bool sendToBackFromISR (const T_ELEMENT_TYPE &item) noexcept
Sends an item to the back in ISR context.
bool sendToFrontFromISR (const T_ELEMENT_TYPE &item) noexcept
Sends an item to the front in ISR context.
bool overwrite (const T_ELEMENT_TYPE &item) noexcept
Overwrites the front item.
bool overwriteFromISR (const T_ELEMENT_TYPE &item) noexcept
Overwrites the front item in ISR context.
size_t messagesWaiting () const noexcept
Gets the number of messages waiting.
size_t messagesWaitingFromISR () const noexcept
Gets the number of messages waiting in ISR context.
size_t spacesAvailable () const noexcept
Gets the number of spaces available.
bool isFull () const noexcept
Checks if the queue is full.
bool isEmpty () const noexcept
Checks if the queue is empty.
constexpr size_t capacity () const noexcept
Gets the queue capacity.
constexpr size_t elementSize () const noexcept
Gets the element size.
void addToRegistry (const std::string &name)
Adds the queue to the registry.
void removeFromRegistry () noexcept
Removes the queue from the registry.
Handle getHandle () const noexcept
Gets the handle.
operator Handle () const noexcept
Conversion to handle.
bool isCreated () const noexcept
Checks if the queue is created.
operator bool () const noexcept
Boolean conversion.
Static Public Attributes
static constexpr size_t LENGTH = QUEUE_LENGTH
static constexpr size_t ELEMENT_SIZE = sizeof(T_ELEMENT_TYPE)
Detailed Description
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1>
class RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >
RAII wrapper for FreeRTOS queues.
Provides type-safe operations for queue management, including creation, destruction, sending, receiving, and querying. Supports both dynamic and static allocation.
Template Parameters
T_ELEMENT_TYPE Element type, must be trivially copyable.
QUEUE_LENGTH Maximum number of elements in the queue.
Examples
RTOS::Queue.
Member Typedef Documentation
Handle
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> using RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::Handle = QueueHandle_t
Type alias for the FreeRTOS queue handle.
Constructor & Destructor Documentation
Queue() [1/3]
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::Queue () inline noexcept
Default constructor.
Referenced by Queue(), Queue(), operator=(), and operator=().
~Queue()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::~Queue () inline
Destructor of Queue class.
Queue() [2/3]
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::Queue (Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > && other) inline noexcept
Move constructor of Queue class.
Parameters
other Queue to move from.
Queue() [3/3]
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::Queue (const Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > &) delete
Copy constructor deleted.
Member Function Documentation
addToRegistry()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> void RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::addToRegistry (const std::string & name) inline
Adds the queue to the registry.
Parameters
name Registry name.
Precondition
Queue must be created. Name must not be empty.
Postcondition
Queue is registered.
capacity()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::capacity () const inline constexpr noexcept
Gets the queue capacity.
Returns
Capacity.
create()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::create () inline
Creates a dynamic queue.
Returns
true if successful, false otherwise.
Precondition
Queue must not be already created.
Postcondition
Queue is created and handle is valid.
Examples
RTOS::Queue.
destroy()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> void RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::destroy () inline noexcept
Destroys the queue.
Precondition
Queue must be created.
Postcondition
Queue handle is invalid.
Examples
RTOS::Queue.
Referenced by ~Queue(), and operator=().
elementSize()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::elementSize () const inline constexpr noexcept
Gets the element size.
Returns
Element size in bytes.
getHandle()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> Handle RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::getHandle () const inline noexcept
Gets the handle.
Returns
Queue handle.
isCreated()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::isCreated () const inline noexcept
Checks if the queue is created.
Returns
true if created, false otherwise.
isEmpty()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::isEmpty () const inline noexcept
Checks if the queue is empty.
Returns
true if empty, false otherwise.
isFull()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::isFull () const inline noexcept
Checks if the queue is full.
Returns
true if full, false otherwise.
messagesWaiting()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::messagesWaiting () const inline noexcept
Gets the number of messages waiting.
Returns
Number of messages.
Examples
RTOS::Queue.
Referenced by isEmpty(), and isFull().
messagesWaitingFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::messagesWaitingFromISR () const inline noexcept
Gets the number of messages waiting in ISR context.
Returns
Number of messages.
operator bool()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::operator bool () const inline explicit noexcept
Boolean conversion.
Returns
true if valid, false otherwise.
operator Handle()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::operator Handle () const inline noexcept
Conversion to handle.
Returns
Queue handle.
operator=() [1/2]
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> Queue & RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::operator= (const Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > &) delete
Copy assignment deleted.
operator=() [2/2]
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> Queue & RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::operator= (Queue< T_ELEMENT_TYPE, QUEUE_LENGTH > && other) inline noexcept
Move assignment operator of Queue class.
Parameters
other Queue to move from.
Returns
Reference to this queue.
overwrite()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::overwrite (const T_ELEMENT_TYPE & item) inline noexcept
Overwrites the front item.
Parameters
item Item to overwrite with.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Front item is overwritten.
overwriteFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::overwriteFromISR (const T_ELEMENT_TYPE & item) inline noexcept
Overwrites the front item in ISR context.
Parameters
item Item to overwrite with.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Front item is overwritten.
peek()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::peek (T_ELEMENT_TYPE & item, TickType_t maxTicksToWait = 0) const inline noexcept
Peeks at the front item without removing it.
Parameters
item Reference to store the peeked item.
maxTicksToWait Maximum ticks to wait.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is peeked if available.
peekFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::peekFromISR (T_ELEMENT_TYPE & item) const inline noexcept
Peeks at the front item in ISR context.
Parameters
item Reference to store the peeked item.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is peeked if available.
receive()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::receive (T_ELEMENT_TYPE & item, TickType_t maxTicksToWait = portMAX_DELAY) const inline noexcept
Receives an item from the queue.
Parameters
item Reference to store the received item.
maxTicksToWait Maximum ticks to wait.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is received if available.
Examples
RTOS::Queue.
receiveFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::receiveFromISR (T_ELEMENT_TYPE & item) const inline noexcept
Receives an item from the queue in ISR context.
Parameters
item Reference to store the received item.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is received if available.
removeFromRegistry()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> void RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::removeFromRegistry () inline noexcept
Removes the queue from the registry.
Precondition
Queue must be created.
Postcondition
Queue is unregistered.
reset()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> void RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::reset () inline noexcept
Resets the queue.
Precondition
Queue must be created.
Postcondition
Queue is empty.
send()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::send (const T_ELEMENT_TYPE & item, TickType_t maxTicksToWait = portMAX_DELAY) inline noexcept
Sends an item to the back of the queue.
Parameters
item Item to send.
maxTicksToWait Maximum ticks to wait.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is sent if space is available.
Examples
RTOS::Queue.
sendToBack()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::sendToBack (const T_ELEMENT_TYPE & item, TickType_t maxTicksToWait = portMAX_DELAY) inline noexcept
Sends an item to the back of the queue.
Parameters
item Item to send.
maxTicksToWait Maximum ticks to wait.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is sent if space is available.
sendToBackFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::sendToBackFromISR (const T_ELEMENT_TYPE & item) inline noexcept
Sends an item to the back in ISR context.
Parameters
item Item to send.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is sent if space is available.
sendToFront()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::sendToFront (const T_ELEMENT_TYPE & item, TickType_t maxTicksToWait = portMAX_DELAY) inline noexcept
Sends an item to the front of the queue.
Parameters
item Item to send.
maxTicksToWait Maximum ticks to wait.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is sent if space is available.
sendToFrontFromISR()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> bool RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::sendToFrontFromISR (const T_ELEMENT_TYPE & item) inline noexcept
Sends an item to the front in ISR context.
Parameters
item Item to send.
Returns
true if successful, false otherwise.
Precondition
Queue must be created.
Postcondition
Item is sent if space is available.
spacesAvailable()
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::spacesAvailable () const inline noexcept
Gets the number of spaces available.
Returns
Number of spaces.
Member Data Documentation
ELEMENT_SIZE
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::ELEMENT_SIZE = sizeof(T_ELEMENT_TYPE) static constexpr
Size of each element in bytes.
Referenced by create(), and elementSize().
LENGTH
template<typename T_ELEMENT_TYPE, size_t QUEUE_LENGTH = 1> size_t RTOS::Queue< T_ELEMENT_TYPE, QUEUE_LENGTH >::LENGTH = QUEUE_LENGTH static constexpr
Maximum queue length.
Referenced by capacity(), create(), and isFull().