IAR Library: Lib::BSP::W25Q128JVSIQ Class Reference
Lib::BSP::W25Q128JVSIQ Class Reference
Interface for W25Q128JVSIQ flash memory chip.
Classes
struct Config
Configuration for W25Q128JVSIQ.
struct Info
Flash memory information.
class Register
Command codes for W25Q128JVSIQ.
Public Member Functions
W25Q128JVSIQ (const Config &config)
Constructor of W25Q128JVSIQ.
~W25Q128JVSIQ ()=default
Destructor of W25Q128JVSIQ.
bool open ()
Opens and initializes the flash memory chip.
bool close ()
Closes and deinitializes the flash memory chip.
const Info & getInfo ()
Gets flash memory information.
bool read (uint32_t address, uint8_t *destination, size_t size)
Reads data from flash memory.
bool readSector (uint8_t *destination, uint32_t sectorIndex, uint32_t sectorCount)
Reads sectors from flash memory.
bool write (uint32_t address, const uint8_t *source, size_t size)
Writes data to flash memory.
bool writeSector (const uint8_t *source, uint32_t sectorIndex, uint32_t sectorCount, bool eraseBeforeWrite=true)
Writes data to sectors.
bool writePage (const uint8_t *source, uint32_t address)
Writes a page of data.
bool eraseChip ()
Erases the entire chip.
bool eraseSector (uint32_t address)
Erases a sector.
bool eraseBlock32K (uint32_t address)
Erases a 32KB block.
bool eraseBlock64K (uint32_t address)
Erases a 64KB block.
bool isPresent () const
Checks if the device is present.
Static Public Attributes
static constexpr uint32_t SPI_TIMEOUT = 1000
SPI timeout in milliseconds.
static constexpr uint32_t MAX_WRITE_TIME = 64
Max write time in milliseconds.
static constexpr uint32_t MAX_ERASE_TIME = 1000
Max erase time in milliseconds.
static constexpr uint32_t BLOCK_READ_SIZE = 32768
Max block read size in bytes.
Detailed Description
Interface for W25Q128JVSIQ flash memory chip.
Supports high-level read, write, and erase operations.
Constructor & Destructor Documentation
W25Q128JVSIQ()
Lib::BSP::W25Q128JVSIQ::W25Q128JVSIQ (const Config & config) inline explicit
Constructor of W25Q128JVSIQ.
Parameters
config SPI and NSS configuration.
~W25Q128JVSIQ()
Lib::BSP::W25Q128JVSIQ::~W25Q128JVSIQ () default
Destructor of W25Q128JVSIQ.
Member Function Documentation
close()
bool Lib::BSP::W25Q128JVSIQ::close () inline
Closes and deinitializes the flash memory chip.
Returns
true if closed successfully, false otherwise.
eraseBlock32K()
bool Lib::BSP::W25Q128JVSIQ::eraseBlock32K (uint32_t address) inline
Erases a 32KB block.
Parameters
address Block address.
Returns
true if successful, false otherwise.
eraseBlock64K()
bool Lib::BSP::W25Q128JVSIQ::eraseBlock64K (uint32_t address) inline
Erases a 64KB block.
Parameters
address Block address.
Returns
true if successful, false otherwise.
eraseChip()
bool Lib::BSP::W25Q128JVSIQ::eraseChip () inline
Erases the entire chip.
Returns
true if successful, false otherwise.
eraseSector()
bool Lib::BSP::W25Q128JVSIQ::eraseSector (uint32_t address) inline
Erases a sector.
Parameters
address Sector address.
Returns
true if successful, false otherwise.
Referenced by writeSector().
getInfo()
const Info & Lib::BSP::W25Q128JVSIQ::getInfo () inline
Gets flash memory information.
Returns
Reference to Info structure.
isPresent()
bool Lib::BSP::W25Q128JVSIQ::isPresent () const inline
Checks if the device is present.
Returns
true if present, false otherwise.
Referenced by eraseBlock32K(), eraseBlock64K(), eraseChip(), eraseSector(), open(), read(), readSector(), write(), writePage(), and writeSector().
open()
bool Lib::BSP::W25Q128JVSIQ::open () inline
Opens and initializes the flash memory chip.
Returns
true if chip is present and initialized, false otherwise.
read()
bool Lib::BSP::W25Q128JVSIQ::read (uint32_t address, uint8_t * destination, size_t size) inline
Reads data from flash memory.
Parameters
address Start address.
destination Destination buffer.
size Number of bytes to read.
Returns
true if successful, false otherwise.
Referenced by readSector().
readSector()
bool Lib::BSP::W25Q128JVSIQ::readSector (uint8_t * destination, uint32_t sectorIndex, uint32_t sectorCount) inline
Reads sectors from flash memory.
Parameters
destination Destination buffer.
sectorIndex Sector number.
sectorCount Number of sectors.
Returns
true if successful, false otherwise.
write()
bool Lib::BSP::W25Q128JVSIQ::write (uint32_t address, const uint8_t * source, size_t size) inline
Writes data to flash memory.
Parameters
address Start address.
source Source buffer.
size Number of bytes to write.
Returns
true if successful, false otherwise.
writePage()
bool Lib::BSP::W25Q128JVSIQ::writePage (const uint8_t * source, uint32_t address) inline
Writes a page of data.
Parameters
source Source buffer.
address Page address.
Returns
true if successful, false otherwise.
Referenced by writeSector().
writeSector()
bool Lib::BSP::W25Q128JVSIQ::writeSector (const uint8_t * source, uint32_t sectorIndex, uint32_t sectorCount, bool eraseBeforeWrite = true) inline
Writes data to sectors.
Parameters
source Source buffer.
sectorIndex Sector number.
sectorCount Number of sectors.
eraseBeforeWrite If true, erase sector before writing.
Returns
true if successful, false otherwise.
Member Data Documentation
BLOCK_READ_SIZE
uint32_t Lib::BSP::W25Q128JVSIQ::BLOCK_READ_SIZE = 32768 static constexpr
Max block read size in bytes.
Referenced by read().
MAX_ERASE_TIME
uint32_t Lib::BSP::W25Q128JVSIQ::MAX_ERASE_TIME = 1000 static constexpr
Max erase time in milliseconds.
MAX_WRITE_TIME
uint32_t Lib::BSP::W25Q128JVSIQ::MAX_WRITE_TIME = 64 static constexpr
Max write time in milliseconds.
SPI_TIMEOUT
uint32_t Lib::BSP::W25Q128JVSIQ::SPI_TIMEOUT = 1000 static constexpr
SPI timeout in milliseconds.
Referenced by read().