IAR Library: RTOS::Kernel Class Reference
RTOS::Kernel Class Reference
Kernel abstraction for FreeRTOS management.
Classes
class CriticalSection
RAII critical section for task context.
class CriticalSectionISR
RAII critical section for ISR context.
struct MemoryInfo
Heap memory diagnostic info.
class SchedulerSuspension
RAII scheduler suspension.
Public Types
enum class Context : uint8_t {
TASK = 0 ,
INTERRUPT = 1
}
Execution context type.
using TickType = TickCounter::TickType
using TaskCount = UBaseType_t
using InterruptMask = uint32_t
Public Member Functions
Kernel (const Kernel &)=delete
Kernel & operator= (const Kernel &)=delete
Static Public Member Functions
static TaskCount getNumberOfTasks ()
Gets number of running tasks.
static bool hasRunningTasks ()
Checks if there are running tasks.
static TaskCount getMaxTaskCount ()
Gets maximum task count.
static uint32_t msToTicks (uint32_t ms)
Converts milliseconds to ticks.
static TickType getTickCount ()
Gets current tick count.
static TickType getTickCountFromISR ()
Gets tick count from ISR.
static uint32_t getTickCountMs ()
Gets tick count in milliseconds.
static uint32_t getTickCountSeconds ()
Gets tick count in seconds.
static uint32_t getUptimeMs ()
Gets system uptime in milliseconds.
static uint32_t getUptimeSeconds ()
Gets system uptime in seconds.
static Context getCurrentContext ()
Gets current execution context.
static bool isInInterrupt ()
Checks if in interrupt context.
static bool isInTask ()
Checks if in task context.
static void yield ()
Yields processor to another task.
static void yieldFromISR (BaseType_t higherPriorityTaskWoken)
Yields from ISR.
static void delay (TickType ticks)
Delays current task by ticks.
static void delayMs (uint32_t milliseconds)
Delays current task by milliseconds.
static void delaySeconds (uint32_t seconds)
Delays current task by seconds.
static void delayUntil (TickType *previousWakeTime, TickType timeIncrement)
Delays until specified tick.
static void enterCritical ()
Enters critical section.
static InterruptMask enterCriticalFromISR ()
Enters critical section from ISR.
static void exitCritical ()
Exits critical section.
static void exitCriticalFromISR (InterruptMask interruptStatus)
Exits critical section from ISR.
static void enableInterrupts ()
Enables interrupts.
static void disableInterrupts ()
Disables interrupts.
template<typename FUNC>
static void withCriticalSection (FUNC &&func)
Executes function in critical section.
template<typename FUNC>
static void withCriticalSectionISR (FUNC &&func)
Executes function in ISR critical section.
static void startScheduler ()
Starts scheduler.
static void endScheduler ()
Ends scheduler.
static bool resumeAll ()
Resumes all tasks.
static void suspendAll ()
Suspends all tasks.
template<typename FUNC>
static void withSchedulerSuspended (FUNC &&func)
Executes function with scheduler suspended.
static bool catchUpTicks (TickType ticks)
Catches up tick count.
static const constexpr char * getVersion ()
Gets kernel version string.
static constexpr uint32_t getTickRateHz ()
Gets tick rate in Hz.
static constexpr UBaseType_t getMaxPriority ()
Gets maximum priority value.
static constexpr bool isValidPriority (UBaseType_t priority)
Checks if priority value is valid.
Detailed Description
Kernel abstraction for FreeRTOS management.
Member Enumeration Documentation
Context
enum class RTOS::Kernel::Context : uint8_t strong
Execution context type.
Enumerator
TASK
Task context.
INTERRUPT
Interrupt context.
Member Function Documentation
catchUpTicks()
bool RTOS::Kernel::catchUpTicks (TickType ticks) inline static
Catches up tick count.
Parameters
ticks Number of ticks to catch up.
Returns
true if successful, false otherwise.
delay()
void RTOS::Kernel::delay (TickType ticks) inline static
Delays current task by ticks.
Parameters
ticks Number of ticks to delay.
Referenced by delayMs().
delayMs()
void RTOS::Kernel::delayMs (uint32_t milliseconds) inline static
Delays current task by milliseconds.
Parameters
milliseconds Number of milliseconds to delay.
Referenced by RTOS::delay(), and delaySeconds().
delaySeconds()
void RTOS::Kernel::delaySeconds (uint32_t seconds) inline static
Delays current task by seconds.
Parameters
seconds Number of seconds to delay.
delayUntil()
void RTOS::Kernel::delayUntil (TickType * previousWakeTime, TickType timeIncrement) inline static
Delays until specified tick.
Parameters
previousWakeTime Pointer to previous wake time.
timeIncrement Tick increment.
disableInterrupts()
void RTOS::Kernel::disableInterrupts () inline static
Disables interrupts.
enableInterrupts()
void RTOS::Kernel::enableInterrupts () inline static
Enables interrupts.
endScheduler()
void RTOS::Kernel::endScheduler () inline static
Ends scheduler.
enterCritical()
void RTOS::Kernel::enterCritical () inline static
Enters critical section.
Referenced by RTOS::Kernel::CriticalSection::CriticalSection().
enterCriticalFromISR()
InterruptMask RTOS::Kernel::enterCriticalFromISR () inline static
Enters critical section from ISR.
Returns
Interrupt mask.
Referenced by RTOS::Kernel::CriticalSectionISR::CriticalSectionISR().
exitCritical()
void RTOS::Kernel::exitCritical () inline static
Exits critical section.
Referenced by RTOS::Kernel::CriticalSection::~CriticalSection().
exitCriticalFromISR()
void RTOS::Kernel::exitCriticalFromISR (InterruptMask interruptStatus) inline static
Exits critical section from ISR.
Parameters
interruptStatus Interrupt mask.
Referenced by RTOS::Kernel::CriticalSectionISR::~CriticalSectionISR().
getCurrentContext()
Context RTOS::Kernel::getCurrentContext () inline static
Gets current execution context.
Returns
Context value.
Referenced by isInInterrupt(), and isInTask().
getMaxPriority()
constexpr UBaseType_t RTOS::Kernel::getMaxPriority () inline static constexpr
Gets maximum priority value.
Returns
Maximum priority value.
Referenced by isValidPriority().
getMaxTaskCount()
TaskCount RTOS::Kernel::getMaxTaskCount () inline static
Gets maximum task count.
Returns
Maximum number of tasks.
getNumberOfTasks()
TaskCount RTOS::Kernel::getNumberOfTasks () inline static
Gets number of running tasks.
Returns
Number of tasks.
Referenced by getMaxTaskCount(), and hasRunningTasks().
getTickCount()
TickType RTOS::Kernel::getTickCount () inline static
Gets current tick count.
Returns
Tick count.
Referenced by getTickCountMs(), and RTOS::getTicks().
getTickCountFromISR()
TickType RTOS::Kernel::getTickCountFromISR () inline static
Gets tick count from ISR.
Returns
Tick count.
getTickCountMs()
uint32_t RTOS::Kernel::getTickCountMs () inline static
Gets tick count in milliseconds.
Returns
Tick count in ms.
Referenced by getTickCountSeconds(), and getUptimeMs().
getTickCountSeconds()
uint32_t RTOS::Kernel::getTickCountSeconds () inline static
Gets tick count in seconds.
Returns
Tick count in seconds.
getTickRateHz()
constexpr uint32_t RTOS::Kernel::getTickRateHz () inline static constexpr
Gets tick rate in Hz.
Returns
Tick rate in Hz.
getUptimeMs()
uint32_t RTOS::Kernel::getUptimeMs () inline static
Gets system uptime in milliseconds.
Returns
Uptime in ms.
Referenced by getUptimeSeconds().
getUptimeSeconds()
uint32_t RTOS::Kernel::getUptimeSeconds () inline static
Gets system uptime in seconds.
Returns
Uptime in seconds.
getVersion()
const constexpr char * RTOS::Kernel::getVersion () inline static constexpr
Gets kernel version string.
Returns
Kernel version string.
hasRunningTasks()
bool RTOS::Kernel::hasRunningTasks () inline static
Checks if there are running tasks.
Returns
true if any tasks are running, false otherwise.
isInInterrupt()
bool RTOS::Kernel::isInInterrupt () inline static
Checks if in interrupt context.
Returns
true if in interrupt, false otherwise.
isInTask()
bool RTOS::Kernel::isInTask () inline static
Checks if in task context.
Returns
true if in task, false otherwise.
isValidPriority()
constexpr bool RTOS::Kernel::isValidPriority (UBaseType_t priority) inline static constexpr
Checks if priority value is valid.
Parameters
priority Priority value.
Returns
true if valid, false otherwise.
msToTicks()
uint32_t RTOS::Kernel::msToTicks (uint32_t ms) inline static
Converts milliseconds to ticks.
Parameters
ms Milliseconds.
Returns
Tick count.
Referenced by RTOS::msToTicks().
resumeAll()
bool RTOS::Kernel::resumeAll () inline static
Resumes all tasks.
Returns
true if successful, false otherwise.
Warning
Asserts if resume fails.
Referenced by RTOS::Kernel::SchedulerSuspension::~SchedulerSuspension().
startScheduler()
void RTOS::Kernel::startScheduler () inline static
Starts scheduler.
suspendAll()
void RTOS::Kernel::suspendAll () inline static
Suspends all tasks.
Referenced by RTOS::Kernel::SchedulerSuspension::SchedulerSuspension().
withCriticalSection()
template<typename FUNC> void RTOS::Kernel::withCriticalSection (FUNC && func) inline static
Executes function in critical section.
Template Parameters
FUNC Callable type.
Parameters
func Function to execute.
Examples
RTOS::Kernel.
withCriticalSectionISR()
template<typename FUNC> void RTOS::Kernel::withCriticalSectionISR (FUNC && func) inline static
Executes function in ISR critical section.
Template Parameters
FUNC Callable type.
Parameters
func Function to execute.
withSchedulerSuspended()
template<typename FUNC> void RTOS::Kernel::withSchedulerSuspended (FUNC && func) inline static
Executes function with scheduler suspended.
Template Parameters
FUNC Callable type.
Parameters
func Function to execute.
yield()
void RTOS::Kernel::yield () inline static
Yields processor to another task.
yieldFromISR()
void RTOS::Kernel::yieldFromISR (BaseType_t higherPriorityTaskWoken) inline static
Yields from ISR.
Parameters
higherPriorityTaskWoken Indicates if a higher priority task was woken.