IAR Library: RTOS::Semaphore Class Reference
RTOS::Semaphore Class Reference
Semaphore class.
Public Types
enum class State : uint8_t {
AVAILABLE = 0 ,
TAKEN = 1 ,
INVALID = 2
}
State of the semaphore.
using Handle = SemaphoreHandle_t
using TickType = TickCounter::TickType
Public Member Functions
Semaphore ()=default
Default constructor of Semaphore class.
Semaphore (bool isAutoCreate)
Constructor of Semaphore class.
Semaphore (Semaphore &&otherSemaphore)
Move constructor of Semaphore class.
Semaphore & operator= (Semaphore &&otherSemaphore)
Move assignment operator of Semaphore class.
~Semaphore () override=default
Destructor of Semaphore class.
bool create () override
Creates the semaphore.
void destroy () override
Destroys the semaphore.
bool take (TickType waitTicks=DEFAULT_WAIT) override
Takes the semaphore.
bool takeMs (uint32_t waitMs)
Takes the semaphore with a timeout in milliseconds.
bool takeSeconds (uint32_t waitSec)
Takes the semaphore with a timeout in seconds.
bool tryTake ()
Tries to take the semaphore without waiting.
bool take (const Timeout &timeout)
Takes the semaphore with a Timeout object.
bool give () override
Gives the semaphore.
bool overwrite () override
Overwrites the semaphore (forces available state).
bool takeFromISR () override
Takes the semaphore from ISR context.
bool giveFromISR () override
Gives the semaphore from ISR context.
bool overwriteFromISR () override
Overwrites the semaphore from ISR context.
bool isCreated () const override
Checks if the semaphore is created.
bool isAvailable () const
Checks if the semaphore is available.
bool isTaken () const
Checks if the semaphore is taken.
State getState () const
Gets the current state of the semaphore.
uint32_t getCount () const
Gets the current count of the semaphore.
bool isValid () const
Checks if the semaphore is valid.
operator Handle & () override
Conversion operator to Handle reference.
operator bool () const
Conversion operator to bool.
virtual Handle getHandle () const noexcept
Returns the underlying semaphore handle.
Static Public Member Functions
static std::unique_ptr< Semaphore > make (bool isAutoCreate=true)
Creates a new Semaphore instance.
static std::unique_ptr< Semaphore > createWithState (bool isInitiallyGiven=false)
Creates a new Semaphore with initial state.
static std::unique_ptr< Semaphore > makeMutex ()
Creates a mutex semaphore.
static std::unique_ptr< Semaphore > makeSignal ()
Creates a signal semaphore.
Static Public Attributes
static constexpr TickType DEFAULT_WAIT = portMAX_DELAY
static constexpr TickType NO_WAIT = 0
Protected Member Functions
virtual bool takeNow () noexcept
Takes the semaphore without waiting.
virtual bool takeForever () noexcept
Takes the semaphore, waiting forever.
Protected Attributes
Handle handle = nullptr
Detailed Description
Semaphore class.
Provides a high-level wrapper for FreeRTOS semaphores, supporting binary, mutex, and signal semantics.
Member Typedef Documentation
Handle
using RTOS::Semaphore::Handle = SemaphoreHandle_t
Underlying FreeRTOS semaphore handle.
TickType
using RTOS::Semaphore::TickType = TickCounter::TickType
Tick type for wait durations.
Member Enumeration Documentation
State
enum class RTOS::Semaphore::State : uint8_t strong
State of the semaphore.
Represents the current state of the semaphore: available, taken, or invalid.
Enumerator
AVAILABLE
Semaphore is available.
TAKEN
Semaphore is taken.
INVALID
Semaphore is invalid or not created.
Constructor & Destructor Documentation
Semaphore() [1/3]
RTOS::Semaphore::Semaphore () default
Default constructor of Semaphore class.
Referenced by Semaphore(), and operator=().
Semaphore() [2/3]
RTOS::Semaphore::Semaphore (bool isAutoCreate) inline explicit
Constructor of Semaphore class.
Parameters
isAutoCreate If true, the semaphore is created automatically.
Semaphore() [3/3]
RTOS::Semaphore::Semaphore (Semaphore && otherSemaphore) inline
Move constructor of Semaphore class.
Parameters
otherSemaphore Semaphore to move from.
~Semaphore()
RTOS::Semaphore::~Semaphore () override default
Destructor of Semaphore class.
Member Function Documentation
create()
bool RTOS::Semaphore::create () inline override virtual
Creates the semaphore.
Returns
true if creation was successful, false otherwise.
Implements RTOS::SemaphoreBase.
Referenced by Lib::Digi::API::ApplicationBase::start().
createWithState()
std::unique_ptr< Semaphore > RTOS::Semaphore::createWithState (bool isInitiallyGiven = false) inline static
Creates a new Semaphore with initial state.
Parameters
isInitiallyGiven If true, the semaphore is initially given.
Returns
Unique pointer to the created Semaphore.
Referenced by makeMutex(), and makeSignal().
destroy()
void RTOS::Semaphore::destroy () inline override virtual
Destroys the semaphore.
Reimplemented from RTOS::SemaphoreBase.
getCount()
uint32_t RTOS::Semaphore::getCount () const inline
Gets the current count of the semaphore.
Returns
Current count value.
getHandle()
virtual Handle RTOS::SemaphoreBase::getHandle () const inline virtual noexcept inherited
Returns the underlying semaphore handle.
Returns
Semaphore handle.
getState()
State RTOS::Semaphore::getState () const inline
Gets the current state of the semaphore.
Returns
State of the semaphore.
give()
bool RTOS::Semaphore::give () inline override virtual
Gives the semaphore.
Returns
true if the semaphore was given, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
Referenced by Lib::Digi::API::ApplicationBase::start().
giveFromISR()
bool RTOS::Semaphore::giveFromISR () inline override virtual
Gives the semaphore from ISR context.
Returns
true if the semaphore was given, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
isAvailable()
bool RTOS::Semaphore::isAvailable () const inline
Checks if the semaphore is available.
Returns
true if the semaphore is available, false otherwise.
isCreated()
bool RTOS::Semaphore::isCreated () const inline override virtual
Checks if the semaphore is created.
Returns
true if the semaphore is created, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
Referenced by isValid(), and operator bool().
isTaken()
bool RTOS::Semaphore::isTaken () const inline
Checks if the semaphore is taken.
Returns
true if the semaphore is taken, false otherwise.
isValid()
bool RTOS::Semaphore::isValid () const inline
Checks if the semaphore is valid.
Returns
true if the semaphore is valid, false otherwise.
make()
std::unique_ptr< Semaphore > RTOS::Semaphore::make (bool isAutoCreate = true) inline static
Creates a new Semaphore instance.
Parameters
isAutoCreate If true, the semaphore is created automatically.
Returns
Unique pointer to the created Semaphore, or nullptr if creation failed.
Examples
RTOS::Semaphore.
Referenced by createWithState().
makeMutex()
std::unique_ptr< Semaphore > RTOS::Semaphore::makeMutex () inline static
Creates a mutex semaphore.
Returns
Unique pointer to the created mutex Semaphore.
makeSignal()
std::unique_ptr< Semaphore > RTOS::Semaphore::makeSignal () inline static
Creates a signal semaphore.
Returns
Unique pointer to the created signal Semaphore.
operator bool()
RTOS::Semaphore::operator bool () const inline explicit
Conversion operator to bool.
Returns
true if the semaphore is created, false otherwise.
operator Handle &()
RTOS::Semaphore::operator Handle & () inline override virtual
Conversion operator to Handle reference.
Returns
Reference to the underlying handle.
Reimplemented from RTOS::SemaphoreBase.
operator=()
Semaphore & RTOS::Semaphore::operator= (Semaphore && otherSemaphore) inline
Move assignment operator of Semaphore class.
Parameters
otherSemaphore Semaphore to move from.
Returns
Reference to this object.
overwrite()
bool RTOS::Semaphore::overwrite () inline override virtual
Overwrites the semaphore (forces available state).
Returns
true if the semaphore was overwritten, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
overwriteFromISR()
bool RTOS::Semaphore::overwriteFromISR () inline override virtual
Overwrites the semaphore from ISR context.
Returns
true if the semaphore was overwritten, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
take() [1/2]
bool RTOS::Semaphore::take (const Timeout & timeout) inline
Takes the semaphore with a Timeout object.
Parameters
timeout Timeout object.
Returns
true if the semaphore was taken, false otherwise.
Referenced by take().
take() [2/2]
bool RTOS::Semaphore::take (TickType waitTicks = DEFAULT_WAIT) inline override virtual
Takes the semaphore.
Parameters
waitTicks Number of ticks to wait.
Returns
true if the semaphore was taken, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
Referenced by takeMs(), and tryTake().
takeForever()
virtual bool RTOS::SemaphoreBase::takeForever () inline protected virtual noexcept inherited
Takes the semaphore, waiting forever.
Returns
true if taken, false otherwise.
takeFromISR()
bool RTOS::Semaphore::takeFromISR () inline override virtual
Takes the semaphore from ISR context.
Returns
true if the semaphore was taken, false otherwise.
Reimplemented from RTOS::SemaphoreBase.
takeMs()
bool RTOS::Semaphore::takeMs (uint32_t waitMs) inline
Takes the semaphore with a timeout in milliseconds.
Parameters
waitMs Timeout in milliseconds.
Returns
true if the semaphore was taken, false otherwise.
Referenced by takeSeconds().
takeNow()
virtual bool RTOS::SemaphoreBase::takeNow () inline protected virtual noexcept inherited
Takes the semaphore without waiting.
Returns
true if taken, false otherwise.
takeSeconds()
bool RTOS::Semaphore::takeSeconds (uint32_t waitSec) inline
Takes the semaphore with a timeout in seconds.
Parameters
waitSec Timeout in seconds.
Returns
true if the semaphore was taken, false otherwise.
tryTake()
bool RTOS::Semaphore::tryTake () inline
Tries to take the semaphore without waiting.
Returns
true if the semaphore was taken, false otherwise.
Member Data Documentation
DEFAULT_WAIT
TickType RTOS::Semaphore::DEFAULT_WAIT = portMAX_DELAY static constexpr
Default wait duration (infinite).
Referenced by take(), and take().
handle
Handle RTOS::SemaphoreBase::handle = nullptr protected inherited
Underlying FreeRTOS semaphore handle.
Referenced by ~SemaphoreBase(), RTOS::Semaphore::create(), RTOS::SemaphoreCounting::create(), destroy(), RTOS::Semaphore::getCount(), RTOS::SemaphoreCounting::getCount(), getHandle(), RTOS::Semaphore::getState(), give(), giveFromISR(), RTOS::Semaphore::isAvailable(), isCreated(), RTOS::Semaphore::isTaken(), operator Handle &(), operator=(), overwrite(), overwriteFromISR(), take(), and takeFromISR().
NO_WAIT
TickType RTOS::Semaphore::NO_WAIT = 0 static constexpr
No wait duration (immediate return).
Referenced by tryTake().