IAR Library: Lib::BSP::Ethercat::PDI::LAN9252::Base Class Reference
Lib::BSP::Ethercat::PDI::LAN9252::Base Class Reference
Base class for LAN9252 EtherCAT slave controller.
Classes
struct Config
Configuration for LAN9252 Base.
Public Types
enum class State : uint8_t {
NO_INIT ,
READY ,
DISABLE ,
ERROR
}
LAN9252 chip state.
Public Member Functions
Base (const Config &config)
Constructor of Base class.
~Base ()=default
Destructor of Base class.
bool init ()
Initializes LAN9252 chip.
bool resetChip ()
Resets LAN9252 chip.
void resetPin (bool value)
Sets reset pin state.
bool verifyChipId ()
Verifies LAN9252 chip ID.
uint32_t readU32 (uint16_t address)
Reads 32-bit value from address.
void writeU32 (uint16_t address, uint32_t value)
Writes 32-bit value to address.
uint16_t readAlEventReg ()
Reads AL Event register.
void readPDIRegister (uint8_t *buffer, uint16_t address, uint16_t length)
Reads PDI register.
void readReg (uint16_t address, void *buffer, size_t length)
Reads register.
void writeReg (uint16_t address, const void *buffer, size_t length)
Writes register.
void readCSR (uint16_t address, void *buffer, uint8_t length)
Reads CSR register.
void writeCSR (uint16_t address, const uint8_t *buffer, uint8_t length)
Writes CSR register.
void readPRAM (uint16_t address, uint8_t *buffer, uint16_t length)
Reads from PRAM.
void writePRAM (const uint8_t *buffer, uint16_t address, uint16_t length)
Writes to PRAM.
uint16_t readDLStatus ()
Reads DL Status register.
uint32_t readBurstMode ()
Reads data in burst mode.
Detailed Description
Base class for LAN9252 EtherCAT slave controller.
Encapsulates initialization, reset, and register access for the LAN9252 EtherCAT slave controller chip.
Member Enumeration Documentation
State
enum class Lib::BSP::Ethercat::PDI::LAN9252::Base::State : uint8_t strong
LAN9252 chip state.
Enumerates the possible states of the LAN9252 chip.
Enumerator
NO_INIT
Not initialized.
READY
Ready for operation.
DISABLE
Disabled.
ERROR
Error state.
Constructor & Destructor Documentation
Base()
Lib::BSP::Ethercat::PDI::LAN9252::Base::Base (const Config & config) inline explicit
Constructor of Base class.
Parameters
config Configuration with SPI and GPIO handles.
~Base()
Lib::BSP::Ethercat::PDI::LAN9252::Base::~Base () default
Destructor of Base class.
Member Function Documentation
init()
bool Lib::BSP::Ethercat::PDI::LAN9252::Base::init () inline
Initializes LAN9252 chip.
Returns
true if successful, false otherwise.
readAlEventReg()
uint16_t Lib::BSP::Ethercat::PDI::LAN9252::Base::readAlEventReg () inline
Reads AL Event register.
Returns
AL Event register value.
readBurstMode()
uint32_t Lib::BSP::Ethercat::PDI::LAN9252::Base::readBurstMode () inline
Reads data in burst mode.
Returns
32-bit value read.
Referenced by readPRAM().
readCSR()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::readCSR (uint16_t address, void * buffer, uint8_t length) inline
Reads CSR register.
Parameters
address Register address.
buffer Destination buffer.
length Number of bytes to read.
Referenced by readAlEventReg(), and readReg().
readDLStatus()
uint16_t Lib::BSP::Ethercat::PDI::LAN9252::Base::readDLStatus () inline
Reads DL Status register.
Returns
DL Status register value.
readPDIRegister()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::readPDIRegister (uint8_t * buffer, uint16_t address, uint16_t length) inline
Reads PDI register.
Parameters
buffer Destination buffer.
address Register address.
length Number of bytes to read.
readPRAM()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::readPRAM (uint16_t address, uint8_t * buffer, uint16_t length) inline
Reads from PRAM.
Parameters
address Register address.
buffer Destination buffer.
length Number of bytes to read.
Referenced by readPDIRegister(), and readReg().
readReg()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::readReg (uint16_t address, void * buffer, size_t length) inline
Reads register.
Parameters
address Register address.
buffer Destination buffer.
length Number of bytes to read.
Referenced by readDLStatus().
readU32()
uint32_t Lib::BSP::Ethercat::PDI::LAN9252::Base::readU32 (uint16_t address) inline
Reads 32-bit value from address.
Parameters
address Register address.
Returns
32-bit value.
Referenced by readCSR(), readPRAM(), verifyChipId(), writeCSR(), and writePRAM().
resetChip()
bool Lib::BSP::Ethercat::PDI::LAN9252::Base::resetChip () inline
Resets LAN9252 chip.
Returns
true if reset successful, false otherwise.
Referenced by init().
resetPin()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::resetPin (bool value) inline
Sets reset pin state.
Parameters
value true for high, false for low.
verifyChipId()
bool Lib::BSP::Ethercat::PDI::LAN9252::Base::verifyChipId () inline
Verifies LAN9252 chip ID.
Returns
true if chip ID is valid, false otherwise.
Referenced by resetChip().
writeCSR()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::writeCSR (uint16_t address, const uint8_t * buffer, uint8_t length) inline
Writes CSR register.
Parameters
address Register address.
buffer Source buffer.
length Number of bytes to write.
Referenced by writeReg().
writePRAM()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::writePRAM (const uint8_t * buffer, uint16_t address, uint16_t length) inline
Writes to PRAM.
Parameters
buffer Source buffer.
address Register address.
length Number of bytes to write.
Referenced by writeReg().
writeReg()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::writeReg (uint16_t address, const void * buffer, size_t length) inline
Writes register.
Parameters
address Register address.
buffer Source buffer.
length Number of bytes to write.
writeU32()
void Lib::BSP::Ethercat::PDI::LAN9252::Base::writeU32 (uint16_t address, uint32_t value) inline
Writes 32-bit value to address.
Parameters
address Register address.
value Value to write.
Referenced by readCSR(), readPRAM(), writeCSR(), and writePRAM().