IAR Library: Lib::HAL::Timer< T_MODE > Class Template Reference
Lib::HAL::Timer< T_MODE > Class Template Reference
Timer class template for TIM peripheral management.
Public Member Functions
Timer ()=default
Constructor of Timer class.
virtual ~Timer ()=default
Destructor of Timer class.
Timer (const Timer &)=delete
Deleted copy constructor of Timer class.
Timer & operator= (const Timer &)=delete
Deleted copy assignment operator of Timer class.
Timer (Timer &&)=delete
Deleted move constructor of Timer class.
Timer & operator= (Timer &&)=delete
Deleted move assignment operator of Timer class.
void setHandle (const Handle &handle)
Set TIM handle and channel.
Handle * getHandle ()
Get pointer to TIM handle wrapper.
constexpr Mode getMode () const
Get timer mode.
bool isValid () const
Check if timer handle is valid.
Detailed Description
template<Mode T_MODE>
class Lib::HAL::Timer< T_MODE >
Timer class template for TIM peripheral management.
Defines an interface for TIM peripheral management, parameterized by Mode (e.g., ENCODER). Provides RAII ownership of TIM handle and channel, supporting future extension for callback/event integration. The class is designed for embedded applications, ensuring type safety, maintainability, and compatibility with STM32 HAL and project documentation guidelines.
Template Parameters
T_MODE Mode of the timer.
Constructor & Destructor Documentation
Timer() [1/3]
template<Mode T_MODE> Lib::HAL::Timer< T_MODE >::Timer () default
Constructor of Timer class.
Referenced by Timer(), Timer(), operator=(), and operator=().
~Timer()
template<Mode T_MODE> virtual Lib::HAL::Timer< T_MODE >::~Timer () virtual default
Destructor of Timer class.
Timer() [2/3]
template<Mode T_MODE> Lib::HAL::Timer< T_MODE >::Timer (const Timer< T_MODE > &) delete
Deleted copy constructor of Timer class.
Timer() [3/3]
template<Mode T_MODE> Lib::HAL::Timer< T_MODE >::Timer (Timer< T_MODE > &&) delete
Deleted move constructor of Timer class.
Member Function Documentation
getHandle()
template<Mode T_MODE> Handle * Lib::HAL::Timer< T_MODE >::getHandle () inline
Get pointer to TIM handle wrapper.
Returns
Pointer to Handle if set, nullptr otherwise.
Referenced by Lib::HAL::Timer< Mode::ENCODER >::close(), and Lib::HAL::Timer< Mode::ENCODER >::open().
getMode()
template<Mode T_MODE> Mode Lib::HAL::Timer< T_MODE >::getMode () const inline constexpr
Get timer mode.
Returns
Mode of timer.
isValid()
template<Mode T_MODE> bool Lib::HAL::Timer< T_MODE >::isValid () const inline
Check if timer handle is valid.
Returns
true if handle is valid, false otherwise.
operator=() [1/2]
template<Mode T_MODE> Timer & Lib::HAL::Timer< T_MODE >::operator= (const Timer< T_MODE > &) delete
Deleted copy assignment operator of Timer class.
operator=() [2/2]
template<Mode T_MODE> Timer & Lib::HAL::Timer< T_MODE >::operator= (Timer< T_MODE > &&) delete
Deleted move assignment operator of Timer class.
setHandle()
template<Mode T_MODE> void Lib::HAL::Timer< T_MODE >::setHandle (const Handle & handle) inline
Set TIM handle and channel.
Parameters
handle TIM handle wrapper.