IAR Library: Lib::System::VersionBase Class Reference
Lib::System::VersionBase Class Reference
Base class for handling version information.
Protected Member Functions
VersionBase (const std::string &versionString, uint32_t subVersion=0)
Constructor of the VersionBase class.
virtual ~VersionBase ()=default
Virtual destructor of the VersionBase class.
virtual uint32_t getValue () const
Retrieves the version value.
virtual uint32_t getSubVersion () const
Retrieves the subversion number.
virtual std::string toString () const
Converts version information to a string.
virtual operator uint32_t () const
Conversion to uint32_t.
virtual operator std::string () const
Conversion to std::string.
Static Protected Member Functions
static uint32_t stringToU32 (const std::string &versionString)
Converts a version string to a 32-bit unsigned integer.
Detailed Description
Base class for handling version information.
Stores, converts, and retrieves version and subversion information. Provides conversion between string and uint32_t formats, supporting embedded version management.
Constructor & Destructor Documentation
VersionBase()
Lib::System::VersionBase::VersionBase (const std::string & versionString, uint32_t subVersion = 0) inline protected
Constructor of the VersionBase class.
Parameters
versionString Version string to convert to a 32-bit unsigned integer.
subVersion Optional subversion number, default is 0.
Precondition
versionString must be in the format "X.Y" where X and Y are integers in [0,255].
Referenced by Lib::System::FirmwareVersion::FirmwareVersion(), and Lib::System::HardwareVersion::HardwareVersion().
~VersionBase()
virtual Lib::System::VersionBase::~VersionBase () protected virtual default
Virtual destructor of the VersionBase class.
Member Function Documentation
getSubVersion()
virtual uint32_t Lib::System::VersionBase::getSubVersion () const inline protected virtual
Retrieves the subversion number.
Returns
The subversion number as a 32-bit unsigned integer.
Reimplemented in Lib::System::FirmwareVersion, and Lib::System::HardwareVersion.
Referenced by Lib::System::FirmwareVersion::getSubVersion(), operator uint32_t(), and toString().
getValue()
virtual uint32_t Lib::System::VersionBase::getValue () const inline protected virtual
Retrieves the version value.
Returns
The version value as a 32-bit unsigned integer.
Reimplemented in Lib::System::FirmwareVersion, and Lib::System::HardwareVersion.
Referenced by Lib::System::FirmwareVersion::getValue(), Lib::System::HardwareVersion::getValue(), and operator uint32_t().
operator std::string()
virtual Lib::System::VersionBase::operator std::string () const inline protected virtual
Conversion to std::string.
Returns
String representation of the version.
Reimplemented in Lib::System::FirmwareVersion, and Lib::System::HardwareVersion.
operator uint32_t()
virtual Lib::System::VersionBase::operator uint32_t () const inline protected virtual
Conversion to uint32_t.
Returns
32-bit unsigned integer representation of the version.
Reimplemented in Lib::System::FirmwareVersion, and Lib::System::HardwareVersion.
stringToU32()
uint32_t Lib::System::VersionBase::stringToU32 (const std::string & versionString) inline static protected
Converts a version string to a 32-bit unsigned integer.
Parameters
versionString Version string in the format "X.Y".
Returns
32-bit unsigned integer representing the version.
Precondition
versionString must be in the format "X.Y" where X and Y are integers in [0,255].
Exceptions
std::invalid_argument if the input format is invalid or out of range.
Referenced by VersionBase().
toString()
virtual std::string Lib::System::VersionBase::toString () const inline protected virtual
Converts version information to a string.
Returns
String in the format "major.minor.subversion".
Reimplemented in Lib::System::FirmwareVersion, and Lib::System::HardwareVersion.
Referenced by operator std::string(), Lib::System::FirmwareVersion::toString(), and Lib::System::HardwareVersion::toString().