IAR Library: Lib::Ethernet::Port Class Reference
Lib::Ethernet::Port Class Reference
Represents an Ethernet port.
Public Member Functions
Port ()=default
Constructor of the Port class.
Port (uint16_t value)
Constructor of the Port class.
uint16_t & get ()
Gets the port value.
const uint16_t & get () const
Gets the port value (const).
void set (uint16_t value)
Sets the port value.
std::string toString () const
Converts the port to a string.
bool fromString (const std::string &str)
Parses the port from a string.
operator uint16_t () const
Conversion operator to uint16_t.
Port & operator= (uint16_t value)
Assignment operator from uint16_t.
Static Public Member Functions
static std::string toString (uint16_t value)
Converts a port value to a string.
static bool fromString (const std::string &str, uint16_t &result)
Parses a port value from a string.
static bool validateString (const std::string &str)
Validates a port string.
Detailed Description
Represents an Ethernet port.
Provides methods for construction, conversion, and validation of port numbers. Supports conversion to and from string representations, validation, and access methods for embedded networking applications.
Constructor & Destructor Documentation
Port() [1/2]
Lib::Ethernet::Port::Port () default
Constructor of the Port class.
Referenced by operator=().
Port() [2/2]
Lib::Ethernet::Port::Port (uint16_t value) inline explicit
Constructor of the Port class.
Parameters
value Port number.
Member Function Documentation
fromString() [1/2]
bool Lib::Ethernet::Port::fromString (const std::string & str) inline
Parses the port from a string.
Parameters
str String to parse.
Returns
true if parsing was successful, false otherwise.
Referenced by fromString().
fromString() [2/2]
bool Lib::Ethernet::Port::fromString (const std::string & str, uint16_t & result) inline static
Parses a port value from a string.
Parameters
str String to parse.
[out] result Output port value.
Returns
true if parsing was successful, false otherwise.
Precondition
str must be a valid decimal string representing a port number in [0, 65535].
get() [1/2]
uint16_t & Lib::Ethernet::Port::get () inline
Gets the port value.
Returns
Reference to the port value.
Referenced by Lib::Ethernet::Wiznet::Socket::connect(), Lib::Ethernet::Wiznet::Socket::open(), Lib::Ethernet::Wiznet::Socket::receiveFrom(), and Lib::Ethernet::Wiznet::Socket::sendTo().
get() [2/2]
const uint16_t & Lib::Ethernet::Port::get () const inline
Gets the port value (const).
Returns
Const reference to the port value.
operator uint16_t()
Lib::Ethernet::Port::operator uint16_t () const inline
Conversion operator to uint16_t.
Returns
Port value.
operator=()
Port & Lib::Ethernet::Port::operator= (uint16_t value) inline
Assignment operator from uint16_t.
Parameters
value Port number.
Returns
Reference to this Port.
set()
void Lib::Ethernet::Port::set (uint16_t value) inline
Sets the port value.
Parameters
value Port number.
Referenced by operator=().
toString() [1/2]
std::string Lib::Ethernet::Port::toString () const inline
Converts the port to a string.
Returns
String representation of the port.
Referenced by toString().
toString() [2/2]
std::string Lib::Ethernet::Port::toString (uint16_t value) inline static
Converts a port value to a string.
Parameters
value Port number.
Returns
String representation.
validateString()
bool Lib::Ethernet::Port::validateString (const std::string & str) inline static
Validates a port string.
Parameters
str String to validate.
Returns
true if the string is a valid port number, false otherwise.
Referenced by fromString().