IAR Library: Lib::System::Version::Base Class Reference
Lib::System::Version::Base Class Reference
Base class for version handling.
Public Member Functions
Base (const std::string &versionString)
Constructor of Base class.
operator uint32_t () const
Conversion operator to uint32_t.
operator std::string () const
Conversion operator to std::string.
Static Public Member Functions
static Lib::Helper::DateTime stringToDateTime (const char *timeString, const char *dateString)
Converts time and date strings to DateTime.
static uint32_t stringToU32 (const std::string &versionString)
Converts version string to uint32_t.
Protected Member Functions
virtual uint8_t subVersion () const
Retrieves the subversion number.
Detailed Description
Base class for version handling.
Provides conversion between version string and integer formats, and parsing of build date/time for embedded systems. Ensures type safety and input validation.
Constructor & Destructor Documentation
Base()
Lib::System::Version::Base::Base (const std::string & versionString) inline explicit
Constructor of Base class.
Parameters
versionString Version string.
Referenced by Lib::System::Version::Firmware::Firmware(), and Lib::System::Version::Hardware::Hardware().
Member Function Documentation
operator std::string()
Lib::System::Version::Base::operator std::string () const inline
Conversion operator to std::string.
Returns
String representation of the version.
operator uint32_t()
Lib::System::Version::Base::operator uint32_t () const inline
Conversion operator to uint32_t.
Returns
32-bit unsigned integer representation of the version.
stringToDateTime()
Lib::Helper::DateTime Lib::System::Version::Base::stringToDateTime (const char * timeString, const char * dateString) inline static
Converts time and date strings to DateTime.
Parameters
timeString Time string (e.g., TIME).
dateString Date string (e.g., DATE).
Returns
DateTime object representing the parsed time and date.
Referenced by Lib::System::Version::Firmware::operator std::string().
stringToU32()
uint32_t Lib::System::Version::Base::stringToU32 (const std::string & versionString) inline static
Converts version string to uint32_t.
Parameters
versionString Version string in the format "X.Y".
Returns
32-bit unsigned integer representing the version.
Referenced by Base().
subVersion()
virtual uint8_t Lib::System::Version::Base::subVersion () const inline protected virtual
Retrieves the subversion number.
Returns
Subversion number (default 0).
Reimplemented in Lib::System::Version::Firmware.
Referenced by operator std::string(), operator uint32_t(), and Lib::System::Version::Firmware::subVersion().