IAR Library: Lib::Ethernet::Wiznet::Socket Class Reference
Lib::Ethernet::Wiznet::Socket Class Reference
Socket wrapper for Wiznet W5500 TCP/UDP communication.
Classes
class Error
Socket error code wrapper.
class Flag
Socket flags for protocol configuration.
class Protocol
Socket protocol type wrapper.
Public Types
using SocketOption = ::sockopt_type
using SocketControl = ::ctlsock_type
Public Member Functions
virtual Error open (uint8_t protocol, Port port, Flag flags)
Open socket with protocol, port, and flags.
virtual Error close ()
Close the socket.
virtual Error listen ()
Listen for incoming connections.
virtual Error connect (const Node &remoteNode)
Connect to remote node.
virtual Error disconnect ()
Disconnect the socket.
virtual bool isClosed () const
Check if socket is closed.
virtual bool isConnect () const
Check if socket is connected.
virtual Error receive (DataHandle<> &buffer, size_t &receivedLength)
Receive incoming message.
size_t getReceivedSize () const
Get received size from hardware.
virtual Error send (const DataHandle<> &buffer, size_t &sentLength)
Send data to connected peer.
virtual size_t receiveFrom (DataHandle<> &buffer, Node &remoteNode)
Receive data from remote node.
virtual size_t sendTo (const DataHandle<> &buffer, const Node &remoteNode)
Send data to remote node.
Friends
class Sockets
Detailed Description
Socket wrapper for Wiznet W5500 TCP/UDP communication.
Provides protocol, flag, and error wrappers, and socket operations for embedded Ethernet.
Member Function Documentation
close()
virtual Error Lib::Ethernet::Wiznet::Socket::close () inline virtual
Close the socket.
Returns
Error code.
Postcondition
Socket closed.
Referenced by close().
connect()
virtual Error Lib::Ethernet::Wiznet::Socket::connect (const Node & remoteNode) inline virtual
Connect to remote node.
Parameters
remoteNode Remote node.
Returns
Error code.
Precondition
remoteNode must be valid.
Postcondition
Socket connected if successful.
Referenced by connect().
disconnect()
virtual Error Lib::Ethernet::Wiznet::Socket::disconnect () inline virtual
Disconnect the socket.
Returns
Error code.
Postcondition
Socket disconnected.
Referenced by disconnect().
getReceivedSize()
size_t Lib::Ethernet::Wiznet::Socket::getReceivedSize () const inline
Get received size from hardware.
Returns
Number of bytes available to read.
isClosed()
virtual bool Lib::Ethernet::Wiznet::Socket::isClosed () const inline virtual
Check if socket is closed.
Returns
true if closed, false otherwise.
isConnect()
virtual bool Lib::Ethernet::Wiznet::Socket::isConnect () const inline virtual
Check if socket is connected.
Returns
true if connected, false otherwise.
listen()
virtual Error Lib::Ethernet::Wiznet::Socket::listen () inline virtual
Listen for incoming connections.
Returns
Error code.
Postcondition
Socket listening.
Referenced by listen().
open()
virtual Error Lib::Ethernet::Wiznet::Socket::open (uint8_t protocol, Port port, Flag flags) inline virtual
Open socket with protocol, port, and flags.
Parameters
protocol Protocol type.
port Port number.
flags Socket flags.
Returns
Error code.
Precondition
protocol, port, and flags must be valid.
Postcondition
Socket opened if successful.
receive()
virtual Error Lib::Ethernet::Wiznet::Socket::receive (DataHandle<> & buffer, size_t & receivedLength) inline virtual
Receive incoming message.
Parameters
buffer Data handle for received data.
[out] receivedLength Length of received data.
Returns
Error code.
Precondition
buffer must be valid.
Postcondition
Data received if successful.
receiveFrom()
virtual size_t Lib::Ethernet::Wiznet::Socket::receiveFrom (DataHandle<> & buffer, Node & remoteNode) inline virtual
Receive data from remote node.
Parameters
buffer Data handle for received data.
remoteNode Node to receive from.
Returns
Number of bytes received.
Precondition
buffer and remoteNode must be valid.
Postcondition
Data received if successful.
send()
virtual Error Lib::Ethernet::Wiznet::Socket::send (const DataHandle<> & buffer, size_t & sentLength) inline virtual
Send data to connected peer.
Parameters
buffer Data handle to send.
[out] sentLength Number of bytes sent.
Returns
Error code.
Precondition
buffer must be valid.
Postcondition
Data sent if successful.
Referenced by send().
sendTo()
virtual size_t Lib::Ethernet::Wiznet::Socket::sendTo (const DataHandle<> & buffer, const Node & remoteNode) inline virtual
Send data to remote node.
Parameters
buffer Data handle to send.
remoteNode Node to send to.
Returns
Number of bytes sent.
Precondition
buffer and remoteNode must be valid.
Postcondition
Data sent if successful.