IAR Library: Lib::System::ParametersBase Class Reference
Lib::System::ParametersBase Class Reference abstract
ParametersBase manages system parameters with storage and validation.
Classes
class StorageBase
StorageBase is an abstract base for storage operations.
Public Member Functions
bool setup ()
Sets up parameters by reading from storage and validating integrity.
bool write ()
Writes current parameters to storage.
bool isValid () const
Checks if stored parameters are valid.
Protected Member Functions
ParametersBase (StorageBase *storage, void *buffer, size_t size)
Constructor of ParametersBase class.
virtual ~ParametersBase ()=default
Destructor of ParametersBase class.
virtual void restoreByDefault ()=0
Restores parameters to default values.
Static Protected Attributes
static constexpr size_t CRC_SIZE = sizeof(uint16_t)
Detailed Description
ParametersBase manages system parameters with storage and validation.
Provides CRC integrity checks, default restoration, and flexible storage backend support.
Constructor & Destructor Documentation
ParametersBase()
Lib::System::ParametersBase::ParametersBase (StorageBase * storage, void * buffer, size_t size) inline explicit protected
Constructor of ParametersBase class.
Parameters
storage Storage implementation.
buffer Data buffer.
size Size of the data buffer.
~ParametersBase()
virtual Lib::System::ParametersBase::~ParametersBase () protected virtual default
Destructor of ParametersBase class.
Member Function Documentation
isValid()
bool Lib::System::ParametersBase::isValid () const inline
Checks if stored parameters are valid.
Returns
true if valid, false otherwise.
Referenced by setup().
restoreByDefault()
virtual void Lib::System::ParametersBase::restoreByDefault () protected pure virtual
Restores parameters to default values.
Referenced by setup().
setup()
bool Lib::System::ParametersBase::setup () inline
Sets up parameters by reading from storage and validating integrity.
Returns
true if successful, false otherwise.
write()
bool Lib::System::ParametersBase::write () inline
Writes current parameters to storage.
Returns
true if successful, false otherwise.
Referenced by setup().
Member Data Documentation
CRC_SIZE
size_t Lib::System::ParametersBase::CRC_SIZE = sizeof(uint16_t) static constexpr protected
CRC16 size in bytes.
Referenced by ParametersBase(), setup(), and write().