IAR Library: Lib::Ethernet::UserProtocol Class Reference
Lib::Ethernet::UserProtocol Class Reference
Ethernet UserProtocol class.
Classes
struct MessageHeader
User protocol Message Header.
Public Types
enum class Command : uint8_t {
ECHO ,
INPUTS ,
OUTPUTS
}
User Protocol commands.
enum class Error : uint8_t {
OK ,
COMMAND_NOT_SUPPORT ,
EMPTY_MESSAGE ,
INVALID_PAYLOAD_LENGTH ,
INVALID_START_DELIMITER
}
User Protocol Errors.
Public Member Functions
UserProtocol ()=default
Constructor of the UserProtocol class.
virtual ~UserProtocol ()=default
Destructor of the UserProtocol class.
Error parse (const uint8_t *data, size_t size, Command &command, uint8_t &option)
Parses the incoming message.
std::vector< uint8_t > build (Command command, uint8_t option, uint16_t id, const std::vector< uint8_t > *payload=nullptr)
Builds the outgoing message.
uint32_t getLastSentTimeStamp () const
Gets the last sent time stamp.
virtual void handleIncomingMessageHeader (const MessageHeader &header)
Handles incoming message header.
virtual void echoCallback ()
Echo callback.
virtual void updateNodeActivityCallback (size_t nodesCount)
Update node activity callback.
virtual void inputsUpdateCallback (uint8_t boardIndex, const uint64_t &value)
Inputs update callback.
virtual void handleOututsUpdate (uint8_t boardIndex, const uint64_t &value)
Outputs update callback.
Detailed Description
Ethernet UserProtocol class.
Provides methods for building and parsing Ethernet user protocol messages, handling commands, options, and payloads. Supports callback mechanisms for message processing and activity updates.
Member Enumeration Documentation
Command
enum class Lib::Ethernet::UserProtocol::Command : uint8_t strong
User Protocol commands.
Enumerates supported user protocol commands.
Enumerator
ECHO
Echo command (client/server function).
INPUTS
Inputs update (server function).
OUTPUTS
Outputs update (server function).
Error
enum class Lib::Ethernet::UserProtocol::Error : uint8_t strong
User Protocol Errors.
Enumerates possible errors during message parsing and processing.
Enumerator
OK
No error.
COMMAND_NOT_SUPPORT
Command not supported.
EMPTY_MESSAGE
Message is empty or parameters are invalid.
INVALID_PAYLOAD_LENGTH
Payload length is invalid.
INVALID_START_DELIMITER
Start delimiter is invalid.
Constructor & Destructor Documentation
UserProtocol()
Lib::Ethernet::UserProtocol::UserProtocol () default
Constructor of the UserProtocol class.
~UserProtocol()
virtual Lib::Ethernet::UserProtocol::~UserProtocol () virtual default
Destructor of the UserProtocol class.
Member Function Documentation
build()
std::vector< uint8_t > Lib::Ethernet::UserProtocol::build (Command command, uint8_t option, uint16_t id, const std::vector< uint8_t > * payload = nullptr) inline
Builds the outgoing message.
Parameters
command Command to send.
option Message option.
id Frame ID.
payload Pointer to payload data (optional).
Returns
Vector containing the constructed message bytes.
Precondition
command must be a valid Command.
option must be a valid option value.
id must be a valid frame ID.
Postcondition
Returns a vector containing the message header and payload.
echoCallback()
virtual void Lib::Ethernet::UserProtocol::echoCallback () inline virtual
Echo callback.
Referenced by parse().
getLastSentTimeStamp()
uint32_t Lib::Ethernet::UserProtocol::getLastSentTimeStamp () const inline
Gets the last sent time stamp.
Returns
Last sent time stamp value.
handleIncomingMessageHeader()
virtual void Lib::Ethernet::UserProtocol::handleIncomingMessageHeader (const MessageHeader & header) inline virtual
Handles incoming message header.
Parameters
header Reference to MessageHeader.
Referenced by parse().
handleOututsUpdate()
virtual void Lib::Ethernet::UserProtocol::handleOututsUpdate (uint8_t boardIndex, const uint64_t & value) inline virtual
Outputs update callback.
Parameters
boardIndex Board index.
value Value.
Referenced by parse().
inputsUpdateCallback()
virtual void Lib::Ethernet::UserProtocol::inputsUpdateCallback (uint8_t boardIndex, const uint64_t & value) inline virtual
Inputs update callback.
Parameters
boardIndex Board index.
value Value.
Referenced by parse().
parse()
Error Lib::Ethernet::UserProtocol::parse (const uint8_t * data, size_t size, Command & command, uint8_t & option) inline
Parses the incoming message.
Parameters
data Pointer to incoming message.
size Size of incoming message.
[out] command Reference to store the parsed command.
[out] option Reference to store the parsed option.
Returns
Error code indicating the result of parsing.
Precondition
data must not be nullptr; size must be greater than 0.
Message must start with the correct delimiter.
Payload length must be valid for the command.
Postcondition
command and option are set if parsing is successful.
See also
Message Format
updateNodeActivityCallback()
virtual void Lib::Ethernet::UserProtocol::updateNodeActivityCallback (size_t nodesCount) inline virtual
Update node activity callback.
Parameters
nodesCount Number of nodes.
Referenced by parse().