IAR Library: RTOS::SemaphoreBase Class Reference
RTOS::SemaphoreBase Class Reference abstract
Base class for FreeRTOS semaphore wrappers.
Public Types
using Handle = SemaphoreHandle_t
Public Member Functions
SemaphoreBase (SemaphoreBase &&other) noexcept
Move constructor of SemaphoreBase class.
SemaphoreBase & operator= (SemaphoreBase &&other) noexcept
Move assignment operator of SemaphoreBase class.
SemaphoreBase (const SemaphoreBase &)=delete
Deleted copy constructor of SemaphoreBase class.
SemaphoreBase & operator= (const SemaphoreBase &)=delete
Deleted copy assignment operator of SemaphoreBase class.
virtual ~SemaphoreBase () noexcept
Destructor of SemaphoreBase class.
virtual Handle getHandle () const noexcept
Returns the underlying semaphore handle.
virtual operator Handle & () noexcept
Conversion operator to handle reference.
virtual bool isCreated () const noexcept
Checks if the semaphore is created.
Protected Member Functions
SemaphoreBase () noexcept=default
Default constructor of SemaphoreBase class.
virtual bool create ()=0
Creates the semaphore.
virtual void destroy () noexcept
Destroys the semaphore and releases resources.
virtual bool take (TickType_t timeout=0) noexcept
Takes the semaphore with timeout.
virtual bool takeNow () noexcept
Takes the semaphore without waiting.
virtual bool takeForever () noexcept
Takes the semaphore, waiting forever.
virtual bool give () noexcept
Gives the semaphore.
virtual bool overwrite () noexcept
Overwrites the semaphore (take then give).
virtual bool takeFromISR () noexcept
Takes the semaphore from ISR context.
virtual bool giveFromISR () noexcept
Gives the semaphore from ISR context.
virtual bool overwriteFromISR () noexcept
Overwrites the semaphore from ISR context.
Protected Attributes
Handle handle = nullptr
Detailed Description
Base class for FreeRTOS semaphore wrappers.
Provides common interface and resource management for semaphore types.
Member Typedef Documentation
Handle
using RTOS::SemaphoreBase::Handle = SemaphoreHandle_t
Alias for FreeRTOS semaphore handle.
Constructor & Destructor Documentation
SemaphoreBase() [1/3]
RTOS::SemaphoreBase::SemaphoreBase (SemaphoreBase && other) inline noexcept
Move constructor of SemaphoreBase class.
Parameters
other Source object to move from.
Referenced by RTOS::Semaphore::Semaphore(), SemaphoreBase(), SemaphoreBase(), RTOS::SemaphoreCounting::SemaphoreCounting(), operator=(), and operator=().
SemaphoreBase() [2/3]
RTOS::SemaphoreBase::SemaphoreBase (const SemaphoreBase &) delete
Deleted copy constructor of SemaphoreBase class.
~SemaphoreBase()
virtual RTOS::SemaphoreBase::~SemaphoreBase () inline virtual noexcept
Destructor of SemaphoreBase class.
SemaphoreBase() [3/3]
RTOS::SemaphoreBase::SemaphoreBase () protected default noexcept
Default constructor of SemaphoreBase class.
Member Function Documentation
create()
virtual bool RTOS::SemaphoreBase::create () protected pure virtual
Creates the semaphore.
Returns
true if creation was successful, false otherwise.
Implemented in RTOS::Semaphore, and RTOS::SemaphoreCounting.
Referenced by RTOS::Semaphore::Semaphore(), and create().
destroy()
virtual void RTOS::SemaphoreBase::destroy () inline protected virtual noexcept
Destroys the semaphore and releases resources.
Reimplemented in RTOS::Semaphore.
Referenced by ~SemaphoreBase(), RTOS::Semaphore::destroy(), destroy(), and operator=().
getHandle()
virtual Handle RTOS::SemaphoreBase::getHandle () const inline virtual noexcept
Returns the underlying semaphore handle.
Returns
Semaphore handle.
give()
virtual bool RTOS::SemaphoreBase::give () inline protected virtual noexcept
Gives the semaphore.
Returns
true if given, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::give().
giveFromISR()
virtual bool RTOS::SemaphoreBase::giveFromISR () inline protected virtual noexcept
Gives the semaphore from ISR context.
Returns
true if given, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::giveFromISR().
isCreated()
virtual bool RTOS::SemaphoreBase::isCreated () const inline virtual noexcept
Checks if the semaphore is created.
Returns
true if created, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::isCreated().
operator Handle &()
virtual RTOS::SemaphoreBase::operator Handle & () inline virtual noexcept
Conversion operator to handle reference.
Returns
Reference to semaphore handle.
Reimplemented in RTOS::Semaphore.
operator=() [1/2]
SemaphoreBase & RTOS::SemaphoreBase::operator= (const SemaphoreBase &) delete
Deleted copy assignment operator of SemaphoreBase class.
operator=() [2/2]
SemaphoreBase & RTOS::SemaphoreBase::operator= (SemaphoreBase && other) inline noexcept
Move assignment operator of SemaphoreBase class.
Parameters
other Source object to move from.
Returns
Reference to this object.
Referenced by RTOS::Semaphore::operator=().
overwrite()
virtual bool RTOS::SemaphoreBase::overwrite () inline protected virtual noexcept
Overwrites the semaphore (take then give).
Returns
true if successful, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::overwrite().
overwriteFromISR()
virtual bool RTOS::SemaphoreBase::overwriteFromISR () inline protected virtual noexcept
Overwrites the semaphore from ISR context.
Returns
true if successful, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::overwriteFromISR().
take()
virtual bool RTOS::SemaphoreBase::take (TickType_t timeout = 0) inline protected virtual noexcept
Takes the semaphore with timeout.
Parameters
timeout Timeout in ticks.
Returns
true if taken, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::take(), takeForever(), and takeNow().
takeForever()
virtual bool RTOS::SemaphoreBase::takeForever () inline protected virtual noexcept
Takes the semaphore, waiting forever.
Returns
true if taken, false otherwise.
takeFromISR()
virtual bool RTOS::SemaphoreBase::takeFromISR () inline protected virtual noexcept
Takes the semaphore from ISR context.
Returns
true if taken, false otherwise.
Reimplemented in RTOS::Semaphore.
Referenced by RTOS::Semaphore::takeFromISR().
takeNow()
virtual bool RTOS::SemaphoreBase::takeNow () inline protected virtual noexcept
Takes the semaphore without waiting.
Returns
true if taken, false otherwise.
Member Data Documentation
handle
Handle RTOS::SemaphoreBase::handle = nullptr protected
Underlying FreeRTOS semaphore handle.
Referenced by ~SemaphoreBase(), RTOS::Semaphore::create(), RTOS::SemaphoreCounting::create(), destroy(), RTOS::Semaphore::getCount(), RTOS::SemaphoreCounting::getCount(), getHandle(), RTOS::Semaphore::getState(), give(), giveFromISR(), RTOS::Semaphore::isAvailable(), isCreated(), RTOS::Semaphore::isTaken(), operator Handle &(), operator=(), overwrite(), overwriteFromISR(), take(), and takeFromISR().