IAR Library: Lib::Helper::DateTime::Date Class Reference
Lib::Helper::DateTime::Date Class Reference
Calendar date (day, month, year).
Public Types
enum class DayOfWeek : uint8_t {
MON = 1 ,
TUE ,
WED ,
THU ,
FRI ,
SAT ,
SUN
}
Days of the week.
enum class Month : uint8_t {
JAN = 1 ,
FEB ,
MAR ,
APR ,
MAY ,
JUN ,
JUL ,
AUG ,
SEP ,
OCT ,
NOV ,
DEC
}
Months of the year.
Public Member Functions
Date ()=default
Default constructor of Date class.
Date (uint8_t day, uint8_t month, uint16_t year)
Constructor of Date class.
~Date ()=default
Destructor of Date class.
bool isValid () const
Check if date is valid.
DayOfWeek getDayOfWeek () const
Get day of week for this date.
std::string toString () const
Convert to "DD.MM.YYYY" string.
operator std::string () const
Conversion to std::string.
bool operator== (const Date &other) const
Equality operator of Date class.
bool operator!= (const Date &other) const
Inequality operator of Date class.
Date & operator= (const Date &other)
Assignment operator of Date class.
Static Public Member Functions
static bool isLeapYear (uint32_t year)
Check if year is leap year.
static bool isValid (const Date &date)
Static validity check.
static DayOfWeek getDayOfWeek (const Date &date)
Get day of week for a date.
static std::string getDayOfWeekShortString (const Date &date)
Get short string for day of week.
static std::string getDayOfWeekLongString (const Date &date)
Get long string for day of week.
static uint8_t getDaysInMonth (const Date &date)
Get days in month for a date.
static uint8_t getDaysInMonth (uint8_t month, uint16_t year)
Get days in month for month/year.
static std::string toString (const Date &date)
Static string conversion.
Public Attributes
uint8_t day = 1
uint8_t month = 1
uint16_t year = FIRST_YEAR
Static Public Attributes
static constexpr uint16_t FIRST_YEAR = 2000
Detailed Description
Calendar date (day, month, year).
Includes validation, formatting, and day-of-week calculation.
Examples
Lib::Helper::MoonPhase.
Member Enumeration Documentation
DayOfWeek
enum class Lib::Helper::DateTime::Date::DayOfWeek : uint8_t strong
Days of the week.
Month
enum class Lib::Helper::DateTime::Date::Month : uint8_t strong
Months of the year.
Constructor & Destructor Documentation
Date() [1/2]
Lib::Helper::DateTime::Date::Date () default
Default constructor of Date class.
Referenced by getDayOfWeek(), getDayOfWeekLongString(), getDayOfWeekShortString(), getDaysInMonth(), isValid(), operator!=(), operator=(), operator==(), and toString().
Date() [2/2]
Lib::Helper::DateTime::Date::Date (uint8_t day, uint8_t month, uint16_t year) inline
Constructor of Date class.
Parameters
day Day [1, 31].
month Month [1, 12].
year Year.
~Date()
Lib::Helper::DateTime::Date::~Date () default
Destructor of Date class.
Member Function Documentation
getDayOfWeek() [1/2]
DayOfWeek Lib::Helper::DateTime::Date::getDayOfWeek () const inline
Get day of week for this date.
Returns
DayOfWeek enum value.
Referenced by getDayOfWeek(), getDayOfWeekLongString(), and getDayOfWeekShortString().
getDayOfWeek() [2/2]
DayOfWeek Lib::Helper::DateTime::Date::getDayOfWeek (const Date & date) inline static
Get day of week for a date.
Parameters
date Date to check.
Returns
DayOfWeek enum value.
getDayOfWeekLongString()
std::string Lib::Helper::DateTime::Date::getDayOfWeekLongString (const Date & date) inline static
Get long string for day of week.
Parameters
date Date to check.
Returns
Long string (e.g., "Monday").
getDayOfWeekShortString()
std::string Lib::Helper::DateTime::Date::getDayOfWeekShortString (const Date & date) inline static
Get short string for day of week.
Parameters
date Date to check.
Returns
Short string (e.g., "MON").
Examples
Lib::Helper::DateTime.
getDaysInMonth() [1/2]
uint8_t Lib::Helper::DateTime::Date::getDaysInMonth (const Date & date) inline static
Get days in month for a date.
Parameters
date Date to check.
Returns
Number of days.
Referenced by getDaysInMonth(), and isValid().
getDaysInMonth() [2/2]
uint8_t Lib::Helper::DateTime::Date::getDaysInMonth (uint8_t month, uint16_t year) inline static
Get days in month for month/year.
Parameters
month Month [1, 12].
year Year.
Returns
Number of days.
isLeapYear()
bool Lib::Helper::DateTime::Date::isLeapYear (uint32_t year) inline static
Check if year is leap year.
Parameters
year Year to check.
Returns
true if leap year, false otherwise.
Referenced by getDaysInMonth().
isValid() [1/2]
bool Lib::Helper::DateTime::Date::isValid () const inline
Check if date is valid.
Returns
true if valid, false otherwise.
Referenced by Lib::Helper::DateTime::isValid(), and Lib::System::ProduceDate::write().
isValid() [2/2]
bool Lib::Helper::DateTime::Date::isValid (const Date & date) inline static
Static validity check.
Parameters
date Date to check.
Returns
true if valid, false otherwise.
operator std::string()
Lib::Helper::DateTime::Date::operator std::string () const inline
Conversion to std::string.
Returns
String representation.
operator!=()
bool Lib::Helper::DateTime::Date::operator!= (const Date & other) const inline
Inequality operator of Date class.
Parameters
other Date to compare.
Returns
true if not equal, false otherwise.
operator=()
Date & Lib::Helper::DateTime::Date::operator= (const Date & other) inline
Assignment operator of Date class.
Parameters
other Date to assign.
Returns
Reference to this.
operator==()
bool Lib::Helper::DateTime::Date::operator== (const Date & other) const inline
Equality operator of Date class.
Parameters
other Date to compare.
Returns
true if equal, false otherwise.
toString() [1/2]
std::string Lib::Helper::DateTime::Date::toString () const inline
Convert to "DD.MM.YYYY" string.
Returns
String representation.
Examples
Lib::Helper::DateTime.
Referenced by operator std::string(), Lib::System::Version::Firmware::operator std::string(), and Lib::Helper::DateTime::toString().
toString() [2/2]
std::string Lib::Helper::DateTime::Date::toString (const Date & date) inline static
Static string conversion.
Parameters
date Date to convert.
Returns
String representation.
Member Data Documentation
day
uint8_t Lib::Helper::DateTime::Date::day = 1
Day [1, 31].
Referenced by Date(), Lib::Helper::MoonPhase::calculate(), getDayOfWeek(), isValid(), Lib::Helper::DateTime::operator tm(), operator=(), operator==(), Lib::Helper::DateTime::pack(), Lib::System::Version::Base::stringToDateTime(), and toString().
FIRST_YEAR
uint16_t Lib::Helper::DateTime::Date::FIRST_YEAR = 2000 static constexpr
First supported year.
Referenced by Lib::Helper::DateTime::pack(), and Lib::Helper::DateTime::unpack().
month
uint8_t Lib::Helper::DateTime::Date::month = 1
Month [1, 12].
Referenced by Date(), Lib::Helper::MoonPhase::calculate(), getDayOfWeek(), getDaysInMonth(), isValid(), Lib::Helper::DateTime::operator tm(), operator=(), operator==(), Lib::Helper::DateTime::pack(), Lib::System::Version::Base::stringToDateTime(), and toString().
year
uint16_t Lib::Helper::DateTime::Date::year = FIRST_YEAR
Year.
Referenced by Date(), Lib::Helper::MoonPhase::calculate(), getDayOfWeek(), getDaysInMonth(), isLeapYear(), isValid(), Lib::Helper::DateTime::operator tm(), operator=(), operator==(), Lib::Helper::DateTime::pack(), Lib::System::Version::Base::stringToDateTime(), and toString().