IAR Library: RTOS::StreamBuffer Class Reference
RTOS::StreamBuffer Class Reference
Public Types
using Handle = StreamBufferHandle_t
Public Member Functions
StreamBuffer (StreamBuffer &&other) noexcept
StreamBuffer & operator= (StreamBuffer &&other) noexcept
bool create (size_t bufferSize, size_t triggerLevel)
Create the stream buffer.
void destroy ()
Destroy the stream buffer.
size_t send (const void *source, size_t length, TickType_t timeout=0)
Send data to the stream buffer.
size_t sendNow (const void *source, size_t length)
Send data without waiting.
size_t sendForever (const void *source, size_t length)
Send data, wait forever.
size_t sendFromISR (const void *source, size_t length)
Send data from ISR.
size_t receive (void *destination, size_t maxLength, TickType_t timeout=0)
Receive data from the stream buffer.
size_t receiveNow (void *destination, size_t maxLength)
Receive data without waiting.
size_t receiveForever (void *destination, size_t maxLength)
Receive data, wait forever.
size_t receiveFromISR (void *destination, size_t maxLength)
Receive data from ISR.
size_t getBytesAvailable () const
Get number of bytes available.
size_t getSpacesAvailable () const
Get number of spaces available.
bool setTriggerLevel (size_t triggerLevel)
Set the trigger level.
bool reset ()
Reset the stream buffer.
bool isEmpty () const
Check if the buffer is empty.
bool isFull () const
Check if the buffer is full.
bool hasData () const
Check if the buffer has data.
bool hasSpace () const
Check if the buffer has space.
size_t getCapacity () const
Get the buffer capacity.
size_t getUtilizationPercent () const
Get utilization percent.
Handle getHandle () const
Get the handle.
operator Handle & ()
Handle conversion operator.
bool isCreated () const
Check if the buffer is created.
Detailed Description
Examples
RTOS::StreamBuffer.
Member Function Documentation
create()
bool RTOS::StreamBuffer::create (size_t bufferSize, size_t triggerLevel) inline
Create the stream buffer.
Parameters
bufferSize Size of the buffer.
triggerLevel Trigger level for notifications.
Returns
true if creation was successful, false otherwise.
Examples
RTOS::StreamBuffer.
destroy()
void RTOS::StreamBuffer::destroy () inline
Destroy the stream buffer.
Examples
RTOS::StreamBuffer.
getBytesAvailable()
size_t RTOS::StreamBuffer::getBytesAvailable () const inline
Get number of bytes available.
Returns
Number of bytes available.
Referenced by getCapacity(), getUtilizationPercent(), and hasData().
getCapacity()
size_t RTOS::StreamBuffer::getCapacity () const inline
Get the buffer capacity.
Returns
Buffer capacity.
Referenced by getUtilizationPercent().
getHandle()
Handle RTOS::StreamBuffer::getHandle () const inline
Get the handle.
Returns
Stream buffer handle.
getSpacesAvailable()
size_t RTOS::StreamBuffer::getSpacesAvailable () const inline
Get number of spaces available.
Returns
Number of spaces available.
Referenced by getCapacity(), and hasSpace().
getUtilizationPercent()
size_t RTOS::StreamBuffer::getUtilizationPercent () const inline
Get utilization percent.
Returns
Utilization percent.
hasData()
bool RTOS::StreamBuffer::hasData () const inline
Check if the buffer has data.
Returns
true if data is available, false otherwise.
hasSpace()
bool RTOS::StreamBuffer::hasSpace () const inline
Check if the buffer has space.
Returns
true if space is available, false otherwise.
isCreated()
bool RTOS::StreamBuffer::isCreated () const inline
Check if the buffer is created.
Returns
true if created, false otherwise.
isEmpty()
bool RTOS::StreamBuffer::isEmpty () const inline
Check if the buffer is empty.
Returns
true if empty, false otherwise.
isFull()
bool RTOS::StreamBuffer::isFull () const inline
Check if the buffer is full.
Returns
true if full, false otherwise.
operator Handle &()
RTOS::StreamBuffer::operator Handle & () inline
Handle conversion operator.
Returns
Reference to the handle.
receive()
size_t RTOS::StreamBuffer::receive (void * destination, size_t maxLength, TickType_t timeout = 0) inline
Receive data from the stream buffer.
Parameters
destination Pointer to the destination buffer.
maxLength Maximum number of bytes to receive.
timeout Timeout in ticks.
Returns
Number of bytes received.
Examples
RTOS::StreamBuffer.
Referenced by receiveForever(), and receiveNow().
receiveForever()
size_t RTOS::StreamBuffer::receiveForever (void * destination, size_t maxLength) inline
Receive data, wait forever.
Parameters
destination Pointer to the destination buffer.
maxLength Maximum number of bytes to receive.
Returns
Number of bytes received.
receiveFromISR()
size_t RTOS::StreamBuffer::receiveFromISR (void * destination, size_t maxLength) inline
Receive data from ISR.
Parameters
destination Pointer to the destination buffer.
maxLength Maximum number of bytes to receive.
Returns
Number of bytes received.
receiveNow()
size_t RTOS::StreamBuffer::receiveNow (void * destination, size_t maxLength) inline
Receive data without waiting.
Parameters
destination Pointer to the destination buffer.
maxLength Maximum number of bytes to receive.
Returns
Number of bytes received.
reset()
bool RTOS::StreamBuffer::reset () inline
Reset the stream buffer.
Returns
true if successful, false otherwise.
send()
size_t RTOS::StreamBuffer::send (const void * source, size_t length, TickType_t timeout = 0) inline
Send data to the stream buffer.
Parameters
source Pointer to the data source.
length Number of bytes to send.
timeout Timeout in ticks.
Returns
Number of bytes sent.
Examples
RTOS::StreamBuffer.
Referenced by sendForever(), and sendNow().
sendForever()
size_t RTOS::StreamBuffer::sendForever (const void * source, size_t length) inline
Send data, wait forever.
Parameters
source Pointer to the data source.
length Number of bytes to send.
Returns
Number of bytes sent.
sendFromISR()
size_t RTOS::StreamBuffer::sendFromISR (const void * source, size_t length) inline
Send data from ISR.
Parameters
source Pointer to the data source.
length Number of bytes to send.
Returns
Number of bytes sent.
sendNow()
size_t RTOS::StreamBuffer::sendNow (const void * source, size_t length) inline
Send data without waiting.
Parameters
source Pointer to the data source.
length Number of bytes to send.
Returns
Number of bytes sent.
setTriggerLevel()
bool RTOS::StreamBuffer::setTriggerLevel (size_t triggerLevel) inline
Set the trigger level.
Parameters
triggerLevel New trigger level.
Returns
true if successful, false otherwise.