IAR Library: Lib::Digi::API::ApplicationBase Class Reference
Lib::Digi::API::ApplicationBase Class Reference abstract
ApplicationBase class for Digi API applications.
Public Member Functions
ApplicationBase (const Core::Module::Config &config)
Constructor of ApplicationBase class.
virtual ~ApplicationBase ()
Destructor of ApplicationBase class.
void pause () override
Pauses the service.
void resume () override
Resumes a service that was previously paused.
Lib::Digi::Core::Module & getModule ()
Gets the reference to the module.
virtual bool start (bool pauseAfterStart)
Starts the Digi application and initializes the services.
virtual bool sendData (const std::vector< uint8_t > &buffer)
Sends the data frame to remote host.
virtual bool getModulePresent () const
Gets the module present state.
virtual bool handleIncomingMessage (const std::vector< uint8_t > &buffer)=0
Handle incoming message event.
virtual void handleOutgoingMessage (std::vector< uint8_t > &buffer)=0
Handle outgoing message event.
virtual void handleTaskTickEvent ()=0
Update Data Callback.
virtual void beginUpdate ()=0
Task initialize callback.
virtual void update ()=0
Task loop callback.
Public Attributes
Connection connection
Core::Diagnostic & diagnostic
Core::ModemStatus modemStatus
Service::SpectrumAnalyzer spectrumAnalyzer
Service::Parameters parameters
Service::NetworkDiscovery networkDiscovery
Service::ChannelScanner channelScanner
Protected Types
enum class Error {
NONE ,
NO_RESPONSE_FROM_MODULE
}
Errors for ApplicationBase.
enum class State {
NO_INIT ,
INIT ,
RUNNING ,
PAUSE ,
ERROR
}
Service state for ApplicationBase.
using Config = Core::Module::Config
Protected Attributes
uint8_t messageFrameId = 0
RTOS::Queue< Core::Message > queueRxMessage
RTOS::Queue< Lib::Digi::Core::Frame0x89::DeliveryStatus > queueTransmitDeliveryStatus
Static Protected Attributes
static constexpr uint32_t MAX_RESPONSE_TIME = 50
static constexpr uint32_t PAUSE_BETWEEN_MESSAGES_IN_DISCONNECTED = 500
static constexpr uint32_t CONNECTION_TIMEOUT = 750
Detailed Description
ApplicationBase class for Digi API applications.
Base class for Digi API client/server applications. Provides lifecycle, service, and message management, including service registration, module management, and message handling.
Member Enumeration Documentation
Error
enum class Lib::Digi::API::ApplicationBase::Error strong protected
Errors for ApplicationBase.
Enumerator
NONE
No error.
NO_RESPONSE_FROM_MODULE
No response from the module.
State
enum class Lib::Digi::API::ApplicationBase::State strong protected
Service state for ApplicationBase.
Enumerator
NO_INIT
Service not initialized.
INIT
Service initialized.
RUNNING
Service running.
PAUSE
Service paused.
ERROR
Service error.
Constructor & Destructor Documentation
ApplicationBase()
Lib::Digi::API::ApplicationBase::ApplicationBase (const Core::Module::Config & config) inline explicit
Constructor of ApplicationBase class.
Parameters
config Reference to configuration.
Referenced by Lib::Digi::API::ClientBase::ClientBase(), and Lib::Digi::API::ServerBase::ServerBase().
~ApplicationBase()
virtual Lib::Digi::API::ApplicationBase::~ApplicationBase () inline virtual
Destructor of ApplicationBase class.
Member Function Documentation
beginUpdate()
virtual void Lib::Digi::API::ApplicationBase::beginUpdate () pure virtual
Task initialize callback.
getModule()
Lib::Digi::Core::Module & Lib::Digi::API::ApplicationBase::getModule () inline
Gets the reference to the module.
Returns
Reference to the Digi module.
getModulePresent()
virtual bool Lib::Digi::API::ApplicationBase::getModulePresent () const inline virtual
Gets the module present state.
Returns
true if the module is present, false otherwise.
Reimplemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
Referenced by Lib::Digi::API::ClientBase::getModulePresent(), and Lib::Digi::API::ServerBase::getModulePresent().
handleIncomingMessage()
virtual bool Lib::Digi::API::ApplicationBase::handleIncomingMessage (const std::vector< uint8_t > & buffer) pure virtual
Handle incoming message event.
Parameters
buffer Incoming message.
Returns
true if parsing the message was successful, false otherwise.
Implemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
handleOutgoingMessage()
virtual void Lib::Digi::API::ApplicationBase::handleOutgoingMessage (std::vector< uint8_t > & buffer) pure virtual
Handle outgoing message event.
Parameters
buffer Reference to vector where the result will be stored.
Implemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
handleTaskTickEvent()
virtual void Lib::Digi::API::ApplicationBase::handleTaskTickEvent () pure virtual
Update Data Callback.
Occurs with each transaction and serves to synchronize the data with the user interface.
Implemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
pause()
void Lib::Digi::API::ApplicationBase::pause () inline override virtual
Pauses the service.
Implements Lib::Digi::API::Pause.
Referenced by Lib::Digi::API::ClientBase::start(), and Lib::Digi::API::ServerBase::start().
resume()
void Lib::Digi::API::ApplicationBase::resume () inline override virtual
Resumes a service that was previously paused.
Implements Lib::Digi::API::Pause.
sendData()
virtual bool Lib::Digi::API::ApplicationBase::sendData (const std::vector< uint8_t > & buffer) inline virtual
Sends the data frame to remote host.
Parameters
buffer Reference to user message vector.
Returns
true if data was transmitted successfully, false otherwise.
Reimplemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
Referenced by Lib::Digi::API::ClientBase::sendData(), and Lib::Digi::API::ServerBase::sendData().
start()
virtual bool Lib::Digi::API::ApplicationBase::start (bool pauseAfterStart) inline virtual
Starts the Digi application and initializes the services.
Parameters
pauseAfterStart If true, pauses after start.
Returns
true if started successfully, false otherwise.
Reimplemented in Lib::Digi::API::ClientBase, and Lib::Digi::API::ServerBase.
Referenced by Lib::Digi::API::ClientBase::start(), and Lib::Digi::API::ServerBase::start().
update()
virtual void Lib::Digi::API::ApplicationBase::update () pure virtual
Task loop callback.
Member Data Documentation
channelScanner
Service::ChannelScanner Lib::Digi::API::ApplicationBase::channelScanner
Channel scanner service.
Referenced by start().
connection
Connection Lib::Digi::API::ApplicationBase::connection
Connection instance.
diagnostic
Core::Diagnostic& Lib::Digi::API::ApplicationBase::diagnostic
Diagnostic data reference.
Referenced by sendData().
messageFrameId
uint8_t Lib::Digi::API::ApplicationBase::messageFrameId = 0 protected
Transmit Frame ID.
Referenced by sendData(), Lib::Digi::API::ClientBase::start(), and Lib::Digi::API::ServerBase::start().
modemStatus
Core::ModemStatus Lib::Digi::API::ApplicationBase::modemStatus
Modem status service.
Referenced by start().
networkDiscovery
Service::NetworkDiscovery Lib::Digi::API::ApplicationBase::networkDiscovery
Network discovery service.
Referenced by start().
parameters
Service::Parameters Lib::Digi::API::ApplicationBase::parameters
Module parameters service.
Referenced by start().
queueRxMessage
RTOS::Queue<Core::Message> Lib::Digi::API::ApplicationBase::queueRxMessage protected
Queue for received messages.
queueTransmitDeliveryStatus
RTOS::Queue<Lib::Digi::Core::Frame0x89::DeliveryStatus> Lib::Digi::API::ApplicationBase::queueTransmitDeliveryStatus protected
Queue for transmit delivery status.
spectrumAnalyzer
Service::SpectrumAnalyzer Lib::Digi::API::ApplicationBase::spectrumAnalyzer
Spectrum analyzer service.
Referenced by start().