IAR Library: Lib::Math::CubicInterpolation< T_VALUE, T_INPUT > Class Template Reference
Lib::Math::CubicInterpolation< T_VALUE, T_INPUT > Class Template Reference final
Cubic spline interpolation class for embedded applications.
Classes
struct Point
Data point structure for interpolation table.
Public Types
enum class BoundaryType : uint8_t {
NATURAL ,
CLAMPED
}
Boundary condition types for cubic spline interpolation.
Public Member Functions
constexpr CubicInterpolation ()
Default constructor of CubicInterpolation class.
template<size_t N>
constexpr CubicInterpolation (const std::array< Point, N > &pointArray, BoundaryType boundary=BoundaryType::NATURAL, T_VALUE leftDeriv=T_VALUE{}, T_VALUE rightDeriv=T_VALUE{})
Constructor of CubicInterpolation class.
bool addPoint (const Point &point)
Add a data point to the interpolation table.
bool addPoint (T_INPUT x, T_VALUE y)
Add a data point to the interpolation table.
void clear ()
Clear all points from the interpolation table.
void setBoundaryConditions (BoundaryType boundary, T_VALUE leftDeriv=T_VALUE{}, T_VALUE rightDeriv=T_VALUE{})
Set boundary conditions for spline interpolation.
constexpr size_t getPointCount () const
Get the number of points in the interpolation table.
constexpr bool isEmpty () const
Check if the interpolation table is empty.
T_VALUE interpolate (T_INPUT x)
Perform cubic spline interpolation for a given input value.
T_VALUE getDerivative (T_INPUT x)
Get the first derivative at a given input value.
const Point & getPoint (size_t index) const
Get a point from the interpolation table.
void sortPoints ()
Sort points by x coordinate.
Detailed Description
template<typename T_VALUE, typename T_INPUT = T_VALUE>
class Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >
Cubic spline interpolation class for embedded applications.
The CubicInterpolation class template provides smooth cubic interpolation between data points using natural or clamped boundary conditions. It uses a tridiagonal matrix solution for efficient spline coefficient calculation and supports up to MAX_POINTS data points. All internal state variables are initialized and updated according to standard cubic spline equations.
Template Parameters
T_VALUE Numeric type for values (float or double).
T_INPUT Numeric type for input coordinates (typically same as T_VALUE).
Member Enumeration Documentation
BoundaryType
template<typename T_VALUE, typename T_INPUT = T_VALUE> enum class Lib::Math::CubicInterpolation::BoundaryType : uint8_t strong
Boundary condition types for cubic spline interpolation.
Specifies spline behavior at boundaries.
Enumerator
NATURAL
Natural boundary (second derivative = 0 at endpoints).
CLAMPED
Clamped boundary (first derivative specified at endpoints).
Constructor & Destructor Documentation
CubicInterpolation() [1/2]
template<typename T_VALUE, typename T_INPUT = T_VALUE> Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::CubicInterpolation () inline constexpr
Default constructor of CubicInterpolation class.
CubicInterpolation() [2/2]
template<typename T_VALUE, typename T_INPUT = T_VALUE> template<size_t N> Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::CubicInterpolation (const std::array< Point, N > & pointArray, BoundaryType boundary = BoundaryType::NATURAL, T_VALUE leftDeriv = T_VALUE{}, T_VALUE rightDeriv = T_VALUE{}) inline constexpr
Constructor of CubicInterpolation class.
Template Parameters
N Number of points.
Parameters
pointArray Array of interpolation points.
boundary Boundary condition type.
leftDeriv Left boundary derivative (clamped).
rightDeriv Right boundary derivative (clamped).
Member Function Documentation
addPoint() [1/2]
template<typename T_VALUE, typename T_INPUT = T_VALUE> bool Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::addPoint (const Point & point) inline
Add a data point to the interpolation table.
Parameters
point Point to add.
Returns
true if added, false if table is full.
addPoint() [2/2]
template<typename T_VALUE, typename T_INPUT = T_VALUE> bool Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::addPoint (T_INPUT x, T_VALUE y) inline
Add a data point to the interpolation table.
Parameters
x Input coordinate value.
y Output value for x.
Returns
true if added, false if table is full.
Referenced by Lib::Math::CubicInterpolation< float, float >::addPoint().
clear()
template<typename T_VALUE, typename T_INPUT = T_VALUE> void Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::clear () inline
Clear all points from the interpolation table.
getDerivative()
template<typename T_VALUE, typename T_INPUT = T_VALUE> T_VALUE Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::getDerivative (T_INPUT x) inline
Get the first derivative at a given input value.
Parameters
x Input value.
Returns
First derivative value.
getPoint()
template<typename T_VALUE, typename T_INPUT = T_VALUE> const Point & Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::getPoint (size_t index) const inline
Get a point from the interpolation table.
Parameters
index Index of the point.
Returns
Reference to the point.
getPointCount()
template<typename T_VALUE, typename T_INPUT = T_VALUE> size_t Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::getPointCount () const inline constexpr
Get the number of points in the interpolation table.
Returns
Number of points.
interpolate()
template<typename T_VALUE, typename T_INPUT = T_VALUE> T_VALUE Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::interpolate (T_INPUT x) inline
Perform cubic spline interpolation for a given input value.
Parameters
x Input value.
Returns
Interpolated output value.
isEmpty()
template<typename T_VALUE, typename T_INPUT = T_VALUE> bool Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::isEmpty () const inline constexpr
Check if the interpolation table is empty.
Returns
true if empty, false otherwise.
setBoundaryConditions()
template<typename T_VALUE, typename T_INPUT = T_VALUE> void Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::setBoundaryConditions (BoundaryType boundary, T_VALUE leftDeriv = T_VALUE{}, T_VALUE rightDeriv = T_VALUE{}) inline
Set boundary conditions for spline interpolation.
Parameters
boundary Boundary condition type.
leftDeriv Left boundary derivative (clamped).
rightDeriv Right boundary derivative (clamped).
sortPoints()
template<typename T_VALUE, typename T_INPUT = T_VALUE> void Lib::Math::CubicInterpolation< T_VALUE, T_INPUT >::sortPoints () inline
Sort points by x coordinate.
Referenced by Lib::Math::CubicInterpolation< float, float >::getDerivative(), and Lib::Math::CubicInterpolation< float, float >::interpolate().